### ISSUE TITLE
Setting a transparent background seems impossible

### ISSUE THREAD

**Issue by DanGTZ** [highcharts/highcharts-android#1]
I'm trying to set a transparent background.
I tried : 

- options.chart.backgroundColor = HIColor.initWithRGBA(255, 255, 255, 0.0);

- options.chart.plotBackgroundColor = HIColor.initWithRGBA(255, 255, 255, 0.0);

- setBackgroundColor(Color.TRANSPARENT); // on the HIChartView object

- android:background="@null", on the layout of the view

Nothing of them works I all display a white background. Any idea of how to set a transparent background?

**Comment by soommy12** [comment]
Hello @DanGTZ ! First of all you need to instantiate the chart object:

options.chart = new HIChart();
options.chart.backgroundColor = HIColor.initWithRGBA(255, 255, 255, 0.0);

Note that if you set the background to transparent and your chart title text is white you won't be able to see those text when you export the chart.

**Comment by DanGTZ** [comment]
Hi @soommy12 ,
Of course I instantiated the HIChart object exactly like you did. If it was not the car I would get a NullPointerException when trying to access backgroundColor field.
My tests has been done on Nexus 6 API 27 Emulator, and I confirm that there the view behaves like it has a white background, behind the chart background.

**Comment by DanGTZ** [comment]
Hello @soommy12 , do you plan to look at this issue soon? Do you need more information?
I'm trying to make the background of my chart transparent (alpha 0.0) so it can display the dark grey/blue color as you can see on this screenshot. But it seems that there is a white background set by default, behind the chart background. In the layout XML, I tried to force the background of the HIChartView to the dark grey/blue color, and I also tried to set it to "@null" for transparency : both produces the same white background.
![image](https://user-images.githubusercontent.com/805312/37100382-2bfd93fc-21f9-11e8-9caa-8cf060e622df.png)

**Comment by soommy12** [comment]
You were right! The wrapper view was white by default. Thank you for noticing that bug. I've made a fix, the solution from first comment will work now :smile:

**Comment by DanGTZ** [comment]
Thanks for the fix! Tested and approved!
