### ISSUE TITLE
Marker from drawable resource.

### ISSUE THREAD

**Issue by nareshkatta99** [highcharts/highcharts-android#10]
The tool tip I want to use is in the drawable resource folder.

I was able to create the drawable path from resource folder using the following reference https://stackoverflow.com/a/31264676/4235267.

I tried to use that path. But no success.

**Comment by sebastianbochan** [comment]
Hi @nareshkatta99,
Thank you for contacting us. The github is our bug tracker, so for general [support](http://www.highcharts.com/support) questions please use stackoverflow / forum or email.
