### ISSUE TITLE
HIOptions not attached. Chart won't render without options.

### ISSUE THREAD

**Issue by vinayakmestri** [highcharts/highcharts-android#101]
I am implementing in Android getting same error.
Piechart wont render first time. but it renders when pressing home button and again opening the app.

**Comment by vinayakmestri** [comment]
package com.jawksoftwares.investyadnya.fragments.DashBoard;


import android.annotation.TargetApi;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.content.ContextCompat;
import android.support.v4.widget.SwipeRefreshLayout;
import android.support.v7.widget.CardView;
import android.text.Html;
import android.text.SpannableStringBuilder;
import android.text.method.LinkMovementMethod;
import android.text.style.ClickableSpan;
import android.text.style.URLSpan;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CompoundButton;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import com.github.florent37.expansionpanel.ExpansionLayout;
import com.github.mikephil.charting.charts.BarChart;
import com.github.mikephil.charting.charts.PieChart;
import com.github.mikephil.charting.components.Legend;
import com.github.mikephil.charting.components.LegendEntry;
import com.github.mikephil.charting.components.XAxis;
import com.github.mikephil.charting.components.YAxis;
import com.github.mikephil.charting.data.BarData;
import com.github.mikephil.charting.data.BarDataSet;
import com.github.mikephil.charting.data.BarEntry;
import com.github.mikephil.charting.interfaces.datasets.IBarDataSet;
import com.gun0912.tedpermission.PermissionListener;
import com.highsoft.highcharts.common.hichartsclasses.HIChart;
import com.highsoft.highcharts.common.hichartsclasses.HICredits;
import com.highsoft.highcharts.common.hichartsclasses.HIDataLabelsOptionsObject;
import com.highsoft.highcharts.common.hichartsclasses.HIExporting;
import com.highsoft.highcharts.common.hichartsclasses.HIOptions;
import com.highsoft.highcharts.common.hichartsclasses.HIPie;
import com.highsoft.highcharts.common.hichartsclasses.HISeries;
import com.highsoft.highcharts.common.hichartsclasses.HISubtitle;
import com.highsoft.highcharts.common.hichartsclasses.HITitle;
import com.highsoft.highcharts.common.hichartsclasses.HITooltip;
import com.highsoft.highcharts.core.HIChartView;
import com.jawksoftwares.investyadnya.R;
import com.jawksoftwares.investyadnya.bean.ConfigBean;
import com.jawksoftwares.investyadnya.common.CommonConstants;
import com.jawksoftwares.investyadnya.common.CommonUtil;
import com.jawksoftwares.investyadnya.fragments.DashBoard.Dialog.AppUpdateDialog;
import com.jawksoftwares.investyadnya.fragments.DashBoard.Dialog.AssetDetailDialog;
import com.jawksoftwares.investyadnya.fragments.DashBoard.Dialog.PaymentDetailDialog;
import com.jawksoftwares.investyadnya.investyadnya.HomeActivity;
import com.jawksoftwares.investyadnya.model.DashBoardModel;
import com.jawksoftwares.investyadnya.model.GoalDetailList;
import com.jawksoftwares.investyadnya.model.assetsModels.EPFAsset;
import com.jawksoftwares.investyadnya.model.assetsModels.EquityAsset;
import com.jawksoftwares.investyadnya.model.assetsModels.FixedDepositAsset;
import com.jawksoftwares.investyadnya.model.assetsModels.MutualFundAsset;
import com.jawksoftwares.investyadnya.model.assetsModels.NPSAsset;
import com.jawksoftwares.investyadnya.model.assetsModels.OtherAsset;
import com.jawksoftwares.investyadnya.model.assetsModels.PPFAsset;
import com.jawksoftwares.investyadnya.network.ApiClient;
import com.jawksoftwares.investyadnya.util.SharedPreferenceController;
import com.jawksoftwares.investyadnya.util.Util;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;

import butterknife.BindView;
import butterknife.ButterKnife;
import butterknife.OnCheckedChanged;
import butterknife.OnClick;

/**
 * A simple {@link Fragment} subclass.
 */
public class DashBoardFragment extends Fragment implements DashBoardView, CompoundButton.OnCheckedChangeListener, View.OnClickListener, SwipeRefreshLayout.OnRefreshListener {


    @BindView(R.id.networthTextView)
    TextView networthTextView;
    @BindView(R.id.assetsTextView)
    TextView assetsTextView;
    @BindView(R.id.liabilitiesTextView)
    TextView liabilitiesTextView;
    @BindView(R.id.subscriptionTextView)
    TextView subscriptionTextView;
    @BindView(R.id.goalsListLayout)
    LinearLayout goalsListLayout;
    @BindView(R.id.totalAssetsTextView)
    TextView totalAssetsTextView;
    @BindView(R.id.monthlyRadioButton)
    RadioButton monthlyRadioButton;
    @BindView(R.id.yearlyRadioButton)
    RadioButton yearlyRadioButton;
    @BindView(R.id.assetDetailButton)
    Button assetDetailButton;
    @BindView(R.id.barLayout)
    CardView barLayout;
    @BindView(R.id.scrollViewLayout)
    ScrollView scrollViewLayout;
    @BindView(R.id.refreshDashboard)
    SwipeRefreshLayout refreshDashboard;
    @BindView(R.id.notAddedAssetLayout)
    LinearLayout notAddedAssetLayout;
    @BindView(R.id.subscribeButton)
    TextView subscribeButton;
    @BindView(R.id.eBooksLayout)
    LinearLayout eBooksLayout;
    @BindView(R.id.eBooksNoData)
    TextView eBooksNoData;
    @BindView(R.id.expansionLayoutEBooks)
    ExpansionLayout expansionLayoutEBooks;

    @BindView(R.id.hc)
    HIChartView chartView;
    HIOptions options;
    ArrayList<Float> values = new ArrayList<>();
    ArrayList<String> tags = new ArrayList<>();
    private PieChart pieChart;
    private BarChart barChart;
    private Context context;
    private DashBoardModel dashBoardModel;
    private DashBoardPresenter dashBoardPresenter;
    boolean isDetails = false;
    Integer bookId;
    String bookName;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.fragment_dash_board, container, false);
        context = getActivity();
        ButterKnife.bind(this, view);
        dashBoardPresenter = new DashBoardPresenterImpl(getActivity(), this, new DashBoardInteractorImpl());
        refreshDashboard.setOnRefreshListener(this);
        barChart = view.findViewById(R.id.barChart);
        if (checkVersionUpdate()) {
            ((HomeActivity) getActivity()).getUserProfileCompleteStatus();
            refreshDashBoard();
        }
        return view;
    }

    private boolean checkVersionUpdate() {
        try {
            ConfigBean configBean = SharedPreferenceController.getInstance().getConfig(context);
            if (configBean != null) {
                if (!configBean.getVersionCode().equals(configBean.getOldVersionCode()))
                    showAppUpdateDialog(configBean.isCompulsaryUpdate());
                if (configBean.isCompulsaryUpdate())
                    return false;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return true;
    }

    **public void initPieData(ArrayList<Float> pieChartData, ArrayList<String> tags) {
        HISubtitle title = new HISubtitle();
        title.setText("");
        chartView.setTitle(title, title, true);

        options = new HIOptions();
        HIChart chart = new HIChart();
        chart.setType("pie");
        chart.setPlotShadow(false);
        HIExporting hiExporting = new HIExporting();
        hiExporting.setEnabled(false);
        options.setExporting(hiExporting);
        options.setChart(chart);
        chartView.setOptions(options);
        ArrayList<String> colors = new ArrayList<>();
        colors.add("#95CEFF");
        colors.add("#e15d62");
        colors.add("#b71c1c");
        colors.add("#aa00ff");
        colors.add("#004d40");
        colors.add("#cddc39");
        colors.add("#e65100");
        colors.add("#bf360c");
        colors.add("#795548");
        colors.add("#e57373");
        colors.add("#b2dfdb");
        colors.add("#66bb6a");
        colors.add("#3e2723");
        colors.add("#607d8b");
        options.setColors(colors);

        HITitle hiTitle = new HITitle();
        hiTitle.setText("");
        options.setTitle(hiTitle);


        HICredits hiCredits = new HICredits();
        hiCredits.setEnabled(false);
        hiCredits.setText("");
        options.setCredits(hiCredits);


        HITooltip tooltip = new HITooltip();
        tooltip.setPointFormat("{series.name}: <b>{point.percentage:.1f}%</b><br>Amount: {point.y}");
        options.setTooltip(tooltip);
        ArrayList<HashMap<String, Object>> data = new ArrayList<>();
        HISeries hiSeries = new HIPie();
        hiSeries.setName("Allocation");
        HIDataLabelsOptionsObject hiDataLabelsOptionsObject = new HIDataLabelsOptionsObject();
        hiDataLabelsOptionsObject.setFormat("{point.name}: <br>" + "<p>Rs. {point.y}</p>");
        hiSeries.setDataLabels(hiDataLabelsOptionsObject);
        hiSeries.setAnimationLimit(0);
        for (int i = 0; i < pieChartData.size(); i++) {
            HashMap<String, Object> object = new HashMap<>();
            object.put("name", tags.get(i));
            object.put("y", pieChartData.get(i));
            data.add(object);
        }
        hiSeries.setData(data);
        hiSeries.animate(false);
        options.setSeries(new ArrayList<>(Collections.singletonList(hiSeries)));
        chartView.setFocusable(false);
        chartView.post(new Runnable() {
            @Override
            public void run() {
                chartView.setOptions(options);
                chartView.setFocusable(false);
                chartView.setFocusable(true);
            }
        });


    }

    @Override
    public void onResume() {
        super.onResume();
        chartView.setFocusable(false);
        chartView.setFocusable(true);
    }

    public void initBarChart() {
        barChart.setDrawBarShadow(false);
        barChart.setDrawValueAboveBar(true);
        barChart.getDescription().setEnabled(false);
        barChart.setPinchZoom(false);
        barChart.setDrawGridBackground(false);
        barChart.setFitBars(true);
        barChart.setExtraBottomOffset(15f);

        XAxis xAxis = barChart.getXAxis();
        xAxis.setEnabled(false);

        YAxis leftAxis = barChart.getAxisLeft();
        leftAxis.setEnabled(false);

        YAxis rightAxis = barChart.getAxisRight();
        rightAxis.setEnabled(false);

        Legend l = barChart.getLegend();
        l.setVerticalAlignment(Legend.LegendVerticalAlignment.BOTTOM);
        l.setHorizontalAlignment(Legend.LegendHorizontalAlignment.CENTER);
        l.setOrientation(Legend.LegendOrientation.HORIZONTAL);
        //l.setDrawInside(false);
        l.setForm(Legend.LegendForm.SQUARE);
        l.setTextSize(11f);
        l.setXOffset(3f);
        l.setWordWrapEnabled(true);
        barChart.invalidate();

    }**

    private void refreshDashBoard() {
        dashBoardPresenter.refreshDashBoardData();
    }

 

    @Override
    public void getDashBoardData(DashBoardModel dashBoardModel) {
        showProgress();
        this.dashBoardModel = dashBoardModel;
        if (SharedPreferenceController.getInstance().getUserPlans(getActivity()) == null || SharedPreferenceController.getInstance().getUserPlans(getActivity()).isEmpty()) {
            isDetails = false;
            subscriptionTextView.setText("Not Subscribed");
        } else {
            String plans = "";
            for (String plan : SharedPreferenceController.getInstance().getUserPlans(getActivity())) {
                if (Util.isEmpty(plans))
                    plans += ", ";
                if (plan.equals("VIDEO_SUBSCRIPTION_PLAN"))
                    plan = "STOCK PLAN";
                plans += plan.replace("_", " ");
            }
            subscriptionTextView.setText(plans);
            isDetails = true;
            subscribeButton.setText("Details");
        }
        subscribeButton.setVisibility(View.VISIBLE);
        if (this.dashBoardModel != null) {
            refreshUI();
            refreshEBooks();
        }
        hideProgress();
    }

    @Override
    public void showProgress() {
        if (getActivity() instanceof HomeActivity) {
            ((HomeActivity) getActivity()).showProgress();
        }
    }

    @Override
    public void hideProgress() {
        refreshDashboard.setRefreshing(false);
        if (getActivity() instanceof HomeActivity) {
            ((HomeActivity) getActivity()).hideProgress();
        }
    }

    **void refreshUI() {
        values.clear();
        tags.clear();
        networthTextView.setText("₹ " + CommonUtil.rupeeFormatFromLong(dashBoardModel.getNetworth()));
        assetsTextView.setText("₹ " + CommonUtil.rupeeFormatFromLong(dashBoardModel.getAssets()));
        totalAssetsTextView.setText("Total Assets : ₹ " + CommonUtil.rupeeFormatFromLong(dashBoardModel.getAssets()));
        liabilitiesTextView.setText("₹ " + CommonUtil.rupeeFormatFromLong(dashBoardModel.getLiabilities()));


        if (dashBoardModel.getAssets() > 0) {
            chartView.setVisibility(View.VISIBLE);
            notAddedAssetLayout.setVisibility(View.GONE);
        } else {
            notAddedAssetLayout.setVisibility(View.VISIBLE);
            chartView.setVisibility(View.GONE);
        }

        try {
            float ppf = 0f;
            for (PPFAsset ppfAsset : dashBoardModel.getAllAssets().getpPFAsset()) {
                ppf += ppfAsset.getClosingBalance();
            }
            if (ppf != 0) {
                tags.add("PPF");
                values.add(ppf);
            }
        } catch (NullPointerException e) {
            e.printStackTrace();
        }
        try {
            float nps = 0f;
            for (NPSAsset npsAsset : dashBoardModel.getAllAssets().getnPSAsset()) {
                nps += npsAsset.getClosingBalance();
            }
            if (nps != 0) {
                values.add(nps);
                tags.add("NPS");
            }
        } catch (NullPointerException e) {
            e.printStackTrace();
        }

        try {
            float epf = 0f;
            for (EPFAsset epfAsset : dashBoardModel.getAllAssets().getePFAsset()) {
                epf += epfAsset.getCurrentBalance();
            }
            if (epf != 0) {
                values.add(epf);
                tags.add("EPF");
            }
        } catch (NullPointerException e) {
            e.printStackTrace();
        }
        try {
            float equity = 0f;
            for (EquityAsset equityAsset : dashBoardModel.getAllAssets().getEquityAsset()) {
                equity += equityAsset.getCurrentAmount();
            }
            if (equity != 0) {
                values.add(equity);
                tags.add("Equity");
            }
        } catch (NullPointerException e) {
            e.printStackTrace();
        }
        try {
            for (OtherAsset otherAsset : dashBoardModel.getAllAssets().getOtherAsset()) {
                values.add(Float.valueOf(otherAsset.getCurrentAmount()));
                tags.add(otherAsset.getAssetType());
            }
        } catch (NullPointerException e) {
            e.printStackTrace();
        }
        try {
            float emf = 0f;
            float dmf = 0f;
            float lmf = 0f;
            for (MutualFundAsset mutualFundAsset : dashBoardModel.getAllAssets().getMutualFundAsset()) {
                if (mutualFundAsset.getMutualFundType().equalsIgnoreCase("Equity Mutual Fund")) {
                    emf += mutualFundAsset.getCurrentAmount();
                } else if (mutualFundAsset.getMutualFundType().equalsIgnoreCase("Debt Mutual Fund")) {
                    dmf += mutualFundAsset.getCurrentAmount();
                } else if (mutualFundAsset.getMutualFundType().equalsIgnoreCase("Liquid Mutual Fund")) {
                    lmf += mutualFundAsset.getCurrentAmount();
                }
            }
            if (emf != 0) {
                values.add(emf);
                tags.add("Equity Mutual Fund");
            }
            if (dmf != 0) {
                values.add(dmf);
                tags.add("Debt Mutual Fund");
            }
            if (lmf != 0) {
                values.add(lmf);
                tags.add("Liquid Mutual Fund");
            }
        } catch (NullPointerException e) {
            e.printStackTrace();
        }
        try {
            float fda = 0f;
            List<FixedDepositAsset> fixedDepositAssets = dashBoardModel.getAllAssets().getFixedDepositAsset();
            for (FixedDepositAsset fixedDepositAsset : fixedDepositAssets) {
                fda = fixedDepositAsset.getAmount();
            }
            if (fda != 0) {
                values.add(fda);
                tags.add("Fixed Deposit Assets");
            }

        } catch (NullPointerException e) {
            e.printStackTrace();
        } finally {
            initBarChart();
            setBarData(dashBoardModel.getIncome().longValue(), dashBoardModel.getExpense().longValue(), dashBoardModel.getInvSurplus().longValue(), true);
            initPieData(values, tags);
            setupGoalsUI();
        }

    }**

    void setupGoalsUI() {
        goalsListLayout.removeAllViews();
        scrollViewLayout.scrollTo(0, 0);
        for (GoalDetailList goalDetailList : dashBoardModel.getGoalDetailList()) {
            View view = getLayoutInflater().inflate(R.layout.layout_goal_list_single, null);
            TextView goalDurationTextView = view.findViewById(R.id.goalDurationTextView);
            TextView currentValueTextView = view.findViewById(R.id.currentValueTextView);
            TextView ncrTextView = view.findViewById(R.id.ncrTextView);
            TextView currentInvestmentTextView = view.findViewById(R.id.currentInvestmentTextView);
            TextView monthlyTextView = view.findViewById(R.id.monthlyTextView);
            TextView stepUpTextView = view.findViewById(R.id.stepUpTextView);
            TextView oneTimeTextView = view.findViewById(R.id.oneTimeTextView);
            TextView goalTitle = view.findViewById(R.id.goalTitle);
            TextView goalPercent = view.findViewById(R.id.goalPercent);
            ImageView goalIcon = view.findViewById(R.id.goalIcon);
            TextView homeLoanInstructionTV = view.findViewById(R.id.homeLoanInstructionTV);
            homeLoanInstructionTV.setVisibility(View.GONE);
            goalDurationTextView.setText(goalDetailList.getRemainingYears() + "");
            currentValueTextView.setText("" + CommonUtil.rupeeFormatFromLong(goalDetailList.getPresentValue()));
            ncrTextView.setText("" + CommonUtil.rupeeFormatFromLong(goalDetailList.getNetCorpusRequired()));
            currentInvestmentTextView.setText("" + CommonUtil.rupeeFormatFromLong(goalDetailList.getCurrentInvestedAmount()));
            monthlyTextView.setText("" + CommonUtil.rupeeFormatFromLong(goalDetailList.getMonthlySIP()));
            stepUpTextView.setText("" + CommonUtil.rupeeFormatFromLong(goalDetailList.getStepUpSIP()));
            oneTimeTextView.setText("" + CommonUtil.rupeeFormatFromLong(goalDetailList.getLumsumInvestment()));
            goalTitle.setText("" + goalDetailList.getGoalName());
            goalPercent.setText("Goal Current Status : " + goalDetailList.getPercentageCompleted() + " %");
            LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT);
            lp.setMargins(10, 10, 10, 10);
            view.setLayoutParams(lp);
            if (goalDetailList.getGoalType().contains("Vacation")) {
                if (goalDetailList.getGoalType().contains("Domestic")) {
                    //domestic
                    goalIcon.setImageResource(R.drawable.goal_domestic);

                } else {
                    //internactional
                    goalIcon.setImageResource(R.drawable.goal_intenational);
                }

            } else if (goalDetailList.getGoalType().contains("Parents Support Goal")) {
                goalIcon.setImageResource(R.drawable.goal_parent);

            } else if (goalDetailList.getGoalType().contains("Graduation")) {
                goalIcon.setImageResource(R.drawable.goal_education);

            } else if (goalDetailList.getGoalType().contains("Retirement")) {
                goalIcon.setImageResource(R.drawable.goal_retierment);

            } else if (goalDetailList.getGoalType().contains("Home")) {
                goalIcon.setImageResource(R.drawable.goal_home);
                homeLoanInstructionTV.setVisibility(View.VISIBLE);
            } else if (goalDetailList.getGoalType().contains("Marriage")) {
                goalIcon.setImageResource(R.drawable.goal_marriage);
            } else if (goalDetailList.getGoalType().contains("Vehicle")) {
                goalIcon.setImageResource(R.drawable.goal_car);
            } else {
                goalIcon.setImageResource(R.drawable.goal_others);
            }
            goalsListLayout.addView(view);

        }
        scrollViewLayout.scrollTo(0, 0);
    }

    @OnCheckedChanged({R.id.monthlyRadioButton, R.id.yearlyRadioButton})
    @Override
    public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
        if (isChecked && dashBoardModel != null) {
            switch (buttonView.getId()) {
                case R.id.monthlyRadioButton:
                    if (dashBoardModel.getIncome() != null && dashBoardModel.getExpense() != null && dashBoardModel.getInvSurplus() != null)
                        setBarData(dashBoardModel.getIncome().longValue(), dashBoardModel.getExpense().longValue(), dashBoardModel.getInvSurplus().longValue(), true);
                    break;
                case R.id.yearlyRadioButton:
                    if (dashBoardModel.getIncome() != null && dashBoardModel.getExpense() != null && dashBoardModel.getInvSurplus() != null)
                        setBarData(dashBoardModel.getIncome().longValue(), dashBoardModel.getExpense().longValue(), dashBoardModel.getInvSurplus().longValue(), false);
                    break;
            }
        }

    }


    @OnClick({R.id.assetDetailButton, R.id.subscribeButton, R.id.titleBarCardView})
    @Override
    public void onClick(View v) {
        if (dashBoardModel == null) {
            return;
        }
        switch (v.getId()) {
            case R.id.assetDetailButton:
                AssetDetailDialog assetDetailDialog = new AssetDetailDialog(getActivity());
                assetDetailDialog.setData(values, tags);
                assetDetailDialog.show();
                break;
            case R.id.subscribeButton:
                if (isDetails) {
                    if (dashBoardModel.getUserPaymentHistoryList() != null) {
                        PaymentDetailDialog paymentDetailDialog = new PaymentDetailDialog(getActivity());
                        paymentDetailDialog.setData(dashBoardModel.getUserPaymentHistoryList());
                        paymentDetailDialog.show();
                    }
                } else {
                    ((HomeActivity) getActivity()).openReport();
                }
                break;
            case R.id.titleBarCardView:
                if (expansionLayoutEBooks.isExpanded()) {
                    expansionLayoutEBooks.toggle(false);
                } else {
                    expansionLayoutEBooks.toggle(true);
                }
                scrollViewLayout.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        scrollViewLayout.fullScroll(View.FOCUS_DOWN);
                    }
                }, 500);
                break;
        }
    }

    @Override
    public void onRefresh() {
        this.dashBoardModel = null;
        refreshDashboard.setRefreshing(false);
        refreshDashBoard();
    }

    @TargetApi(Build.VERSION_CODES.N)
    private void refreshEBooks() {
        try {
            List<Object[]> booksPurchaseHistoryList = dashBoardModel.getBooksPurchaseHistoryList();
            if (booksPurchaseHistoryList == null || booksPurchaseHistoryList.size() == 0) {
                String bookUrl = CommonConstants.eBooksURL + "?name=" + SharedPreferenceController.getInstance().getUser(getActivity()).getFullName() +
                        "&email=" + SharedPreferenceController.getInstance().getUser(getActivity()).getEmail() +
                        "&mobileNumber=" + SharedPreferenceController.getInstance().getUser(getActivity()).getPhoneNumber() + "&client=mobileapp";
                String str = "<p>You have not purchased any eBook. Please  <a color='#3270a3' href='" + bookUrl + "'>click here</a> to purchase our eBooks.</p>";
                CharSequence sequence = Html.fromHtml(str);
                SpannableStringBuilder strBuilder = new SpannableStringBuilder(sequence);
                URLSpan[] urls = strBuilder.getSpans(0, sequence.length(), URLSpan.class);
                for (URLSpan span : urls) {
                    makeLinkClickable(strBuilder, span, bookUrl);
                }
                eBooksNoData.setText(strBuilder);
                eBooksNoData.setMovementMethod(LinkMovementMethod.getInstance());
                eBooksNoData.setVisibility(View.VISIBLE);
            } else {
                eBooksNoData.setVisibility(View.GONE);
                eBooksLayout.removeAllViews();
                int index = 0;
                for (Object[] bookObject : booksPurchaseHistoryList) {
                    CardView cardView = (CardView) getLayoutInflater().inflate(R.layout.layout_ebooks_single_item, null);
                    TextView nameTV = cardView.findViewById(R.id.nameTV);
                    TextView amountTV = cardView.findViewById(R.id.amountTV);
                    TextView dateTV = cardView.findViewById(R.id.dateTV);
                    ImageView downloadIV = cardView.findViewById(R.id.downloadIV);
                    if (index > 0) {
                        TextView nameLblTV = cardView.findViewById(R.id.nameLblTV);
                        nameLblTV.setVisibility(View.GONE);
                        TextView amountLblTV = cardView.findViewById(R.id.amountLblTV);
                        amountLblTV.setVisibility(View.GONE);
                        TextView dateLblTV = cardView.findViewById(R.id.dateLblTV);
                        dateLblTV.setVisibility(View.GONE);
                        TextView downloadLblTV = cardView.findViewById(R.id.downloadLblTV);
                        downloadLblTV.setVisibility(View.GONE);
                    }
                    nameTV.setText("" + bookObject[1]);
                    amountTV.setText("" + (int) Double.parseDouble(bookObject[2].toString()));
                    dateTV.setText("" + CommonUtil.getDateMonthAndYear(((Number) bookObject[3]).longValue()));
                    eBooksLayout.addView(cardView);
                    downloadIV.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View view) {
                            bookId = (int) Double.parseDouble(bookObject[0].toString());
                            bookName = bookObject[1].toString();
                            downloadEBook();
                        }
                    });
                    nameTV.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View view) {
                            bookId = (int) Double.parseDouble(bookObject[0].toString());
                            bookName = bookObject[1].toString();
                            downloadEBook();
                        }
                    });
                    index++;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    protected void makeLinkClickable(SpannableStringBuilder strBuilder, final URLSpan span, String bookUrl) {
        int start = strBuilder.getSpanStart(span);
        int end = strBuilder.getSpanEnd(span);
        int flags = strBuilder.getSpanFlags(span);
        ClickableSpan clickable = new ClickableSpan() {
            public void onClick(View view) {
                CommonUtil.openUrlInBrowser(getContext(), bookUrl);
            }
        };
        strBuilder.setSpan(clickable, start, end, flags);
        strBuilder.removeSpan(span);
    }

    @Override
    public void downloadEBook() {
        if (CommonUtil.isWriteStoragePermissionGranted(getActivity(), permissionlistener)) {
            if (bookId != null && bookName != null) {
                String fileName = bookName + ".pdf";
                ((HomeActivity) getActivity()).downloadFile(ApiClient.BASE_URL + "downloadBook-" + bookId, fileName);
                bookId = null;
                bookName = null;
            } else {
                Toast.makeText(getActivity(), "Book id is null", Toast.LENGTH_SHORT).show();
            }
        }
    }


    PermissionListener permissionlistener = new PermissionListener() {
        @Override
        public void onPermissionGranted() {
            Toast.makeText(getActivity(), "Permission Granted", Toast.LENGTH_SHORT).show();
            downloadEBook();
        }

        @Override
        public void onPermissionDenied(ArrayList<String> deniedPermissions) {
            Toast.makeText(getActivity(), "Permission Denied\n" + deniedPermissions.toString(), Toast.LENGTH_SHORT).show();
        }
    };

    void showAppUpdateDialog(boolean isCompulsoryUpdate) {
        AppUpdateDialog appUpdateDialog = new AppUpdateDialog(getActivity());
        appUpdateDialog.setCancelable(false);
        appUpdateDialog.setCallBack(isCompulsoryUpdate, new AppUpdateDialog.AppUpdateCallBack() {
            @Override
            public void onUpdateSelected() {
                Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse("market://details?id=com.jawksoftwares.investyadnya"));
                startActivity(intent);
            }
        });
        appUpdateDialog.show();
    }
}

**Comment by vinayakmestri** [comment]
options = new HIOptions();
 HIChart chart = new HIChart();
 chart.setType("pie");
 chart.setPlotShadow(false);
 HIExporting hiExporting = new HIExporting();
 hiExporting.setEnabled(false);
 options.setExporting(hiExporting);
 options.setChart(chart);
 chartView.setOptions(options);
 ArrayList<String> colors = new ArrayList<>();
 colors.add("#95CEFF");
 colors.add("#e15d62");
 colors.add("#b71c1c");
 colors.add("#aa00ff");
 colors.add("#004d40");
 colors.add("#cddc39");
 colors.add("#e65100");
 colors.add("#bf360c");
 colors.add("#795548");
 colors.add("#e57373");
 colors.add("#b2dfdb");
 colors.add("#66bb6a");
 colors.add("#3e2723");
 colors.add("#607d8b");
 options.setColors(colors);

 HITitle hiTitle = new HITitle();
 hiTitle.setText("");
 options.setTitle(hiTitle);


 HICredits hiCredits = new HICredits();
 hiCredits.setEnabled(false);
 hiCredits.setText("");
 options.setCredits(hiCredits);


 HITooltip tooltip = new HITooltip();
 tooltip.setPointFormat("{series.name}: <b>{point.percentage:.1f}%</b><br>Amount: {point.y}");
 options.setTooltip(tooltip);
 ArrayList<HashMap<String, Object>> data = new ArrayList<>();
 HISeries hiSeries = new HIPie();
 hiSeries.setName("Allocation");
 HIDataLabelsOptionsObject hiDataLabelsOptionsObject = new HIDataLabelsOptionsObject();
 hiDataLabelsOptionsObject.setFormat("{point.name}: <br>" + "<p>Rs. {point.y}</p>");
 hiSeries.setDataLabels(hiDataLabelsOptionsObject);
 hiSeries.setAnimationLimit(0);
 for (int i = 0; i < pieChartData.size(); i++) {
     HashMap<String, Object> object = new HashMap<>();
     object.put("name", tags.get(i));
     object.put("y", pieChartData.get(i));
     data.add(object);
 }
 hiSeries.setData(data);
 hiSeries.animate(false);
 options.setSeries(new ArrayList<>(Collections.singletonList(hiSeries)));
 chartView.setFocusable(false);
 chartView.post(new Runnable() {
     @Override
     public void run() {
         chartView.setOptions(options);
         chartView.setFocusable(false);
         chartView.setFocusable(true);
     }
 });

**Comment by vinayakmestri** [comment]
**public void initPieData(ArrayList<Float> pieChartData, ArrayList<String> tags) {
        HISubtitle title = new HISubtitle();
        title.setText("");
        chartView.setTitle(title, title, true);

        options = new HIOptions();
        HIChart chart = new HIChart();
        chart.setType("pie");
        chart.setPlotShadow(false);
        HIExporting hiExporting = new HIExporting();
        hiExporting.setEnabled(false);
        options.setExporting(hiExporting);
        options.setChart(chart);
        chartView.setOptions(options);
        ArrayList<String> colors = new ArrayList<>();
        colors.add("#95CEFF");
        colors.add("#e15d62");
        colors.add("#b71c1c");
        colors.add("#aa00ff");
        colors.add("#004d40");
        colors.add("#cddc39");
        colors.add("#e65100");
        colors.add("#bf360c");
        colors.add("#795548");
        colors.add("#e57373");
        colors.add("#b2dfdb");
        colors.add("#66bb6a");
        colors.add("#3e2723");
        colors.add("#607d8b");
        options.setColors(colors);

        HITitle hiTitle = new HITitle();
        hiTitle.setText("");
        options.setTitle(hiTitle);


        HICredits hiCredits = new HICredits();
        hiCredits.setEnabled(false);
        hiCredits.setText("");
        options.setCredits(hiCredits);


        HITooltip tooltip = new HITooltip();
        tooltip.setPointFormat("{series.name}: <b>{point.percentage:.1f}%</b><br>Amount: {point.y}");
        options.setTooltip(tooltip);
        ArrayList<HashMap<String, Object>> data = new ArrayList<>();
        HISeries hiSeries = new HIPie();
        hiSeries.setName("Allocation");
        HIDataLabelsOptionsObject hiDataLabelsOptionsObject = new HIDataLabelsOptionsObject();
        hiDataLabelsOptionsObject.setFormat("{point.name}: <br>" + "<p>Rs. {point.y}</p>");
        hiSeries.setDataLabels(hiDataLabelsOptionsObject);
        hiSeries.setAnimationLimit(0);
        for (int i = 0; i < pieChartData.size(); i++) {
            HashMap<String, Object> object = new HashMap<>();
            object.put("name", tags.get(i));
            object.put("y", pieChartData.get(i));
            data.add(object);
        }
        hiSeries.setData(data);
        hiSeries.animate(false);
        options.setSeries(new ArrayList<>(Collections.singletonList(hiSeries)));
        chartView.setFocusable(false);
        chartView.post(new Runnable() {
            @Override
            public void run() {
                chartView.setOptions(options);
                chartView.setFocusable(false);
                chartView.setFocusable(true);
            }
        });


    }**

**Comment by soommy12** [comment]
HI @vinayakmestri ! Thanks for your question. As the error says, the `HIChartView` can't be drawn without options attached. This means if you are attaching options in `post` method the error will be thrown. The solution is to attach empty `HIOptions` object to your chart before the actual options.
