### ISSUE TITLE
Issue with method removal

### ISSUE THREAD

**Issue by DevNigam** [highcharts/highcharts-android#102]
In latest version of highcharts i.e, 7.1.2 from `HISeries` class `setProperty()` has been removed. Along with that how can I access that property by using `HIChartContext` object inside `setPointFormatter()`

**Comment by soommy12** [comment]
Hello @DevNigam ! Thanks for the question. Don't really get what you're trying to do. Can you please explain what you want to achieve in more detail (it would be great to see some code snippets)?

**Comment by DevNigam** [comment]
@soommy12 Thanks for your quick response. What I want is

        // Data Set
        ArrayList<HISeries> dataSeries = new ArrayList<>();
        for (DailySale sale : dailySales) {
            HILine line = new HILine();
            line.setName(sale.name);
            ArrayList<Number[]> dataSet = new ArrayList<>();
            for (List<String> item : sale.data) {
                long time = CommonUtils.parseLong(item.get(0));
                double value = CommonUtils.parseDouble(item.get(1));
                Number[] data = new Number[]{time, value};
                dataSet.add(data);
            }
            line.setData(dataSet);
          // Here I want to set some custom property e.g., say line.setProperty("key","value");
            dataSeries.add(line);
        }
        options.setSeries(dataSeries);

        // Tooltip
        HITooltip tooltip = new HITooltip();
        tooltip.setUseHTML(true);
        tooltip.setXDateFormat("%d/%m/%Y");
        tooltip.setSplit(true);
        tooltip.setPointFormatter(new HIFunction(hiChartContext -> {
            String data = "<span style=\"color:%s\">%s:</span> <b>%s Ltrs</b>";
            String name = (String) hiChartContext.getProperty("series.name");
            double amount = (double) hiChartContext.getProperty("y");
            String color = (String) hiChartContext.getProperty("color");
          // Here I want to access that property
            return String.format(data, color, name, CommonUtils.getCurrencyFormat(amount));
        }, new String[]{"y", "series.name", "color"}));
        options.setTooltip(tooltip);

Inside the **for loop**, I want to set some custom property for that data set and inside **HIFunction**, I want to access that data.

**Comment by soommy12** [comment]
Thanks, I got it. I forgot to add this during the update. As far as I know, the 7.1.3 is on its way so I will introduce the fix along with it.

**Comment by DevNigam** [comment]
@soommy12 Thanks for the response. But, can you please let me know, how can I access that value using `hiChartContext`. That will be helpful for me.

**Comment by soommy12** [comment]
Sorry for the late response. You can access the custom property by its key. But remember to pass the value to the `HIFunction`'s second parameter (put it into the array). So, in your callback should be a line like this: `hiChartContext.getProperty("yourKey");`.

**Comment by DevNigam** [comment]
@soommy12 Thanks for your reply. I am eagerly waiting for 7.1.3 release.

**Comment by meirinberg** [comment]
@soommy12 I am failing to return any custom property in my callback. `hiChartContext.getProperty("yourKey");` always returns null and I have ensured it is in the array. I'm able to access it within the tooltip, but it's never making its way to my Kotlin code. On iOS, I don't have this issue. I can provide my code snippet -- I would appreciate any suggestions.  -- Posted full question here [https://github.com/highcharts/highcharts-android/issues/310](https://github.com/highcharts/highcharts-android/issues/310)
