### ISSUE TITLE
When orientation change chart weight and height automatically changing  

### ISSUE THREAD

**Issue by ArunVicky001** [highcharts/highcharts-android#103]
Hi 

I have placed the chart inside relative layout when the initial load it looks good  if I rotate the device into landscape mode, the view display as expected, again if I rotate the device to portrait mode the chart weight and height automatically changing. 

```
<RelativeLayout
                android:id="@+id/firstChartRelativeLayout"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_marginLeft="10dp"
                android:layout_marginTop="0dp"
                android:layout_marginRight="10dp"
                android:layout_marginBottom="5dp"
                android:layout_weight="4.45"
                android:background="@color/lineGreen">

                <com.highsoft.highcharts.core.HIChartView
                    android:id="@+id/hc"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">
                </com.highsoft.highcharts.core.HIChartView>
        
            </RelativeLayout> 
```

<img width="309" alt="Screenshot 2019-06-24 at 7 49 33 PM" src="https://user-images.githubusercontent.com/34921497/60026521-52931d80-96b9-11e9-8ee5-472c563526bb.png">

other than the chart all the controls are working fine. Could you please help me to solve this issue

**Comment by soommy12** [comment]
Hi @ArunVicky001 , thanks for your report. Gonna investigate the problem.

**Comment by ArunVicky001** [comment]
I have some other view in the layout for that I am using `layout_weight` for relative layout

**Comment by soommy12** [comment]
Great, can you share it?

**Comment by ArunVicky001** [comment]
If I give specific height and weight to relative layout it's working fine but the view will not be adaptive.

**Comment by ArunVicky001** [comment]
[sample.txt](https://github.com/highcharts/highcharts-android/files/3324571/sample.txt)

**Comment by ArunVicky001** [comment]
Initially my chart being like when the change the orientation 
![1](https://user-images.githubusercontent.com/34921497/60087695-27f9a100-975b-11e9-809b-2b0f2117335b.png)

it will display like below 

![2](https://user-images.githubusercontent.com/34921497/60087750-3d6ecb00-975b-11e9-8f3a-c8029c924d9e.png)

**Comment by ArunVicky001** [comment]
Actually my portrait and landscape views are entirely different, so am maintaining two `xml` file, whenever I rotate the device based on the configuration changes I will display the respective view.  Except the `HIChartView` view all other controls are working fine.

**Comment by soommy12** [comment]
When it comes to `match_parent` (either width or height) the `HIChartView` behaves indeed a little buggy. For now, we suggest you specify the chart view width or move it to another view while we will be investigating the problem.

**Comment by ArunVicky001** [comment]
Thanks for your response, Will give specific weight to the `HIChartView` (In this case view will not be adaptive). and please investigate this issue and fix it as soon as possible.

**Comment by widyhafiz03** [comment]
as well as graphics made to explain data to others so that understanding the differences in points in the picture is clear and easy to understand.
