### ISSUE TITLE
redraw is not working 

### ISSUE THREAD

**Issue by BoBoMEe** [highcharts/highcharts-android#104]
In my project,this is a  stackbar,
there is a Dynamic categories,so the series data will changed usually,
first,i setOptions with a changed options
after i want to call redraw,but redraw is not working and reload works well.
also,when i changed the chartview`s layoutparams and chart height in options ,but the render size is not changed
How can i change UI dynamically，thanks very match.

```java
HIChartView mHIChartView;
int barPointWidth = 16;
private HIOptions options buildOptions(List<String> categories, Number[]... data){
    HIOptions options = new HIOptions();
    HIChart hiChart = new HIChart();
    hiChart.setType("bar");
    int size = categories.size();
    hiChart.setHeight(80 + size * 2 * barPointWidth);
    options.setChart(hiChart);
...
    HIXAxis hixAxis = new HIXAxis();
    hixAxis.setCategories(new ArrayList<String>() {
      {
        addAll(categories);
      }
    });
    options.setXAxis(new ArrayList<HIXAxis>() {
      {
        add(hixAxis);
      }
    });
...
  options.setSeries(buildSeries(data));
  return options;
}
...
private void chartLayoutHeight(Object height) {
   int h = dp2px((Integer)height);
   ViewGroup.LayoutParams layoutParams = mHIChartView.getLayoutParams();
   layoutParams.height = h;
   mHIChartView.setLayoutParams(layoutParams);
}
...
// the categories and data is Dynamically
HIOptions options  = buildOptions(categories,data1,data2); 
Object height = options.getChart().getHeight();
chartLayoutHeight(height);
mHIChartView.setOptions(options);
mHIChartView.reload();
```
the webview size is not changed and the chart can scroll vertical in webview.

**Comment by soommy12** [comment]
Hi @BoBoMEe ! Sorry for your waiting, I am currently working on this issue.

**Comment by BoBoMEe** [comment]
thank you very match,

and I've shared a Demo app with your devs，I would appreciate it if you
could solve this error.

Bartosz <notifications@github.com> 于2019年7月8日周一 下午10:26写道：

**Comment by soommy12** [comment]
Yes, I just got it, thank you. I am analysing it.

**Comment by soommy12** [comment]
@BoBoMEe Your demo indeed showed us the problem with the dynamic chart scaling / resize. It will need some further investigation. The issue lies in view measurement. Please consider that it can take more time to solve than usually.

**Comment by BoBoMEe** [comment]
It's all right. I can wait for you to solve this problem. Is it necessary to update a version to solve this problem? I'll keep track of it. Thank you.

**Comment by soommy12** [comment]
Aye, the solution will be introduced in the new library version, that's for sure.

**Comment by soommy12** [comment]
The thing is, you haven't used the chart update properly @BoBoMEe . Setting the new `HIOptions` again indeed has no effect. Instead, each specific value of `HIOptions` can update the chart for you while using its setter. I will explain this on your demo app. You should initialize two separate `HIOptions` objects globally:
```
  private void setUpChartView() {
        mChartView1 = findViewById(R.id.chartview1);
        mChartView2 = findViewById(R.id.chartview2);
        options1 = new HIOptions();
        options2 = new HIOptions();
    }
```
Your method for chart options initialization should have `HIOptions` as an parameter:
```
   private void initChartOptions(HIOptions chartOptions, String type, final List<String> categories, Number[]... data) {
        HIOptions options = chartOptions;
        ...
}
```
Then, in the `initChartDatas` method you can use those as follows:
```
    private void initChartDatas(int categorySize, String type) {

        ....

        if (TextUtils.equals(type, targetStack)) {
            initChartOptions(options1, type, categories, listData, endData, noProgressData, onGoingData);
            mChartView1.setOptions(options1);
        } else if (TextUtils.equals(type, indicationStack)) {
            initChartOptions(options2, type, categories, listData, endData, noProgressData, onGoingData);
            mChartView2.setOptions(options2);
        }
    }
```
While the options are set by spinner callback, you should call `redraw()` for the first selection:
```
mSpinner1.setSelection(8);
mChartView1.redraw();
```

After those changes, you won't need `reload` method (which is deprecated) and your `chartLayoutMethod`. 

Anyways, I have to admit that thanks to your report we will introduce some chart draw improvements.

**Comment by BoBoMEe** [comment]
Oh, thank you, this is really ok, redraw can work.
My problem may be another question. When the category is changed, the size of the chart cannot be changed, it cannot be displayed completely or there is a large blank below.

**Comment by fasi1208** [comment]
How to redraw a bar chart. I already tried `chart.redraw()` but it's not working. I  am stuck to it please help

**Comment by pradeep-orbi** [comment]
> How to redraw a bar chart. I already tried `chart.redraw()` but it's not working. I am stuck to it please help

@fasi1208 Were you able to solve this issue ? If yes, can you please share how did you solve it ?
