### ISSUE TITLE
HIChartView is displaying www.highcharts.com

### ISSUE THREAD

**Issue by muhammadsr** [highcharts/highcharts-android#106]
![Screenshot_20190709-143047_HighFit](https://user-images.githubusercontent.com/1937488/60924577-61033c80-a256-11e9-8044-51100ab7cec2.jpg)

Notice the first chart is displaying www.highcharts.com instead of the actual chart. Any idea what is happening here?

**Comment by soommy12** [comment]
Hello @muhammadsr ! You probably miss-clicked the HICredits (the link) in the bottom right corner.
