### ISSUE TITLE
Highcharts - throwing OutOfMemoryError when using HILine

### ISSUE THREAD

**Issue by deepakgupta7403** [highcharts/highcharts-android#107]
Hey
I m using HILine and m getting 10000 data from server but when m set to graph the application is force closing and showing  **Throwing OutOfMemoryError "Failed to allocate a 39220 byte allocation with 8286 free bytes and 8KB until OOM"**  actually i have 2 HILine and both hold 10000+ data. please help me to how i solve the error...

**Comment by soommy12** [comment]
Hello @deepakgupta7403 ! Thanks for your question. That's indeed strange behaviour. Could you please share a JSON sample with your data to help us recreate the problem? Thanks in advance!

**Comment by deepakgupta7403** [comment]
hey @soommy12 thanks for response 
Please Find below Attachment
if you seen in the Sample JSON there is one payLoad inside payLoad Obj there is one **data**   array that **data** is hold the main data
[sample.txt](https://github.com/highcharts/highcharts-android/files/3397340/sample.txt)

**Comment by soommy12** [comment]
Thanks! Gonna investigate the issue now.

**Comment by deepakgupta7403** [comment]
@soommy12  hey 
Can you help me when i building Release APK. m getting error 
FAILURE: Build failed with an exception.
*** What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details**

this error came after when i add highchart library .
is there any thing that i need to add into proguards-rules...

**Comment by soommy12** [comment]
Depends what you have in your `proguard-rules` file. Anyways, this question concerns a different topic. Could you please create another issue for this specific question?
