### ISSUE TITLE
After updating Android Studio to 3.4.2 - Highcharts is not working 

### ISSUE THREAD

**Issue by deepakgupta7403** [highcharts/highcharts-android#108]
Hey,
3 hours back Highcharts is working fine but when i update the Android Studio to 3.4.2 highcharts show **cannot resolve symbol highcharts** please help me what can i do, thanks in advance

**Comment by soommy12** [comment]
I have updated my Android Studio and I didn't meet the problem. Please try to re-sync your Gradle file or use `Invalidate Caches/Restart`.

**Comment by deepakgupta7403** [comment]
Yes is done after clean and rebuilding the project 
thank you
