### ISSUE TITLE
How to catch onClick(onTouch) event on graph module outside the object.

### ISSUE THREAD

**Issue by ZuzanaBenicko** [highcharts/highcharts-android#11]
Hello, 

I have graph module in Recycleview.ViewHolder as a small preview and on click(with no interaction in the graph), I want to show fullscreen version (or call any of my functions). 

Unfortunately, I can not find the way how to catch onClick event on the whole module in Recycleview outside the graph object. On touch listener on viewHolder or HIChartView module is not called after click or touch, also descendantFocusability, clickable, focusable, enabled does nothing.

Please is there a way how to completely disable user interaction on the graph and catch the event outside the graph object?

Thank you,
Zuzana

**Comment by soommy12** [comment]
Hello @ZuzanaBenicko , thanks for reporting the issue. Can you provide us with some code to let us recreate the problem?

**Comment by ZuzanaBenicko** [comment]
Hi,

I have fragment layout:

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/swipeRefreshLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
        <android.support.v7.widget.RecyclerView
            android:id="@+id/rv_home"
            android:layout_width="match_parent"
            android:layout_height="match_parent"

            app:fastScrollEnabled="true"
            app:fastScrollHorizontalThumbDrawable="@drawable/thumb_drawable"
            app:fastScrollHorizontalTrackDrawable="@drawable/line_drawable"
            app:fastScrollVerticalThumbDrawable="@drawable/thumb_drawable"
            app:fastScrollVerticalTrackDrawable="@drawable/line_drawable"/>

    </android.support.v4.widget.SwipeRefreshLayout>


</RelativeLayout>

and RecycleView.ViewHolder layout:

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:padding="3dp"
    >

        <com.highsoft.highcharts.Core.HIChartView
            android:id="@+id/hc_row"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:visibility="invisible"
            android:clickable="false"
            android:focusable="false"
            android:focusableInTouchMode="false"
            android:descendantFocusability="blocksDescendants"
        />


</RelativeLayout>

I want to set a listener onClick or onTouch and call my own function after
clicking on the row (with no interaction in the graph). How can I do that?
I'm not able to catch the action with an onClickListener set for ViewHolder
nor HIChartView.

2018-08-01 11:51 GMT+02:00 Bartosz <notifications@github.com>:

**Comment by soommy12** [comment]
Unfortunately, `HIChartView` behaves like `WebView` so it won't capture onClick events. I suggest adding a button to your charts like this:
```
        <RelativeLayout
            android:orientation="vertical"
            xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:tools="http://schemas.android.com/tools"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/chart_container_1"
            tools:context="com.highsoft.devground.IssuesActivity">
            <com.highsoft.highcharts.Core.HIChartView
                android:id="@+id/hc_row"
                android:layout_height="match_parent"
                android:layout_width="match_parent"/>
            <Button
                android:id="@+id/btn"
                android:layout_alignParentStart="true"
                android:layout_alignParentBottom="true"
                android:text="Button"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content" />
        </RelativeLayout>
```
Thanks to this button you will be able to call your own functions. When it comes to changing bounds of your chart I suggest creating another fragment with the detailed full-screen chart instead of expanding it. The animation of expanding with many charts in the same view will be scuttering (HIChartView is demanding view).  A similar approach is presented in [HighFit](https://github.com/highcharts/highcharts-android/blob/master/Example/HighFit/app/src/main/java/com/highsoft/highfit/DashboardFragment.java#L94) (example app).
