### ISSUE TITLE
issue when data contains Single quotes (') 

### ISSUE THREAD

**Issue by SSJ2912** [highcharts/highcharts-android#110]
Hicharts is not rendering when I set a data with single quote like "Highchart's data".  This issue can not be produced in iOS.
The log show - E/Highcharts: Uncaught SyntaxError: missing ) after argument list.

**Comment by soommy12** [comment]
Hello @SSJ2912 ! Thank you for your question. I didn't meet such behaviour (I used word cloud series type for the test). Which version of the library are you using? I remember there was a problem with quotes but it was solved. Maybe there is still a case when its buggy. Can you please share your options?

**Comment by SSJ2912** [comment]
The problem is with the custom ToolTip. when I use default tooltip there is no problem.
My JS code handles the escape char- single quote

**Comment by soommy12** [comment]
Sorry, I thought you meant chart's data (that's what the title says). Anyway, can you please share your custom tooltip code?
