### ISSUE TITLE
Data Labels

### ISSUE THREAD

**Issue by soareseneves** [highcharts/highcharts-android#111]
Hello, first of all, thanks for this great framework!

I implemented some pie charts on iOS and now I am trying to replicate those on android but unfortunately the DataLabels are not in like iOS, here is the screenshot of iOS:

![iOS-chart](https://user-images.githubusercontent.com/16960561/64254306-82e70b80-cef5-11e9-8dcc-d3b4ead2480b.jpg)

and here is Android screenshot:

![android-chart](https://user-images.githubusercontent.com/16960561/64254329-8da1a080-cef5-11e9-9198-5e8e951a2071.jpg)

As you see, android is missing the data labels above the pie chart.

Here is the code I use on iOS:

```
        let plotOptions = HIPlotOptions()
        plotOptions.pie = HIPie()
        plotOptions.pie.allowPointSelect = NSNumber(value: true)
        plotOptions.pie.cursor = "pointer"
        plotOptions.pie.dataLabels = HIDataLabels()
        plotOptions.pie.dataLabels.enabled = NSNumber(value: true)
        plotOptions.pie.dataLabels.color = HIColor(uiColor: UIColor.white)
        plotOptions.pie.dataLabels.format = "<b>{point.name}</b>: {point.percentage:.1f}% ({point.y})"
```

And here is the android code:

```
        val plotOptions = HIPlotOptions()
        plotOptions.pie = HIPie()
        plotOptions.pie.allowPointSelect = true
        plotOptions.pie.cursor = "pointer"
        val dataLabels = HIDataLabelsOptionsObject()
        dataLabels.format = "<b>{point.name}</b>: {point.percentage:.1f}% ({point.y)"
        dataLabels.enabled = true
        dataLabels.color = HIColor.initWithHexValue("#FFFFFF")
        plotOptions.pie.dataLabels = arrayListOf(dataLabels)
```

How can I achieve this on android?

Thanks.

**Comment by soommy12** [comment]
Hello @soareseneves ! Thanks for your question. Which version of the library are you using?

**Comment by soareseneves** [comment]
7.1.3 on Android and 7.0.2 on iOS :P

**Comment by soommy12** [comment]
Thanks for your report! It is a bug (already fixed on the iOS side). The Android fix will be introduced in the 7.2 release.

**Comment by soareseneves** [comment]
Ohh, so my code is correct? All I need to do is wait for the update? :)

**Comment by soommy12** [comment]
Yeah, it's okay. At most, the `HIDataLabelsOptionsObject` could change to `HIDataLabels` but it's not a big deal. Hopefully, the update will appear this week.

**Comment by soareseneves** [comment]
Thanks for the quick responses!
