### ISSUE TITLE
HIEvents kotlin example

### ISSUE THREAD

**Issue by soareseneves** [highcharts/highcharts-android#112]
Hello again, can you please provide an example of HIEvents using kotlin? specifically the redraw event, I want to stop my custom loading UI when the charts finishes loading.

**Comment by soareseneves** [comment]
I found it!

If anyone ever needs this:

```
        val pie = HIPie()
        pie.name = this.chartTitle
        pie.data = data

        val events = HIEvents()
        events.afterAnimate =  HIFunction(   HIConsumer<HIChartContext> {
            //STOP THE LOADING
        } , arrayOf())

        pie.events = events
```

**Comment by afasina** [comment]
How did you go by loading the data to the chart
