### ISSUE TITLE
Define custom space between bars

### ISSUE THREAD

**Issue by jhowcs** [highcharts/highcharts-android#116]
I'd like to know whether or not is possible to define a specific space/margin between bars. 

As you can see in the image below, when we have just a few items the space between each bar is too much and I'd like to hardcode a custom margin to avoid this to happen.

![Screen Shot 2019-09-26 at 10 43 08](https://user-images.githubusercontent.com/5488195/65680139-4fa82000-e04e-11e9-8092-38151dbc9da7.png)

**Comment by soommy12** [comment]
Hi @jhowcs !
Yes, it is possible. Use this:
```
HIColumn column = new HIColumn();
column.setGroupPadding(0);
```
