### ISSUE TITLE
Highchart Share : Open by defaults 

### ISSUE THREAD

**Issue by TarunDholakiyaClarion** [highcharts/highcharts-android#117]
I was trying to share the Chart image so on tap of the export icon the share items appear. So I choose the to Gmail and accidentally I tapped on **"Always"** instead of **"Just once"**. 

Now, I was trying to **"CLEAR DEFAULTS"** but somehow it shows "No defaults set". Hence now anytime I try to share it always opens Gmail.

Is there any way to Clear Defaults?

**Comment by soommy12** [comment]
Hello @TarunDholakiyaClarion !

Choose Gmail app in the settings instead of your app.  Then click **clear defaults**.
