### ISSUE TITLE
How to store image of an chart prgramatically?

### ISSUE THREAD

**Issue by savyad** [highcharts/highcharts-android#118]
I want to store image of an chart on sdcard is it possible.

**Comment by soommy12** [comment]
Hi @savyad !

Currently, there is no such option. You can share chart as an image to different apps but store it on the sd card or phone memory is not available. We will take the implementation of this kind of export under consideration. Although, you can store chart options as JSON e.g. in `SharedPreferences` thanks to `HIOptions`'s `getParams()` method which returns a map.
