### ISSUE TITLE
HIDataLabelsOptionsObject is missing connector settings

### ISSUE THREAD

**Issue by skydschmidt** [highcharts/highcharts-android#119]
Hi,
I'm trying to customize the connection line on PieChart. With iOS there are options for connectorWidth and connectorColor in the object HIDataLabelsOptionsObject. Unfortunately I don't see these in Android, there is another possibility to make this setting here.
Thanks

**Comment by soommy12** [comment]
Hi @skydschmidt ! 

Which version of the library are you using?

**Comment by skydschmidt** [comment]
Hi @soommy12 ,

I use the version 7.2.

**Comment by soommy12** [comment]
I am really sorry about that. Due to the update process, some content from this class got cut. Hopefully, this will be fixed in the next release.

**Comment by skydschmidt** [comment]
Okay, thanks. I'll wait.

**Comment by soommy12** [comment]
Hi @skydschmidt ! I'm coming back with the news. The fix in the core library is already done. Unfortunately, they introduced it after 7.2.1 release so it will be available in the future one.

**Comment by skydschmidt** [comment]
works for me in 8.0
