### ISSUE TITLE
HISeries  fillColor Property not supported

### ISSUE THREAD

**Issue by hxx1197411446** [highcharts/highcharts-android#121]
fillColor: {  
                    linearGradient: {x1: 0, x2: 0, y1: 0, y2: 1},
                    stops: [
                        [0, 'rgba(55,100,148,0.4)'],
                        [1, 'rgba(36,44,62,0.4)']
                    ]
                },

**Comment by soommy12** [comment]
Hi @hxx1197411446 ! Thanks for your post. Can you please explain further what exactly do you mean?

**Comment by hxx1197411446** [comment]
![image](https://user-images.githubusercontent.com/10133519/66884307-631e2980-f003-11e9-9449-e43dae73d9a7.png)

**Comment by hxx1197411446** [comment]
I want to set this property but can't find it

**Comment by soommy12** [comment]
Which version of the library are you using? In the newest one, this method is accessible:
```
HIAreaspline areaspline = new HIAreaspline();
areaspline.setFillColor(HIColor.initWithName("red"));
```

**Comment by hxx1197411446** [comment]
![image](https://user-images.githubusercontent.com/10133519/66894578-632e2180-f023-11e9-8ff1-3aa7e5233e16.png) How to set it in

**Comment by soommy12** [comment]
You have set the `fillColor` property properly. Can you explain please what are your expectations?

**Comment by hxx1197411446** [comment]
Don't need to set it in the chart again? like this
![image](https://user-images.githubusercontent.com/10133519/66895177-b9e82b00-f024-11e9-96f5-ab36f1aea37e.png)

**Comment by soommy12** [comment]
Yes, you do. There are many tutorials on how to use Highcharts Android wrapper. The short one is [right here, on Github](https://github.com/highcharts/highcharts-android#create-the-chart). The second is on [the Highcharts blog](https://www.highcharts.com/blog/post/highcharts-android-wrapper-tutorial/).

**Comment by hxx1197411446** [comment]
Thank you
