### ISSUE TITLE
Does HIChartView.addFont support otf?

### ISSUE THREAD

**Issue by ergunkocak** [highcharts/highcharts-android#122]
Hi,

Does HIChartView.addFont support otf? If so is there anything else required other than :

```Swift
let fontMedium = Bundle.main.path(forResource: "AvenirNextRoundedStd-Med", ofType: "otf")
HIChartView.addFont(fontMedium)
```

And is there a special place to call this method?

Or is it maybe because i am using HMTL in labels:
```Swift
let dataLabelsOptionsObject = HIDataLabelsOptionsObject()
dataLabelsOptionsObject.format = "<span>{point.name}</span><br><span style=\"color: #A2A2A2;\">{point.percentage:.2f} %</span>"
dataLabelsOptionsObject.useHTML = true
```

If so how can i specify the font in HTML tags?

```Swift
dataLabelsOptionsObject.format = "<span style=\"font-family:AvenirNextRoundedStd-Med;\">{point.name}</span><br><span style=\"color: #A2A2A2;\">{point.percentage:.2f} %</span>"
```

?

Best

**Comment by soommy12** [comment]
Hi @ergunkocak ! This is Highcharts Android Wrapper repository. The code you shared is in Swift. If you have questions about swift please visit [Highcharts iOS Wrapper repository](https://github.com/highcharts/highcharts-ios).

**Comment by ergunkocak** [comment]
Sorry :)
