### ISSUE TITLE
Tooltip with long text is not moved to new line.

### ISSUE THREAD

**Issue by SSJ2912** [highcharts/highcharts-android#123]
Data is hidden when Tooltip has long text. Is there any way to either truncate or wrap the text to new line?. 
![Screenshot_20191017-123344_Zoho CRM Analytics](https://user-images.githubusercontent.com/38619144/66995713-16af1880-f0ed-11e9-8d34-e4c104339ce9.jpg)

**Comment by soommy12** [comment]
Hi @SSJ2912 ! You can always use `HICSSObject` to restrain the tooltip width:
```
HITooltip tooltip = new HITooltip();
tooltip.setPointFormat("This is very long tooltip which we need to wrap on your chart for the pretty look");
HICSSObject style = new HICSSObject();
style.setWidth(50);
tooltip.setStyle(style);
```
