### ISSUE TITLE
Uncaught syntax error while updating options

### ISSUE THREAD

**Issue by DevNigam** [highcharts/highcharts-android#124]
I am getting an exception while calling

`update(options, true, true)`

**Highcharts: Uncaught SyntaxError: missing ) after argument list**

Version : **7.2**

**Comment by soommy12** [comment]
Hi @DevNigam , thanks for the question. Can you please share some more code? When I am using this method the problem does not occur. Maybe the problem happens somewhere else in your project?

**Comment by DevNigam** [comment]
@soommy12 Thanks for the reply. Let me identify exact case and will revert back to you.
