### ISSUE TITLE
API Level 22 - Error inflating class

### ISSUE THREAD

**Issue by skydschmidt** [highcharts/highcharts-android#125]
Hi everyone, I currently have the problem that the HighChart View cannot be inflated. Apparently this occurs at API level 22.

Even with a completely new project, which I set up by just adding the view in XML to the main activity, the app crashes when opened. API level 19 works, API level 23 works.
I used the emulator to test it.

Best regards,
Daniel

**Comment by soommy12** [comment]
Hi @skydschmidt ! Thanks for the question. Are you using `androidx.*` artifacts?

**Comment by skydschmidt** [comment]
Hi @soommy12 , yes i use it.

**Comment by soommy12** [comment]
So it is directly connected with https://github.com/highcharts/highcharts-android/issues/115. We are currently working on it.
