### ISSUE TITLE
How to add colors with Alpha value to the PieChart?

### ISSUE THREAD

**Issue by PallaviTapkir** [highcharts/highcharts-android#126]
I am using highcharts library for Android.
I want to set custom colors wih alpha values to the PieChart.
But, it seems that HighChart allows only colors without alpha value.

Like,
Suppose I am adding "#990C83F3" which is 60% transparent color to the pie chart it allows only #990C83 color and ignores the last 2 characters, which implies to change in color.

How can I add required colors with alpha value to the pie chart?

**Comment by soommy12** [comment]
Hi @PallaviTapkir ! To set a colour with alpha you can do this using RGBA. It can be done this way, where the fourth parameter is the Alpha value.:

``` HIColor.initWithRGBA(70, 130, 180, 0.6) ```

**Comment by PallaviTapkir** [comment]
@soommy12   I want set multiple colors. So I am calling 

`HIPie pie = new HIPie();
            pie.setColors(getColorList());`

And this `setColors `methods accepts only `List<String>`.

**Comment by soommy12** [comment]
You can add colors to the list like this:
```
List<String> myColorList = new ArrayList<>();
myColorList.add((String) HIColor.initWithRGBA(70,130,180,0.6).getData());
```

**Comment by PallaviTapkir** [comment]
> You can add colors to the list like this:
> 
> ```
> List<String> myColorList = new ArrayList<>();
> myColorList.add((String) HIColor.initWithRGBA(70,130,180,0.6).getData());
> ```

It works!!! Thanks
