### ISSUE TITLE
Not able to add X-Axis and Y-Axis values in date format

### ISSUE THREAD

**Issue by PallaviTapkir** [highcharts/highcharts-android#127]
![Screenshot_20191118-113136_Finaureus Polo](https://user-images.githubusercontent.com/17737793/69028475-1d84c000-09f8-11ea-90be-2b51f941f0f2.jpg)

I want set X-axis labels in Date format and Y-axis labels as per response parameter. 
I am not able to set them.

Below is code I tried so far.

`xAxisPortfolioData.clear();
        xAxisBenchmarkData.clear();
        yAxisBenchmarkData.clear();
        yAxisPortfolioData.clear();

        ThematicSeries portfolioSeries = runValuation.getSeries().get(0);
        for (int i = 0; i < portfolioSeries.getData().size(); i++) {
            long timestamp = Long.parseLong(portfolioSeries.getData().get(i).get(0));
            double yAxisValue = Double.parseDouble(portfolioSeries.getData().get(i).get(1));
            yAxisValue = Math.abs(yAxisValue);
            yAxisPortfolioData.add(String.valueOf(StringUtils.formatDecimalNumber(yAxisValue)));

            String date = DateUtils.getDateFromTimestamp(timestamp);
            xAxisPortfolioData.add(date);
        }
        ThematicSeries benchmarkSeries = runValuation.getSeries().get(0);
        for (int i = 0; i < benchmarkSeries.getData().size(); i++) {
            long timestamp = Long.parseLong(benchmarkSeries.getData().get(i).get(0));
            double yAxisValue = Double.parseDouble(benchmarkSeries.getData().get(i).get(1));
            yAxisValue = Math.abs(yAxisValue);
            yAxisBenchmarkData.add(String.valueOf(StringUtils.formatDecimalNumber(yAxisValue)));

            String date = DateUtils.getDateFromTimestamp(timestamp);
            xAxisBenchmarkData.add(date);
        }`

and setting both lists to the spline graph as 
for X-axis
`xAxis.setCategories(xAxisPortfolioData);`

for Y-axis
`yAxis.setCategories(yAxisPortfolioData);`

How can achieve the desired output?

**Comment by soommy12** [comment]
Hi @PallaviTapkir ! You can check this one: https://api.highcharts.com/highcharts/xAxis.dateTimeLabelFormats

and then set up your `HIXAxis`:

```
HIXAxis axis = new HIXAxis();
axis.setType("datetime");
axis.setDateTimeLabelFormats(new HIDateTimeLabelFormats());
axis.getDateTimeLabelFormats().setDay(new HIDay());
axis.getDateTimeLabelFormats().getDay().setMain("%e of %b"); // this will give e.g.: 1 of Jan
options.setXAxis(new ArrayList<>(Collections.singletonList(axis)));
```

having that, you can give a starting point to your series and a point interval, let's say:
```
series.setPointStart(new Date(99,0,1).getTime()); // starting from 1.1.1999
series.setPointInterval(24 * 3600 * 1000); // one day
```
