### ISSUE TITLE
Erratic issue on load

### ISSUE THREAD

**Issue by LaurentKinomap** [highcharts/highcharts-android#128]
Hi, 
Using an area spline into a fragment, 1 out of 10 time, the chart does not appear and I don't understand why. Note that the activity contains several other fragments.
The data series comes from already loaded variables.
Note that the same chart is called and built in another activity without any problem.
Attached some screenshots showing the screens with explicit names (note that some screenshots were done on iOS but we're indeed talking about Android only here)
Thanks for your help!

![always_loading_on_this_screen](https://user-images.githubusercontent.com/2536885/69067447-5ede9500-0a23-11ea-8924-edafe8d609ba.png)
![90%_ofthetime_loading](https://user-images.githubusercontent.com/2536885/69067448-5ede9500-0a23-11ea-8a68-9f02f4434e73.png)
![10%_ofthetime_not loading](https://user-images.githubusercontent.com/2536885/69067451-5ede9500-0a23-11ea-892a-a0406264aad6.jpg)

Laurent

**Comment by soommy12** [comment]
Hi @LaurentKinomap ! Thank you for the question. Thanks for the information you gave us there is no way to define the problem. During our internal tests, we didn't meet such behaviour. Can you please share some code or explain what do you mean by "data series comes from already loaded variables."? That would be very helpful to replicate the issue.

**Comment by LaurentKinomap** [comment]
Hi @soommy12 Pour répondre a ton mail @laurent:
Les données du graphique sont déjà stockées dans un singleton lorsque l'on arrive sur l'activité.
Dans cette activité, il y a plusieurs fragments dont celui qui doit afficher le graphique. Lorsque le graphique est initialisé, les données sont bien présente (j'ai vérifié dans les logs) pourtant, et aléatoirement, le graphique ne s'affiche pas.
