### ISSUE TITLE
DataLabels not showing in Android

### ISSUE THREAD

**Issue by JibuVarghese** [highcharts/highcharts-android#129]
I am setting like below to show data label  .
 Using library version 7.2.1

                HIDataLabelsOptionsObject hiDataLabelsOptionsObject = new HIDataLabelsOptionsObject();
                hiDataLabelsOptionsObject.setEnabled(true);
                ArrayList<HIDataLabelsOptionsObject> dataLabelList = new ArrayList<>();
                dataLabelList.add(hiDataLabelsOptionsObject);
                plotOptions.getSpline().setDataLabels(dataLabelList);

If I set dataLabel like above spline is not showing and if I comment above piece of code chart spline is showing without data labels. 
please help me in showing spline chart with datalabels. Previously I was using 6.1.4 where it was working fine because of databinding issues I updated to new version 7.2.1

**Comment by soommy12** [comment]
Hello @JibuVarghese ! Thank you for reporting this bug. I will dive into it.

**Comment by soommy12** [comment]
The class `HIDataLabelsOptionsObject ` is not present in the library at this moment. Please use `HIDataLabels` instead.
