### ISSUE TITLE
Show HiMarker only for the last x data

### ISSUE THREAD

**Issue by nivCoindash** [highcharts/highcharts-android#13]
Hey, 

Im trying to add marker for the last point on x axis. 
there is a way to achieve this? 

i tried to add object to the data - 

`public class ChartData extends ArrayList<Object> {

    private Number y;
    private Number x;
    private HIMarker marker;

    public ChartData(Number y, Number x, HIMarker marker) {
        this.x = x;
        this.y = y;
        this.marker = marker;

        add(x);
        add(y);
        add(marker);
    }
}
`

Thank you, 

Niv

**Comment by nivCoindash** [comment]
@soommy12  first of all tank you for your help!

im passing a ArrayList<ArrayList> to the chart. 

1, what is the best practice?
2, iv to use HashMap? or there is another way?

Thank you, niv

**Comment by soommy12** [comment]
When it comes to Highcharts specific object class you need to use maps. They key in the single node tells the wrapper how to serialize it properly. In other situations please check this: #5

**Comment by nivCoindash** [comment]
ok iv managed to add marker to the last point!

thank you for your help!!
