### ISSUE TITLE
How do I change the default text？

### ISSUE THREAD

**Issue by cjlkbxt** [highcharts/highcharts-android#133]
How do I change the default text of HITooltip in the HIBoxplot?such as Maximum、Upper quartile、Median、Lower quartile、Minimum.

**Comment by soommy12** [comment]
Hello @cjlkbxt ! You can use `setPointFormat` or `setPointFormatter` methods. I really encourage you to read the [documentation]([url](https://api.highcharts.com/android/highcharts/com/highsoft/highcharts/Common/HIChartsClasses/HITooltip.html)).
