### ISSUE TITLE
HIDataLabelsOptionsObject for bubble's datalabel throws uncaught exception

### ISSUE THREAD

**Issue by SSJ2912** [highcharts/highcharts-android#134]
When I set dataLabel for Bubble Chart, it throws "Uncaught TypeError: Cannot read property 'color' of undefined"

 val plotOptions = HIPlotOptions()
        plotOptions.bubble = HIBubble().apply {
            dataLabels = arrayListOf(HIDataLabelsOptionsObject().apply {
                enabled = true
                format = "{point.name}"
            })
        }

**Comment by soommy12** [comment]
Hello @SSJ2912 ! Which version of the library do you use?

**Comment by SSJ2912** [comment]
Hello @soommy12 
We have been using v7 for our apps and we will migrate to v8 in the upcoming versions of our apps. Is it possible to fix this issue in version 7?

**Comment by soommy12** [comment]
I'm afraid that there is no such option. I really encourage you to migrate to 8.0. It solves some crucial problems.

**Comment by MrunalDesale** [comment]
@soommy12 @SSJ2912 
Can you post solution? Not working for me.
My code is:

val packedbubble1 = HIPackedbubble()
        packedbubble1.name = "Europe1"
        val data11 = HIData()
        data11.name = "Germany"
        data11.value = 767
        packedbubble1.data = ArrayList(
            listOf(
                data11
            )
        )
        val dataLabel = HIDataLabels()
        dataLabel.enabled = true
        dataLabel.format = "{point.name}"
        packedbubble1.dataLabels = arrayListOf(dataLabel)

**Comment by soommy12** [comment]
Well, the code you posted is working like a charm @MrunalDesale . Did you attach `HICPackedbubble` instance to your series list?
