### ISSUE TITLE
A crash happened

### ISSUE THREAD

**Issue by cjlkbxt** [highcharts/highcharts-android#136]

**Comment by cjlkbxt** [comment]
I met a crash。
#16505 android.content.res.Resources$NotFoundException
String resource ID #0x2040003

com.highsoft.highcharts.core.HIChartView.a(SourceFile:137)

**Comment by soommy12** [comment]
Hi @cjlkbxt ! Can you please share you options code?

**Comment by cjlkbxt** [comment]
1 android.view.InflateException:Binary XML file line #61: Error inflating class com.highsoft.highcharts.core.HIChartView
--
2 android.view.LayoutInflater.createView(LayoutInflater.java:642)
3 ......
4 Caused by:
5 android.content.res.Resources$NotFoundException:String resource ID #0x2040003
6 android.content.res.Resources.getText(Resources.java:318)
7 android.content.res.VivoResources.getText(VivoResources.java:123)
8 android.content.res.Resources.getString(Resources.java:404)
9 com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:694)
10 com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:618)
11 com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)

Not all mobile happened，but one mobile happened。I just use the layout such as` <com.highsoft.highcharts.core.HIChartView
                    android:id="@+id/hc"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">`

**Comment by soommy12** [comment]
Was that API 22 or 21?

**Comment by cjlkbxt** [comment]
API 22

**Comment by soommy12** [comment]
In that case, you should check [this](https://github.com/highcharts/highcharts-android/issues/115) out. It is a known problem with Android WebView on API 21/22.
