### ISSUE TITLE
Dynamic change of plotLine

### ISSUE THREAD

**Issue by svivian1993** [highcharts/highcharts-android#137]
Hello,

I have a chart and I have added to the yAxis a plotLine. What I would like is when I press a button to set a new value to the plotline. Right now I reset the new options to my chart but nothing happens. Though through debugging I can see in my chart object that the new value is set correctly. I am calling the update method from my chart, I even used redraw separately, but the line doesn't change position in the graph. Do you have any suggestion of why it's not rendering again?

**Comment by soommy12** [comment]
Hi @svivian1993 ! Sorry for the late response. To achieve this you need to set the new series on the options object then set the options to your chart view again.

**Comment by svivian1993** [comment]
Yes it worked! Thank you so much for the response.
