### ISSUE TITLE
how to add params to hipoint so i can use them and show them in datalables 

### ISSUE THREAD

**Issue by sarah-geara** [highcharts/highcharts-android#139]
how to add params to hipoint so i can use them and show them in datalables 

i have tried this way to add the params to hipoint and then to add the hipoint to hicolomn :
HIPoint hiPoint =new HIPoint();
column.setPoint(hiPoint);
column.getPoint().getParams().put("age","1.0");

and then show it like this in the datalables : 
plotOptions.getSeries().getDataLabels().setFormat("{point.age:.1f}%");

p.s: i am using this version 6.1.4

Please need help

**Comment by sarah-geara** [comment]
unfortunately it's showing the data lable without the correct value , it's showing 0.0 always

**Comment by soommy12** [comment]
Hi @sarah-geara ! You need to use formatter instead of fromat. Those custom params can be referred to in HIFunction. It was discussed in https://github.com/highcharts/highcharts-android/issues/102
