### ISSUE TITLE
incompatible types: HIDataLabels cannot be converted to ArrayList

### ISSUE THREAD

**Issue by paulagaitan97** [highcharts/highcharts-android#140]
Hi, I am implementing network-graph in an android application.
I initially use the base code of network-graph 
(https://www.highcharts.com/android/demo/network-graph). 
but it generates three errors:
![image](https://user-images.githubusercontent.com/23261158/77093919-b264ed80-69d9-11ea-8b97-090b1758129c.png)

Implementation steps:

![image](https://user-images.githubusercontent.com/23261158/77094131-0c65b300-69da-11ea-823b-355bce746acc.png)

![image](https://user-images.githubusercontent.com/23261158/77094348-564e9900-69da-11ea-9646-4b224ed540f9.png)

![image](https://user-images.githubusercontent.com/23261158/77094454-81d18380-69da-11ea-846c-a21e6852a625.png)

ERROR :

![image](https://user-images.githubusercontent.com/23261158/77094665-d248e100-69da-11ea-9a32-a12ff5d1d51b.png)

![image](https://user-images.githubusercontent.com/23261158/77094770-fad0db00-69da-11ea-922c-1fcfc0932899.png)

**Thanks for your attention. I'd appreciate your help**

**Comment by soommy12** [comment]
Hi there! Thanks for the question! The demo on the website is not up to date. `HIDataLabels` should be passed in the list. Check this out:
```
HINetworkgraph networkgraph = new HINetworkgraph();
ArrayList<HIDataLabels> dataLabelsList = new ArrayList<>();
HIDataLabels dataLabels = new HIDataLabels();
dataLabels.setEnabled(true);
networkgraph.setDataLabels(dataLabelsList);
options.setSeries(new ArrayList<>(Collections.singletonList(networkgraph)));
```

**Comment by paulagaitan97** [comment]
Hi, Thanks for answering. 

Apply what you suggested but I still have an error :

![image](https://user-images.githubusercontent.com/23261158/77174464-17c6e600-6a8f-11ea-8877-8ec7404cead2.png)

**Comment by paulagaitan97** [comment]
And other question..

how do i add the data?

![image](https://user-images.githubusercontent.com/23261158/77175531-c91a4b80-6a90-11ea-8dcb-652de461649b.png)

**Comment by paulagaitan97** [comment]
Please a solution. thanks

**Comment by soommy12** [comment]
What version of the library are you using?

**Comment by paulagaitan97** [comment]
8.0

**Comment by paulagaitan97** [comment]
If you can give me an example, I would appreciate it.  From network-graph

**Comment by soommy12** [comment]
Hi! You have data already added to your chart. This is how you set them up for this specific series type. When it comes to the incompatible types - that is strange. I can't reproduce this error.

**Comment by paulagaitan97** [comment]
If you can give me an example, I would appreciate it. From network-graph

**Comment by soommy12** [comment]
> Hi there! Thanks for the question! The demo on the website is not up to date. `HIDataLabels` should be passed in the list. Check this out:
> 
> ```
> HINetworkgraph networkgraph = new HINetworkgraph();
> ArrayList<HIDataLabels> dataLabelsList = new ArrayList<>();
> HIDataLabels dataLabels = new HIDataLabels();
> dataLabels.setEnabled(true);
> networkgraph.setDataLabels(dataLabelsList);
> options.setSeries(new ArrayList<>(Collections.singletonList(networkgraph)));
> ```

The example is already given here. If you're having any problems with it you can try to pass `HISeries` into ArrayList's diamond operator.

**Comment by paulagaitan97** [comment]
but how do I add the data?

**Comment by soommy12** [comment]
As you can see in the demo code (which you posted via link) the data is created by a list of pairs (the pair is represented by the two-element table, the contents in such pair mean that those two points on the graph are connected.

**Comment by paulagaitan97** [comment]
but how do I add the data with the solution you gave. arraylist <HiDataLabels>

**Comment by paulagaitan97** [comment]
but how do I add the data with the solution you gave. arraylist <HiDataLabels>??

**Comment by soommy12** [comment]
Yes, you should use ArrayList, exactly the same as the example says.

**Comment by mallipurna03** [comment]
I am also facing the same issue for **Column with drilldown chart**
```
HIPlotOptions plotOptions = new HIPlotOptions();
plotOptions.setSeries(new HISeries());
plotOptions.getSeries().setDataLabels(new HIDataLabels);
plotOptions.getSeries().getDataLabels().setEnabled(true);
plotOptions.getSeries().getDataLabels().setFormat("{point.y:.1f}%");
options.setPlotOptions(plotOptions);
```
