### ISSUE TITLE
Failed to resolve: com.highsoft.highcharts:highcharts:8.0.4

### ISSUE THREAD

**Issue by RuiRoque** [highcharts/highcharts-android#142]
Did the repository change? I can only find 8.0 as the latest in bintray.

Adding the AAR in libs is not really an option since this is a dependency of a module.

**Comment by soommy12** [comment]
Yes, you're right. At this moment the 8.0.4 version is not available as a Gradle dependency. I'm afraid it won't be in the near future.

**Comment by SSJ2912** [comment]
Hi @soommy12 ,
This version has certain bug fixes from the previous ones which we are in need of. We would require this version as gradle dependency for our project's release. Can we get an ETA on when will this version be available?

**Comment by soommy12** [comment]
Hi @SSJ2912 ! There's no ETA for this version as gradle dependency.
