### ISSUE TITLE
Icon for data label

### ISSUE THREAD

**Issue by 2ma** [highcharts/highcharts-android#144]
Hello, I would like to add icons as data labels, and the closest I have found would be something similar to this: `dataLabels: [{
            enabled: true,
            format: '<div style="width: 20px; height: 20px; overflow: hidden; border-radius: 50%; margin-left: -25px">' +
                '<img src="https://www.highcharts.com/images/employees2014/{point.assignee}.jpg" ' +
                'style="width: 30px; margin-left: -5px; margin-top: -2px"></div>',
            useHTML: true,
            align: 'left'
        }, {
            enabled: true,
            format: '<i class="fa fa-{point.fontSymbol}" style="font-size: 1.5em"></i>',
            useHTML: true,
            align: 'right'
        }]` 
. My question is, is it possible to use local resource assets somehow in Android, or it has to be an url? Thanks!

**Comment by soommy12** [comment]
Hi @2ma ! It is not possible to use android asset, it has to be an url.

**Comment by 2ma** [comment]
Hey @soommy12 thanks for the answer! I found out that, if you put your images in the android assets folder, you can load them locally using the file:///android_asset/someimage.png url.
Svg-s work too. It can be used dynamically as I wrote in the original question:
file:///android_asset/{point.icon}.png
