### ISSUE TITLE
How to set rounded corners for ResetZoom button

### ISSUE THREAD

**Issue by alessioscudieri** [highcharts/highcharts-android#145]
Hi!

I'm trying to add rounded corners for the ResetZoom button.
This code unfortunately is not working:
  HICSSObject hicssObject = new HICSSObject();
  hicssObject.setBorderRadius(3);
  attrs.setStyle(hicssObject);
  resetZoomButton.setTheme(attrs);

I have found this .js example :

 resetZoomButton: {
            theme: {
                r: 18,
                ....

that "r" param is exactly what I'm looking for.
Could you please help me?

thanks

**Comment by soommy12** [comment]
Hi @alessioscudieri ! Thanks for the question! Is that example tested in Highcharts JS library already? Can you please share with me that?

**Comment by alessioscudieri** [comment]
Hi @soommy12 ! sure, this is a working example:https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/resetzoombutton-theme/ If you set  "r: 20" for example, it works as expected, but unfortunately I can't get the same result on android.

thanks!

**Comment by soommy12** [comment]
Sorry for the late response. Apparently it is impossible to use members which are not listed [here](https://api.highcharts.com/class-reference/Highcharts.SVGAttributes). This is unfortunate, we will add a method which will let you add any SVG attribute by its name in the next release.

**Comment by alessioscudieri** [comment]
ok thanks!
