### ISSUE TITLE
Heatmap scrollablePlotArea and border issue

### ISSUE THREAD

**Issue by SSJ2912** [highcharts/highcharts-android#146]
Hi,
We are not able to change ScrollablePlotArea's opacity . It is set as transparent even when we set the value as 1.
And is there any property to set borders in between cells of heatmap. We could find borderColor and borderWidth inside HIPie , HIColumn, HIFunnel. But there is no property in heatmap.

**Comment by soommy12** [comment]
HI @SSJ2912 ! Thanks for your question. To set the chart opacity you need to use the following code:
```
HIChart chart = new HIChart();
chart.setScrollablePlotArea(new HIScrollablePlotArea());
chart.getScrollablePlotArea().setOpacity(0.5);
options.setChart(chart);
```
When it comes to `borderColor` property there is none for heatmap by default.

**Comment by SSJ2912** [comment]
Hi @soommy12 ,
Yes we have been using the above code from the previous versions (v7). After upgrading to version 8.0.4, we are getting this issue. The charts are scrollable but the opacity is transparent(0f) even after setting it a value nearer to 1.0

**Comment by soommy12** [comment]
Did you try it on the 8.1.1 ?
