### ISSUE TITLE
DataLabels not showing

### ISSUE THREAD

**Issue by jai-invest19** [highcharts/highcharts-android#148]
![chart](https://user-images.githubusercontent.com/62373798/84475958-0ca8de00-acab-11ea-99bb-e563e6de13bf.png)

I want show datalables similar to image.
I just coding in android 

**HIDataLabels hiDataLabels = new HIDataLabels();
hiDataLabels.setAllowOverlap(true);
hiDataLabels.setEnabled(true);
hiDataLabels.setShadow(true);
hiDataLabels.setFormat("{point.name}");
hiDataLabels.setDistance(10);
hiDataLabels.setColor(HIColor.initWithHexValue("#FFFFFF"));
series1.setDataLabels(new ArrayList<>(Arrays.asList(hiDataLabels)));**
for label but it's not showing.

**Comment by soommy12** [comment]
Hi @jai-invest19 ! What version of the library are you using at this moment?

**Comment by jai-invest19** [comment]
Hi @soommy12 I am using the latest source code from the github.

**Comment by soommy12** [comment]
Hmm, that's strange. Can you please provide some more code? You can also set the data labels by `HIPlotOptions`. There's a possibility that you are overriding your data labels there so they are not visible.
