### ISSUE TITLE
How to use getSVG in android and iOS app

### ISSUE THREAD

**Issue by MukeshKumarS** [highcharts/highcharts-android#149]
I want to get SVG string from Chart but there is no option for getSVG() in android or iOS module.

**Comment by soommy12** [comment]
Hi @MukeshKumarS ! Thank you for your question. Did you mean `HISVGAttributes` class? It can be used only for `HIDataLabels`, `HIHalo`, `HIExporting`, `HINoData`, `HIPatternOptionsObject`, `HIResetZoomButton` and `HITextPath` classes.  Can you please provide an equivalent from JavaScript library? Maybe we're lacking some feature on the mobile side.

**Comment by MukeshKumarS** [comment]
Hi @soommy12,
Thanks for responding.
I'm trying to convert my chart to SVG string. In all examples that are provided for exporting programmatically in Java Script uses chart.getSVG() or chart.exportChart() to get SVG string of the chart. Whereas in Android or iOS If I want to convert my chart to SVG I can't find any helpful material from your documentation. 

One example for exporting in JS - http://jsfiddle.net/8vw7esjx/3/
               
               // Hide the export button
                options.navigation = HINavigation()
                options.navigation.buttonOptions = HIButtonOptions()
                options.navigation.buttonOptions.enabled = false

               // Enabling export option
                val exporting = HIExporting()
                exporting.enabled = true
                exporting.fallbackToExportServer = false
                exporting.filename = "MyChart"
                options.exporting = exporting

In android, I enabled exporting as shown above. though I don't see those functions and when I checked your documentation regarding this I don't find those methods for exporting. Kindly let me know what I have to do from mobile application.

**Comment by soommy12** [comment]
Ahh, now I know what you're asking about. For mobile versions of the library, only image exporting is available  (e.g. you can pass chart image via chat app or send it via email in png format). There is no ETA for other exports at this moment. Therefore, I will mark this ticket as an enhancement.

**Comment by MukeshKumarS** [comment]
@soommy12 Ok if I can export as PNG. Kindly let me know if there is any sample for it.
I'll convert it to SVG or I'll upload has a file to my server.

**Comment by soommy12** [comment]
You're right, there is no such method in the android wrapper. Clicking on the export button (while `HIExporting` is enabled and attached to chart) will create a new intent (of _image/png_ type) passing there a generated file. This process is hidden for the end-user. In case you want to pass chart image to your backend server there is no method to achieve that.

**Comment by MukeshKumarS** [comment]
@soommy12  
Then only option common for both Android and iOS for sending graph for now is using highcharts server in our server. Am I right?

**Comment by MukeshKumarS** [comment]
@soommy12 
Then the only possibility for exporting Graph that is common for Android and iOS is using Node Server (https://www.highcharts.com/docs/export-module/setting-up-the-server). Am I right?

**Comment by soommy12** [comment]
@MukeshKumarS, to be honest, I have no idea. I've never tested this one on any mobile platform.

**Comment by MukeshKumarS** [comment]
@soommy12 
Thanks for your time. Thank you so much
