### ISSUE TITLE
Event listener on pie chart

### ISSUE THREAD

**Issue by umersaleem78** [highcharts/highcharts-android#150]
I'm trying to implement event listener on pie chart and some other charts but it is throwing an exception of null pointer.
I tried searching for the solution but didn't find any solution.
I'm using the below code:
//setting data here
 pie.setData(data);
//setting event listener here
 pie.getPoint().setEvents(new HIEvents());
        
        pie.getPoint().getEvents().setClick(new HIFunction(
                (HIChartContext f) -> {
                    Toast t = Toast.makeText(
                            this,
                            "Clicked point [ " + f.getProperty("x") + ", " + f.getProperty("y") + " ]",
                            Toast.LENGTH_SHORT);
                    t.show();
                },
                new String[] {"x", "y"}
        ));

Exception:
 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.highsoft.highcharts.Common.HIChartsClasses.HIPoint.setEvents(com.highsoft.highcharts.Common.HIChartsClasses.HIEvents)' on a null object reference

Exception occurs on this line:
 pie.getPoint().setEvents(new HIEvents());

**Comment by soommy12** [comment]
Hi @umersaleem78 ! Thank you for your quesiton. Did you set `HIPoint` object to your pie chart? Before the line where exception occurs, you should put ```pie.setPoint(new HIPoint());```

**Comment by umersaleem78** [comment]
> Hi @umersaleem78 ! Thank you for your quesiton. Did you set `HIPoint` object to your pie chart? Before the line where exception occurs, you should put `pie.setPoint(new HIPoint());`

I missed that point. after setting the 'HiPoint' object it is now working fine. Will the listener be implemented similarly for all the charts ?

**Comment by umersaleem78** [comment]
> Hi @umersaleem78 ! Thank you for your quesiton. Did you set `HIPoint` object to your pie chart? Before the line where exception occurs, you should put `pie.setPoint(new HIPoint());`

I'm facing another issue as well. 

HIPlotOptions plotOptions = new HIPlotOptions();
        plotOptions.setPie(new HIPie());
        plotOptions.getPie().setAllowPointSelect(true);
        plotOptions.getPie().setCursor("pointer");
        plotOptions.getPie().setDataLabels(tags);

        //plotOptions.getPie().getDataLabels().getStyle().setColor("#000000");
        options.setPlotOptions(plotOptions);

Whenever I use these lines to set the plotting options, there is an exception. When I comment out these lines everything runs fine. Can you point out the issue in these lines? I'm using version 8.1.2

Exception:

java.lang.ClassCastException: java.lang.String cannot be cast to com.highsoft.highcharts.core.HIFoundation

**Comment by soommy12** [comment]
I am pleased that your problem mentioned in the ticket name was fixed. 

> Will the listener be implemented similarly for all the charts ?
Yes, exactly.

>plotOptions.getPie().setDataLabels(tags); //tags is a string arraylist
tags should be an array list of `HIDataLabels` objects

If you have further questions which are not connected to the subject please create another ticket.

**Comment by umersaleem78** [comment]
OK Thank you.
