### ISSUE TITLE
Type question for HIDataLabels

### ISSUE THREAD

**Issue by cjlkbxt** [highcharts/highcharts-android#151]
Why was the class HIDataLabels used the type of String for y，but the type of Number for x？

**Comment by soommy12** [comment]
Hi @cjlkbxt ! Thank you for spotting that issue. It is indeed strange, and definitely both values should be of Number type. We will fix that in the next build.

**Comment by pawelfus** [comment]
Related core issue: https://github.com/highcharts/highcharts/issues/13699
