### ISSUE TITLE
I want to add icon on treeMap 

### ISSUE THREAD

**Issue by ahmedKhaledMohammed** [highcharts/highcharts-android#152]
I want to add a generic icon on TreeMap chart and several labels not just one label but it gets out of its cell
<img width="379" alt="Screen Shot 2020-07-21 at 2 24 43 PM" src="https://user-images.githubusercontent.com/28790458/88049507-ef92e500-cb5d-11ea-9820-51627df23219.png">

       hiFunction = new HIFunction("(function() {return '<div style=\"vertical-align:middle;\">" +
                "<img src=\"file:///android_res/drawable/' + this.point.imageName + '.png\"  ></img>" +
                "<br>" +
                "<label for=\"lfname\">' + this.point.name + '</label>" +    "<br>" +
                "<label for=\"lfname\">' + this.point.name2 + '</label>" +   "<br>" +
                "<label for=\"lfname\">' + this.point.name3 + '</label>" +   "<br>" +
                "<label for=\"lfname\">' + this.point.value + '</label>" +   "<br>" +
                "</div>';})");

        dataLabels.setFormatter(hiFunction);

**Comment by soommy12** [comment]
Hi @ahmedKhaledMohammed! I'm sorry for the late response. This image is definitely too large. You can try to resize it in the HTML code but remember that this will behave differently on different devices. There is no solution from the Android perspective to your problem. If you are using direct javascript injection you should follow the original Higcharts library solutions.
