### ISSUE TITLE
Incompatible with Hilt DI

### ISSUE THREAD

**Issue by mardann** [highcharts/highcharts-android#153]
When a `Fragment`/`Activity`, who's view contains a `com.highsoft.highcharts.core.HIChartView`, and is annotated with `@AndroidEntryPoint`, then inflation fails with the following error:
`Caused by: java.lang.ClassCastException: dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper cannot be cast to android.app.Activity
        at com.highsoft.highcharts.core.HIChartView.<init>(SourceFile:562)`

my work around was to create an intermediate `HIChartView` wrapper that extracts `context` properly:

`open class SafeHiChartsView @JvmOverloads constructor(context: Context, attrs: AttributeSet? = null): HIChartView(getActivity(context), attrs) {
    
    companion object {
        fun getActivity(context: Context): Context {
            return if (context is ViewComponentManager.FragmentContextWrapper) {
                context.baseContext
            } else context
        }
        
    }
    `

**Comment by soommy12** [comment]
Hello @mardann ! The Higcharts library was not yet tested with Hilt DI. Anyway, it's strange because it is working well with Dagger. We definitely look forward to making it compatible as Hilt is part of Android Architecture components. Unfortunately, this is not our top priority for now but we have it on our radar.

**Comment by mardann** [comment]
Thanks for the quick reply!
Hilt differs from Dagger in that it generates a _base class_ for every class annotated with `@AndroidEntryPoint`. this generated class then holds all the Dagger boilerplate usually implemented in android.
Importantly, this generated class is injected as a _parent class_ of the annotated class at compile time at the bytecode level, and then it provides the `context` as a  `FragmentContextWrapper` - which doesn't inherit from `Activity`, thus the inflation error.

Anyway, the workaround works, and maybe a better solutions would be to not depend on `Activity` at all, but on `Context`?

**Comment by dutchmanbd** [comment]
@mardann how your workaround works. I wrote below code but not working for me. Please help me. Thank you.

open class SafeHiChartsView @JvmOverloads constructor(context: Context, attrs: AttributeSet? = null): HIChartView(getActivity(context), attrs) {

}

**Comment by MikolajMichalczak** [comment]
Hi all!
This issue was fixed in version 11.4.1.
