### ISSUE TITLE
Rounded corners in Android 

### ISSUE THREAD

**Issue by anarghya-das** [highcharts/highcharts-android#155]
I am trying to find how do I achieve getting rounded corners around the chart view in android. I tried setting a custom drawable to the android:background property in the xml of HIChartView but that did not work. Is there any way I can do this?

**Comment by soommy12** [comment]
Hi @anarghya-das ! Do you mean rounded corners for the HIChartView or the chart inside the view? The first one can be achieved by putting your HIChartView inside a CardView. The second option is [this plugin](https://github.com/highcharts/rounded-corners) but it is not embedded into the wrapper. We could add this into the next release but I definitely advise you to use the first option as it is the native one and should work the best. CardView with some padding should do the perfect job!

**Comment by anarghya-das** [comment]
@soommy12 Thank you, the CardView worked! That's what I wanted to do.
