### ISSUE TITLE
comma issue

### ISSUE THREAD

**Issue by sarah-geara** [highcharts/highcharts-android#157]
hello i am using bar highchart , i have an issue concerning formatting numbers in tooltip i tried this way :
tooltip.setPointFormat("<table><tr><td>{point.name}: </td><td style=\"text-align: right\"><b>{point.y:,.2f}</b></td></tr>");

and also this way : 
  chartView.lang = new HILang();
  chartView.lang.setThousandsSep(",");

please note that i am using hichart in recyclerview .
Also note that when i use my hichart in a view pager the comma is showing.
Please help me to fix this, i am using this version : 6.1.4

**Comment by sarah-geara** [comment]
is there an other way ?? anyone can help please

**Comment by sarah-geara** [comment]
@soommy12 please advice

**Comment by soommy12** [comment]
Hi there @sarah-geare ! What is your expected result? What would you like to see on the chart when it comes to the number on your tooltip? Additionally, I strongly recommend using the newest version of the library.

**Comment by sarah-geara** [comment]
@soommy12  i want to see on the tooltip the number formatted with comma "," instead of space
When using the bar chart inthe recyclerview it's not working but when using the bar chart in the viewpager it's working.

**Comment by sarah-geara** [comment]
@soommy12  for example : in recyler view the number in tool tip is showing : 300 502  but in the view pager the number in tool tip is showing : 300,502
Advice please

**Comment by soommy12** [comment]
Well, if in one case the commas are visible that's great. You should be able to do that in both cases. Highcharts library is not widget dependent. Are you sure you are injecting the same options?
