### ISSUE TITLE
Not getting label on bar chart

### ISSUE THREAD

**Issue by sahil0289** [highcharts/highcharts-android#158]
how to get label on bar chart.

**Comment by soommy12** [comment]
Hi @sahil0289! To get a label on bar chart you first need to set it by `setHIDataLabels()` method on your series. For example:
```
HIDataLabels dataLabels = new HIDataLabels();
HISeries series = new HISeries();
series.setDataLabels(new ArrayList<>(Collections.singletonList(dataLabels)));
```

**Comment by sahil0289** [comment]
I have added this but still not getting label on bar chart. I have added my code:-
HIOptions options = new HIOptions();


        HIXAxis xAxis = new HIXAxis();
        xAxis.setType("category");
        xAxis.setLabels(new HILabels());
        xAxis.getLabels().setRotation(-45);
        xAxis.getLabels().setStyle(new HICSSObject());
        xAxis.getLabels().getStyle().setFontSize("13px");
        xAxis.getLabels().getStyle().setFontFamily("Verdana, sans-serif");
        options.setXAxis(new ArrayList<HIXAxis>(){{add(xAxis);}});

        HIYAxis yAxis = new HIYAxis();
        yAxis.setMin(0);
        yAxis.setTitle(new HITitle());
        yAxis.getTitle().setText("Population (millions)");
        options.setYAxis(new ArrayList<HIYAxis>(){{add(yAxis);}});

        HILegend legend = new HILegend();
        legend.setEnabled(false);
        options.setLegend(legend);

        HITooltip tooltip = new HITooltip();
        tooltip.setPointFormat("Population in'2008': <b>{point.y:.1f} millions</b>");
        options.setTooltip(tooltip);
        HIColumn series1 = new HIColumn();
        series1.setName("Population");

        Object[] object1 = new Object[] { "Shanghai", 23.7 };
        Object[] object2 = new Object[] { "Lagos", 16.1 };
        Object[] object3 = new Object[] { "Istanbul", 14.2 };
        Object[] object4 = new Object[] { "Karachi", 14 };
        Object[] object5 = new Object[] { "Mumbai", 12.5 };





        **ArrayList<HIDataLabels> dataLabelsList = new ArrayList<>();
        HIDataLabels dataLabels = new HIDataLabels();
        dataLabels.setEnabled(true);
        series1.setDataLabels(dataLabelsList);**



        series1.setData(new ArrayList<>(Arrays.asList(object1, object2, object3, object4, object5)));


        options.setSeries(new ArrayList<>(Arrays.asList(series1)));

        chartView.setOptions(options);

**Comment by sahil0289** [comment]
my dependency is :-implementation 'com.highsoft.highcharts:highcharts:8.1.2'
