### ISSUE TITLE
which release compatible with android api level 25 ?

### ISSUE THREAD

**Issue by mthri** [highcharts/highcharts-android#159]
Hi,
I want use this chart on devices has android api level 25 above.
also i try use [release v8.1.2](https://github.com/highcharts/highcharts-android/releases/tag/v8.1.2) but not work on my android device(Android 8), asked question in [stackoverflow ](https://stackoverflow.com/questions/63450747/use-highcharts-in-android) and got this answer :  _it could only run on devices at API level 27 (Android 8.1) and higher_

Please told me each release compatible which android api.
Thanks!

**Comment by soommy12** [comment]
Hi@mthri all releases are compatible with API level 25. The min API version is 19

**Comment by mthri** [comment]
Thanks for reply @soommy12 
I could not use *release v8.1.2* on my device (Android 8.0 or API level 26) did not launch, anyway,i chose *v6.1r*, thas works fine.

**Comment by soommy12** [comment]
Can you please share what exactly happened on your phone @mthri ? I just tested the lib on API 26 and it was working perfectly fine.
