### ISSUE TITLE
Hello, I want to format the head of HITooltip

### ISSUE THREAD

**Issue by phoebewow** [highcharts/highcharts-android#160]
Hello, I have used multiple sets of data. I want to format x into the value after the operation of X * 50 / 1000. The header has no formatter. Using hitooltip's formatter directly, when obtaining multiple sets of data on the same x-axis, the following errors occur        

source:
        val tooltip = HITooltip().apply {
            shared = true
            valueDecimals = 2
            followTouchMove = false
            headerFormat = "{point.key} * 50 / 1000 is the number of seconds<br />"
            formatter = HIFunction(
                HIFunctionInterface { f: HIChartContext ->
                    (f.getProperty("x") as Double * 50 / 1000).toString()
                }, arrayOf("x", "y", "points")
            )
        }

E/Highcharts: Uncaught TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'B'
        |     property 'axes' -> object with constructor 'Array'
        |     index 0 -> object with constructor 'e'
        --- property 'chart' closes the circle
E/Highcharts: Uncaught TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'B'
        |     property 'axes' -> object with constructor 'Array'
        |     index 0 -> object with constructor 'e'
        --- property 'chart' closes the circle

And I want to know whether this library is paid or free? If it is paid, how is it charged?

**Comment by phoebewow** [comment]
v8.1.2 release

**Comment by soommy12** [comment]
Hi @phoebewow unfortunately  `circular references` are not supported in mobile versions of the library. Can please tell where do you attach your formatter HIFunction object? That would be really helpful. 

>And I want to know whether this library is paid or free? If it is paid, how is it charged?

highcharts-angular is free but a Highcharts license is required: https://shop.highsoft.com/

**Comment by phoebewow** [comment]
@soommy12 It would be better to add HIFunction support to the header and footer of HITooltip

**Comment by soommy12** [comment]
@phoebewow you can use a `HIFunction` wherever the library lets you do so but some arguments are impossible to manage in `HIFunction` scope due to JavaScript specific behaviour. Please, share your code so we can try to figure out how to overcome this issue!

**Comment by phoebewow** [comment]
[MainActivity.kt.zip](https://github.com/highcharts/highcharts-android/files/5352967/MainActivity.kt.zip)

**Comment by soommy12** [comment]
Hi @phoebewow ! Can you please share this code on GitHub repo?

**Comment by phoebewow** [comment]
https://github.com/phoebewow/highchart_android_demo

**Comment by soommy12** [comment]
@phoebewow Thank you for the demo code! There is a formatter support for the tooltip. The filed name is `formatter`.  According to [the docs](https://api.highcharts.com/highcharts/tooltip.formatter) there is nothing like `value` inside `HITooltip` object. I would suggest you change it simply for `x`. Each object has its own properties, so its always a good move to check the docs in this matter.
```Kotlin
        val tooltip = HITooltip().apply {
            shared = true
            valueDecimals = 2
            followTouchMove = false
            formatter = HIFunction(HIFunctionInterface { f: HIChartContext -> abs((f.getProperty("x") as Double * 50 / 1000)).toString() + "s" }, arrayOf("x"))
        }
```

**Comment by phoebewow** [comment]
@soommy12 
Sorry to reply so long. I've tried your demo code before. I can get the data of X, but the display of other data is gone. I just want to change the headerformat

In addition, I also want to ask, according to my demo code, if the data is OK in 200000 groups, no matter how big it is, it will load very slowly or even oom. Is there a better way to load more data?
