### ISSUE TITLE
Tooltip points to the wrong data point when selected

### ISSUE THREAD

**Issue by SSJ2912** [highcharts/highcharts-android#161]
Hi Team,
For charts with horizontal scroll, when we scroll through the chart and select any of the data points, the tooltip points to the first few data points and not to the current one.
This issue has been previously addressed in the below link. And we notice that it has been fixed in v8.0.1 and above. But we are having license in version 7 and upgrading to latest version for this issue will not solve our case as all our requirements have been met in the current version.
It would be better if we could get the fix in version 7.

Issue:
https://github.com/highcharts/highcharts/issues/12657

**Comment by soommy12** [comment]
Hi @SSJ2912 ! If you have a version 7 license you can use a 7.1.1 which was mentioned as a solution for the issue you linked here.
