### ISSUE TITLE
android tree map (squarified)

### ISSUE THREAD

**Issue by mahmodmasoud2009** [highcharts/highcharts-android#165]
Hi guys , 

I need you help please i have the following tree map **squarified** chart i had some point regarding to it 

 - some squares appears empty 
- also i need to Crop all text in side every square and here is the html text i used 

![Screenshot_1602707390](https://user-images.githubusercontent.com/6525250/96093024-5103ef00-0ed4-11eb-8f2d-7d92a6dd2f1a.png)
[html.txt](https://github.com/highcharts/highcharts-android/files/5383223/html.txt)

**Comment by mahmodmasoud2009** [comment]
this is my class 
package qa.com.thegroup.securities.ui.heatmap;

import android.graphics.Color;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.Nullable;
import com.highsoft.highcharts.common.hichartsclasses.HICredits;
import com.highsoft.highcharts.common.hichartsclasses.HIDataLabels;
import com.highsoft.highcharts.common.hichartsclasses.HIEvents;
import com.highsoft.highcharts.common.hichartsclasses.HIExporting;
import com.highsoft.highcharts.common.hichartsclasses.HILevels;
import com.highsoft.highcharts.common.hichartsclasses.HIOptions;
import com.highsoft.highcharts.common.hichartsclasses.HIPoint;
import com.highsoft.highcharts.common.hichartsclasses.HISeries;
import com.highsoft.highcharts.common.hichartsclasses.HIStyle;
import com.highsoft.highcharts.common.hichartsclasses.HITitle;
import com.highsoft.highcharts.common.hichartsclasses.HITooltip;
import com.highsoft.highcharts.common.hichartsclasses.HITreemap;
import com.highsoft.highcharts.core.HIChartView;
import com.highsoft.highcharts.core.HIFunction;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import butterknife.BindView;
import butterknife.ButterKnife;
import qa.com.thegroup.securities.R;
import qa.com.thegroup.securities.ui.base.BaseActivity;
import qa.com.thegroup.securities.ui.widget.priceswidget.model.PriceInfoObjc;
import qa.com.thegroup.securities.utils.AppLogger;
import qa.com.thegroup.securities.utils.Constants;
import qa.com.thegroup.securities.utils.Util;

public class HeatMapActivity extends BaseActivity {
    private static final String TAG = "HeatMapActivity";
    @BindView(R.id.hc)
    HIChartView chartView;
    @BindView(R.id.ivBack)
    ImageView ivBack;
    @BindView(R.id.tvMarketStatus)
    TextView tvMarketStatus;

    private HITreemap series1 = new HITreemap();
    private HIOptions options = new HIOptions();

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_heat_map);
        setUnBinder(ButterKnife.bind(this));
        initUi();

        ivBack.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                onBackPressed();
            }
        });
    }

    private Integer getMaximumTradeValue(){
        Iterator hmIterator = Constants.getPriceInfoObjcHashMap().entrySet().iterator();
        List<Integer> integerList = new ArrayList<>();
        while (hmIterator.hasNext()) {
            Map.Entry mapElement = (Map.Entry)hmIterator.next();
            PriceInfoObjc priceInfoObjc = ((PriceInfoObjc)mapElement.getValue());
            integerList.add(priceInfoObjc.getTotTrades());
        }
        return Collections.max(integerList);
    }


    private Integer getMinimumTradeValue(){
        Iterator hmIterator = Constants.getPriceInfoObjcHashMap().entrySet().iterator();
        List<Integer> integerList = new ArrayList<>();
        while (hmIterator.hasNext()) {
            Map.Entry mapElement = (Map.Entry)hmIterator.next();
            PriceInfoObjc priceInfoObjc = ((PriceInfoObjc)mapElement.getValue());
            integerList.add(priceInfoObjc.getTotTrades());
        }
        return Collections.min(integerList);
    }

    private HashMap<String, Object> getBaseGreen(){
        HashMap<String, Object> baseGreenColor = new HashMap<>();
        baseGreenColor.put("id", "+");
        baseGreenColor.put("color", "#48C9B0");
        return baseGreenColor;
    }

    private HashMap<String, Object> getBaseRed(){
        HashMap<String, Object> baseRedColor = new HashMap<>();
        baseRedColor.put("id", "-");
        baseRedColor.put("color", "#EC7063");
        return baseRedColor;
    }

    private HashMap<String, Object> getBaseGray(){
        HashMap<String, Object> baseGreyColor = new HashMap<>();
        baseGreyColor.put("id", "=");
        baseGreyColor.put("color", "#808080");
        return baseGreyColor;
    }

    private int getColorWithAlpha(int color, float ratio) {
        int newColor = 0;
        int alpha = Math.round(Color.alpha(color) * ratio);
        int r = Color.red(color);
        int g = Color.green(color);
        int b = Color.blue(color);
        newColor = Color.argb(alpha, r, g, b);
        return newColor;
    }


    private void updatePricesData(){
        // get all total trade min value and max value
//        Double minValue = 589.0;
//        Double maxValue = 8767476.0;
        Integer minValue = getMinimumTradeValue();
        Integer maxValue = getMaximumTradeValue();
        Double  rate_Value = 0.9;

        ArrayList arrayList = new ArrayList();
            AppLogger.i(TAG,Constants.getPriceInfoObjcHashMap().size()+"");
            Iterator hmIterator = Constants.getPriceInfoObjcHashMap().entrySet().iterator();
            while (hmIterator.hasNext()) {
                Map.Entry mapElement = (Map.Entry)hmIterator.next();
                PriceInfoObjc priceInfoObjc = ((PriceInfoObjc)mapElement.getValue());
                HashMap<String, Object> map = new HashMap<>();
                map.put("company_name", priceInfoObjc.getCompanyCode());
                map.put("company_image_link", Constants.COMPANY_LOGO_URL+priceInfoObjc.getCompanyCode()+".svg");
                map.put("value_one",priceInfoObjc.getBidPrice()+" | "+priceInfoObjc.getAskPrice());
                map.put("value_two",priceInfoObjc.getLastPrice()+" | "+priceInfoObjc.getNetChange());
                map.put("value_three",priceInfoObjc.getTotVal()+"");
                map.put("TotalTrade",  priceInfoObjc.getTotVal());
                map.put("value",  ((rate_Value * (priceInfoObjc.getTotVal() - minValue) / (maxValue - minValue)) + 0.1));
                map.put("colorvalue",  "3");
                if(priceInfoObjc.getTickDir().equalsIgnoreCase("+")){
//                    String hexColor = Integer.toHexString(getColorWithAlpha(R.color.base_green, priceInfoObjc.getVar().floatValue()));
                    map.put("color","#48C9B0");
                }
                else
                if(priceInfoObjc.getTickDir().equalsIgnoreCase("-")){
//                    String hexColor = Integer.toHexString(getColorWithAlpha(R.color.base_red, priceInfoObjc.getVar().floatValue()));
                    map.put("color","#EC7063");
                }
                else{
//                    String hexColor = Integer.toHexString(getColorWithAlpha(R.color.base_gray, priceInfoObjc.getVar().floatValue()));
                    map.put("color","#808080");
                }

                arrayList.add(map);
            }

        series1.setData(arrayList);
        options.setSeries(new ArrayList<HISeries>(Arrays.asList(series1)));
        chartView.setOptions(options);
        series1.setPoint(new HIPoint());
        series1.getPoint().setEvents(new HIEvents());
        series1.getPoint().getEvents().setClick(new HIFunction(
                f -> {
                    double xVal = (double) f.getProperty("x");
                    int indx = (int) xVal;
                    HashMap<String, Object> selectedData = new HashMap<>();
                    selectedData = (HashMap<String, Object>) series1.getData().get(indx);
                    ActionDialog  dialog = new ActionDialog((String) selectedData.get("company_name"),
                            (String) selectedData.get("company_image_link"),
                            (String) selectedData.get("value_one"),
                            (String) selectedData.get("value_two"),
                            (String) selectedData.get("value_three")
                            , HeatMapActivity.this);
                    dialog.showDialog();
                },
                new String[] {"x", "y"}
        ));
    }



    @Override
    protected void initUi() {
        tvMarketStatus.setText(getResources().getString(R.string.open));
        chartView.plugins = new ArrayList<>(Arrays.asList("heatmap", "treemap"));

        HICredits hiCredits = new HICredits();// to disable highchart.com Domain
        hiCredits.setEnabled(false);
        hiCredits.setText("");

        HITitle title = new HITitle();
        title.setText(""); // to disable title of chart
        options.setTitle(title);


        options.setExporting(new HIExporting()); // to disable exporting menu
        options.getExporting().setEnabled(false);


        series1.setLayoutAlgorithm("squarified");
        series1.setAlternateStartingDirection(true);
        series1.setLevelIsConstant(false);
        series1.setAnimationLimit(200);



        HILevels level = new HILevels();
        level.setLevel(1);
        level.setLayoutAlgorithm("squarified");
        level.setBorderWidth(3);

        HITooltip tooltip = new HITooltip(); // to disable tool tips
        tooltip.setEnabled(false);
        options.setTooltip(tooltip);

//        HashMap<String, Object> additionalOptions = new HashMap<>();
//        HashMap<String, Object> colorAxis = new HashMap<>();
//        colorAxis.put("minColor", "#FFFFFF");
//        colorAxis.put("maxColor", "#7cb5ec");
//        additionalOptions.put("colorAxis", colorAxis);
//        options.additionalOptions = additionalOptions;

        HIDataLabels dataLabels2 = new HIDataLabels();
        dataLabels2.setEnabled(true);
        dataLabels2.setAlign("left");
        dataLabels2.setCrop(true);
        dataLabels2.setVerticalAlign("left");
        dataLabels2.setUseHTML(true);
        HIFunction hiFunction;
        hiFunction = new HIFunction(Util.readFileFromAssets(this));
        dataLabels2.setFormatter(hiFunction);
        HIStyle style = new HIStyle();
        style.setFontSize("9px");
        style.setColor("#000000");//black
        style.setFontWeight("bold");

        dataLabels2.setStyle(style);
        level.setDataLabels(dataLabels2);

        series1.setLevels(new ArrayList<>(Arrays.asList(level)));

        updatePricesData();


    }
}

**Comment by soommy12** [comment]
Hi @mahmodmasoud2009 ! Thank you for the question, let me investigate your code. I'll back with the answer soon.

**Comment by soommy12** [comment]
There was already a similar question about treemaps here https://github.com/highcharts/highcharts-android/issues/152. When it comes to cropping the text and images you should try to achieve it directly by `HTML` manipulation (this should be done using `HIFunction` supporting directly the javascript code). When it comes to empty squares, the [Higcharts documentation](https://www.highcharts.com/docs/chart-and-series-types/treemap#squarified) says the squarified algorithm will try to fit created squares to chart area so no additional squares are created. My bet is on your data set. You're doing some iteration over to apply icons/text. During this process, try to find an entry, which does not meet the requirements for this - it should be the empty square.
