### ISSUE TITLE
Get Legend Click Event

### ISSUE THREAD

**Issue by TusharGabani25890** [highcharts/highcharts-android#166]
I just wants to show alert message when any or all **legend(s) getting select or un-select**.

Currently i wants legends click event for **Column** chart type but you can provide the same for all chart types (if possible)

![legneds](https://user-images.githubusercontent.com/12511476/96407409-f41f7600-11fe-11eb-9bcf-35dca40e69ee.png)

**Comment by soommy12** [comment]
Hi @TusharGabani25890 ! I would suggest using `legendItemClick` filed from `HIEvents` object which should be assigned to your `HISeries` (depending on what you have in your code - plotOption series or chartView series). You can find how to show a toast via `HIFunction` object on our Github readme.
