### ISSUE TITLE
stacking not work in Android

### ISSUE THREAD

**Issue by umeshkanhasoft** [highcharts/highcharts-android#167]
i use the stacking="normal" but not work

my code is 

HIChartView chartView = findViewById(R.id.hc);
        HIOptions options = new HIOptions();

        HIChart chart = new HIChart();
        chart.setType("columnrange");
        chart.setScrollablePlotArea(new HIScrollablePlotArea());
        options.setChart(chart);

        HITitle title = new HITitle();
        title.setText("");
        options.setTitle(title);

        HIXAxis xAxis = new HIXAxis();
        String[] categoriesList = new String[]{"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};
        xAxis.setCategories(new ArrayList<>(Arrays.asList(categoriesList)));
        options.setXAxis(new ArrayList<HIXAxis>() {{
            add(xAxis);
        }});

        HIYAxis yAxis = new HIYAxis();
        yAxis.setTitle(new HITitle());
        yAxis.getTitle().setText("Altitude ( °C )");
        options.setYAxis(new ArrayList<HIYAxis>() {{
            add(yAxis);
        }});

        HITooltip tooltip = new HITooltip();
        tooltip.setValueSuffix("°C");
        options.setTooltip(tooltip);

        HIPlotOptions hiPlotOptions = new HIPlotOptions();
        HIColumnrange hiColumnrange = new HIColumnrange();
        hiColumnrange.setStacking("normal");
        hiPlotOptions.setColumnrange(hiColumnrange);
        options.setPlotOptions(hiPlotOptions);

        HILegend legend = new HILegend();
        legend.setEnabled(false);
        options.setLegend(legend);

        HIColumnrange series1 = new HIColumnrange();
        series1.setName("Temperatures");

        Number[][] series1_data = new Number[][]{{10, 5}, {5, -5}};
        series1.setData(new ArrayList<>(Arrays.asList(series1_data)));
        options.setSeries(new ArrayList<>(Arrays.asList(series1)));
        chartView.setOptions(options);

but it working fine in web like
--------------------------------------------
Highcharts.chart('container', {

    chart: {
        type: 'columnrange',
    },

    title: {
        text: 'Layer column chart'
    },
		tooltip: {
        enabled: false,
        pointFormat: '<span style="color:{series.color}">{series.name}</span>: <b>{point.y}</b><br/>',
        shared: true
      },
		xAxis: {
        categories: ['Layer']
      },

    yAxis: {
    		max:15,
        min:10,
        title: {
          text: 'Total Layer consumption'
        },
    },
	

    plotOptions: {
          
         columnrange: {
             stacking:"normal",
         } ,
    },

    legend: {
        enabled: false
    },

    series: [
    	{
        data: [[15, 12],],
    	},
      {
        data: [            [12,10],        ],
    	},
      
      {
        name: `sample123`,
        type: "scatter",
        data: [14],
        color:"#C71585",
      },
      {
        name: `sample1223`,
        type: "scatter",
        data: [15],
        color:"#C71585",
      },
      {
        name: `sample1223`,
        type: "scatter",
        data: [12],
        color:"#C71585",
      }
    ]

});

**Comment by soommy12** [comment]
Hi @umeshkanhasoft ! Try to set series via `plotOptions` object instead of using `options` directly.

**Comment by umeshkanhasoft** [comment]
Thanks
