### ISSUE TITLE
How to refresh data for highchart ?

### ISSUE THREAD

**Issue by ismailtosun** [highcharts/highcharts-android#169]
Hi, when i refresh the page,  I want to refresh my chart with new data ?

how can i do this? chart.reload() is deprecated.

**Comment by soommy12** [comment]
Hi @ismailtosun ! Just reassign series object, then call `update()` method on series.

**Comment by ismailtosun** [comment]
I couldn't found update metot on series

**Comment by soommy12** [comment]
What version of the library are you using?

**Comment by ismailtosun** [comment]
I am using this version :
 implementation 'com.highsoft.highcharts:highcharts:8.1.2'

**Comment by ismailtosun** [comment]
model?.let { i ->
            i.datasource?.let{ j ->
                var categories =  j.filter { !it.name.isNullOrEmpty() }.groupBy { it.name }
                hixAxis.categories = ArrayList(categories.keys)
                var list = ArrayList<HIXAxis>()
                list.add(hixAxis)
                options.xAxis = list

                val totalQty = HIColumn()
                val nokQty   = HIColumn()

                totalQty.name = "Total Qty"
                nokQty.name = "Nok Qty"


                val totalQtyData = ArrayList<Float>()
                val nokQtyData = ArrayList<Float>()

                j.filter { !it.name.isNullOrEmpty() }.forEach { item ->
                    totalQtyData.add(item.totalQuantity?.toFloat() ?: 0f)
                    nokQtyData.add(item.nOKQuantity?.toFloat() ?: 0f)
                }

                totalQty.data = totalQtyData
                nokQty.data = nokQtyData


                var series = ArrayList<HISeries>()
                series.add(totalQty)
                series.add(nokQty)


                options.series = series
                chartView.options = options
            }


        }

**Comment by soommy12** [comment]
Firstly you should update your series object
```Kotlin
options.series = /* your updated series here */
```
Then, you can update it via the method I mentioned:
```Kotlin
chartView.update(options, true)
```
The flag for the method is not required if you do not want the animation of drawing.

**Comment by ismailtosun** [comment]
My Code like this : 

 ```
 model?.let { i ->
            i.datasource?.let{ j ->
                var categories =  j.filter { !it.name.isNullOrEmpty() }.groupBy { it.name }
                hixAxis.categories = ArrayList(categories.keys)
                var list = ArrayList<HIXAxis>()
                list.add(hixAxis)
                options.xAxis = list

                val totalQty = HIColumn()
                val nokQty   = HIColumn()

                totalQty.name = "Total Qty"
                nokQty.name = "Nok Qty"


                val totalQtyData = ArrayList<Float>()
                val nokQtyData = ArrayList<Float>()

                j.filter { !it.name.isNullOrEmpty() }.forEach { item ->
                    totalQtyData.add(item.totalQuantity?.toFloat() ?: 0f)
                    nokQtyData.add(item.nOKQuantity?.toFloat() ?: 0f)
                }

                totalQty.data = totalQtyData
                nokQty.data = nokQtyData


                var series = ArrayList<HISeries>()
                series.add(totalQty)
                series.add(nokQty)


                options.series = series
                chartView.options = options
            }
        }
```

**Comment by soommy12** [comment]
I can see that `HIOptions` object is outside the scope of the code you posted. Just update your options with new data set and update the `chartView ` :) (e.g. in another method)

**Comment by ismailtosun** [comment]
thank u for helping :)
