### ISSUE TITLE
Cannot call HIGFunction

### ISSUE THREAD

**Issue by adirahman** [highcharts/highcharts-android#17]
base on tutorial
https://www.highcharts.com/android/demo/dynamic-update

I cannot call HIGHFunction, i'm using com.highsoft.highcharts:highcharts:6.1.1

**Comment by soommy12** [comment]
Hello,

Unfortunately, demos on the site are outdated. You should use `HIFunction`. The overview of this function can be found in [readme](https://github.com/highcharts/highcharts-android/blob/master/README.md).

**Comment by adirahman** [comment]
Thank's
