### ISSUE TITLE
How to draw target limit ?

### ISSUE THREAD

**Issue by ismailtosun** [highcharts/highcharts-android#170]
hi, thanks for support. 
How to draw final target like that ? 

![Capture](https://user-images.githubusercontent.com/5730271/97406882-f1153b80-190a-11eb-99e9-d46200e93d45.PNG)

**Comment by soommy12** [comment]
Hi @ismailtosun ! You can apply `HIPlotLines` to your `yAxis` object. Check available styles [here](https://api.highcharts.com/class-reference/Highcharts#.DashStyleValue).
