### ISSUE TITLE
set particuler range color in range bar chart 

### ISSUE THREAD

**Issue by umeshkanhasoft** [highcharts/highcharts-android#171]
i want to set particuler range bar color not apply in all series of range
my link is devloped in web like

https://jsfiddle.net/oc1te7w3/1/
hear apply red color but i want to apply only single range not every series of range
also my Android code is ready

   HIColumnrange series2 = new HIColumnrange();
        series2.setName("Temperatures");
        Number[][] numbers2 = new Number[][]{{5, 3}, {8, 3}, {10, 5}};
        series2.setData(new ArrayList(Arrays.asList(numbers2)));
        ArrayList<String> arrayList1 = new ArrayList<>();
        arrayList1.add("#00FF00");
        arrayList1.add("#FF0000");
        arrayList1.add("#0000FF");
        series2.setColors(arrayList1);

like this with acept positive and nagative value also

![rsz_screenshot_from_2020-10-30_16-42-27 (1)](https://user-images.githubusercontent.com/46366675/97699506-45b5e380-1ad0-11eb-9eff-af12ccd254cf.png)

**Comment by soommy12** [comment]
Hi @umeshkanhasoft I will advise you to make use of `HIFunction` and make colour dependent on the value.

**Comment by umeshkanhasoft** [comment]
Thanks for your replay i have solve using 
colorByPoint: true

and also set colors array like
https://jsfiddle.net/gbL5r8ka/2/
