### ISSUE TITLE
i want to display as a Pattern

### ISSUE THREAD

**Issue by umeshkanhasoft** [highcharts/highcharts-android#173]
i want to display HIPatternOptionsObject in graph same like as 
https://codepen.io/jay_gojariya/pen/WNxyjgX
but hear colors object provide as a string array not provide a HIPatternOptionsObject 
can you please help me

**Comment by umeshkanhasoft** [comment]
i need a urgent please help me

**Comment by soommy12** [comment]
Hi @umeshkanhasoft , you can copy the code from JS and pas it as a String and it will render exactly as you want it to.

**Comment by soommy12** [comment]
I am closing this one because the same example was shared here: https://github.com/highcharts/highcharts-android/issues/173. I strongly recommend following this issue.
