### ISSUE TITLE
How to access HiPatternObject

### ISSUE THREAD

**Issue by ashishkanhasoft** [highcharts/highcharts-android#174]
In the android project, 
[I want to integrate pattern same as integrated into web](https://codepen.io/jay_gojariya/pen/WNxyjgX)

As per the ios integration, there is a pattern object pointed to the HIColor object but in android, that option is not available.
 [here is the reference of ios integration](https://github.com/highcharts/highcharts-ios/issues/333#issuecomment-697453859)

In highchart v8.1.2 pattern object not available.

So How can I integrate same functionality in android?

**Comment by soommy12** [comment]
Hi @ashishkanhasoft ! Indeed, there is no option to init `HIColor` by `HIPatternObject`. We do not have it implemented yet. I will mark this as an enhancement.
