### ISSUE TITLE
Is android highcharts has timeline chart ?

### ISSUE THREAD

**Issue by ismailtosun** [highcharts/highcharts-android#175]

**Comment by soommy12** [comment]
Hi @ismailtosun ! Thanks for the question. We do provide `HITimeline` class, so I suppose the answer is "yes" :)

**Comment by ismailtosun** [comment]
thanks for answering so which chart should I use for like this pic ? 

![time](https://user-images.githubusercontent.com/5730271/98535342-fcffe680-2296-11eb-8cad-53dc8690bc7b.PNG)

**Comment by soommy12** [comment]
You can try `HITimeline` but the choice is yours.

**Comment by pawelfus** [comment]
I would recommend `xrange` series: https://www.highcharts.com/ios/demo/x-range
