### ISSUE TITLE
 No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 403.

### ISSUE THREAD

**Issue by Umesh-Bobade** [highcharts/highcharts-android#177]
works fine with 
data.setCsvURL("https://cdn.rawgit.com/highcharts/highcharts/057b672172ccc6c08fe7dbb27fc17ebca3f5b770/samples/data/analytics.csv"); 
this url but when i use another csv url gives this error.

how to set origin in android using java?

**Comment by soommy12** [comment]
Hi @Umesh-Bobade ! Are you sure that the data is available through your link? You have to turn on the internet connection on your device too.
