### ISSUE TITLE
Highcharts android plot not drawn on initial call , also never loads if reload() is removed

### ISSUE THREAD

**Issue by poojalivin** [highcharts/highcharts-android#180]
This is a portion of my code.

        HIChartView hcWaitTime;
        HIOptions options;
       private void initView(View view) {
        hcWaitTime = view.findViewById(R.id.hcWaitTime);
       }
      private void loadChartData() {
        options = new HIOptions();

        HICredits hiCredits = new HICredits();
        hiCredits.setEnabled(false);
        options.setCredits(hiCredits);
        HIChart hiChart = new HIChart();
        hiChart.setZoomType("x");
        options.setChart(hiChart);

        HIXAxis xaxis = new HIXAxis();
        String[] xList = new String[waitTimeData.size()];
        xaxis.setCategories(new ArrayList<>(Arrays.asList(xList)));
        options.setXAxis(new ArrayList<HIXAxis>() {
            {
                add(xaxis);
            }
        });
        HIYAxis yaxis = new HIYAxis();
        yaxis.setTitle(new HITitle());
        yaxis.getTitle().setText(getViewContext().getResources().getString(R.string.txtNumberPatients));
        options.setYAxis(new ArrayList<>(Collections.singletonList(yaxis)));
        HIPlotOptions plotoptions = new HIPlotOptions();
        options.setPlotOptions(plotoptions);
        HIResponsive responsive = new HIResponsive();
        HIRules rules1 = new HIRules();
        rules1.setCondition(new HICondition());
        rules1.getCondition().setMaxWidth(500);
        responsive.setRules(new ArrayList<>(Collections.singletonList(rules1)));
        options.setResponsive(responsive);
        options.setSeries(seriesArrayList); // seriesArrayList contains data set
        hcWaitTime.setOptions(options);
    //    hcWaitTime.reload();

    }

 Question 1 : if reload() is commented chart is not drawn. What change should I make in my code? I have seen solutions like to add setters. Does that mean to use setOptions() ?
 Question 2 : I have different tabs horizontally and on each tab selection a chart must be shown. If I add reload() the charts are plotted but only on second call.
              Say initially I am on TAB 1 there chart is not shown . If I switch to TAB 2 also nothing is shown. But when I get back to TAB 1 the chart is shown. Same for TAB 2 also.
              On all these tab change I am getting proper response from server and chart reload is also called.
              Chart is draw on initial call when the app is on debug mode.
 The following warnings are shown in logcat.
  Uncaught Error: Highcharts error #13: www.highcharts.com/errors/13/
  Highcharts: Uncaught ReferenceError: Highcharts is not defined
  Also chromium: [ERROR:tile_manager.cc(778)] WARNING: tile memory limits exceeded, some content may not draw while running on physical device.

**Comment by soommy12** [comment]
Hi @poojalivin ! 
re 1 Yes, it means you should use a setter - it will keep your chart working.
re 2 Do not use `reload()` method. You should call `setOptions` with a new options object when the data is changed. That will fill your chart view with a new portion of data. You can also put a flag "redraw" which lets you see the drawing animation if you want.

**Comment by poojalivin** [comment]
Thanks for your response @soommy12 . But when I remove reload() the chart data is never loaded.

**Comment by poojalivin** [comment]
Hi @soommy12 . I found the solution.  I initialized the chart with an empty arraylist and setter in app onCreate() and then updated the data series and used setOptions on service response and it worked fine.
Thanks for your time
