### ISSUE TITLE
How to set date time data into series?

### ISSUE THREAD

**Issue by cupatil** [highcharts/highcharts-android#182]
I am creating highchart using the android wrapper but I am not understanding how to set date time series of data to the graph.

Sample Data: [[1608072120000, 1.6116], [1608072180000, 1.6119], [1608072240000, 1.6119]]

JSFidle: http://jsfiddle.net/chetanpatil1993/62quhdgn/13/

For setting up this I am using the below code in android:

    `val options = HIOptions()
    
    //Setting up x axis
    val xaxis = HIXAxis()
    xaxis.type = "datetime"
    val formats = HIDateTimeLabelFormats()
    val hiDay = HIDay()
    hiDay.main = "%H:%M"
    formats.day = hiDay
    val hiHour = HIHour()
    hiHour.main = "%H:%M"
    formats.hour = hiHour
    xaxis.dateTimeLabelFormats = formats
    xaxis.lineWidth = 1
    options.xAxis = object : ArrayList<HIXAxis?>() {
	    init {
		    add(xaxis)
	    }
    }
    
    //Setting up yAxis
    val yAxis = HIYAxis()
    yAxis.gridLineWidth = 1
    yAxis.lineWidth = 1
    yAxis.opposite = true
    val accessibility = HIAccessibility()
    accessibility.enabled = true
    yAxis.accessibility = accessibility
    
    options.yAxis = object : ArrayList<HIYAxis?>() {
	    init {
		    add(yAxis)
	    }
    }
    
    //Disbal credit
    val credits = HICredits()
    credits.enabled = true
    options.credits = credits
    
    //Prepare and set series data
    val list: ArrayList<HISeries> = ArrayList()
    val series = HISeries()
    
    
    val data: HashMap<Long, Double> = HashMap()
    data.put(1608072120000,1.6116)
    data.put(1608072180000,1.6119)
    data.put(1608072240000,1.6119)
    series.data = ArrayList(listOf(data))
    list.add(series)
    
    options.series = list
    
    chartView.options = options`
    
Please let me know if I miss something

**Comment by soommy12** [comment]
Hello @cupatil ! According to the JS example you posted here your series should look like this:

```
     val data1 = HISeries().apply {
            data = arrayListOf(
                    arrayOf(1608072120000,1.6116),
                    arrayOf(1608072180000,1.6119),
                    arrayOf(1608072240000,1.6119)
            )
            name = "UTC Midnight"
            tooltip = HITooltip().apply {
                pointFormat = "{point.x:%H:%M} local time"
            }
        }
```
