### ISSUE TITLE
Datalabels not showing in Line Chart

### ISSUE THREAD

**Issue by RikySaepuloh** [highcharts/highcharts-android#183]
my code:

        val options = HIOptions()
        val chart = HIChart()
        chart.type = "line"
        options.chart = chart

        val hiTitle = HITitle()
        hiTitle.align="left"
        hiTitle.text = "My Chart"

        val hiSubtitle = HISubtitle()
        hiSubtitle.text="Just Chart"
        hiSubtitle.align="left"

        val plotOptions = HIPlotOptions()
        plotOptions.line = HILine()
        plotOptions.line.dataLabels = ArrayList(listOf(HIDataLabels()))
        plotOptions.line.enableMouseTracking = false
        options.plotOptions = plotOptions

        options.title = hiTitle
        options.subtitle = hiSubtitle

        val firstData = HILine()
        firstData.name="SHU"
        firstData.showInLegend=true
        firstData.data = ArrayList(
                listOf(
                        92, 20, 48, 1, 9, 3

                )
        )

        val secondData = HILine()
        secondData.name="SDM"
        secondData.data=ArrayList(
                listOf(
                        18, 19, 12, 20, 9, 8
                )
        )

        val thirdData = HILine()
        thirdData.name="Beban"
        thirdData.data=ArrayList(
                listOf(
                        8, 22, 10, 18, 10, 4
                )
        )

        val fourthData = HILine()
        fourthData.name="Pendapatan"
        fourthData.data=ArrayList(
                listOf(
                        18, 22, 17, 14, 10, 4
                )
        )
        val emptyTitle=HITitle()
        emptyTitle.text=""

        val hiyAxis = HIYAxis()
        hiyAxis.min = 0
        hiyAxis.title = emptyTitle
        hiyAxis.title.text = ""
        hiyAxis.tickInterval=20
        options.yAxis = arrayListOf(hiyAxis)

        val hixAxis = HIXAxis()
        hixAxis.categories = categoriesX
        options.xAxis = arrayListOf(hixAxis)

        val credits = HICredits().apply {
            enabled = false
        }
        val exporting = HIExporting().apply {
            enabled = false
        }
        options.exporting=exporting
        options.credits=credits

        val allseries= ArrayList<HISeries>()
        allseries.add(firstData)
        allseries.add(secondData)
        allseries.add(thirdData)
        allseries.add(fourthData)
        options.series = allseries
        options.plotOptions=plotOptions
        chartView.options = options

my references : highcharts.com/demo/android/line-labels
i've noticed that i cannot use the 

        plotOptions.line.datalabels.enabled=true

this option was not listed in my program

please let me know if i was missing something

version : com.highsoft.highcharts:highcharts:8.1.2

![graph](https://user-images.githubusercontent.com/48169520/102871139-a2020780-4470-11eb-8557-503d8e5791d1.jpg)

**Comment by soommy12** [comment]
Hi @RikySaepuloh ! The data labels are not showing because you disabled mouse tracking. Just remove this line:
```plotOptions.line.enableMouseTracking = false```

**Comment by RikySaepuloh** [comment]
I'm sorry, I just reached out to you now.
I've remove that line and it worked out fine.
Thank You! @soommy12
