### ISSUE TITLE
how to change theme of charts ? 

### ISSUE THREAD

**Issue by ismailtosun** [highcharts/highcharts-android#184]

**Comment by soommy12** [comment]
Hello @ismailtosun ! You can find `theme` property in the `HIChartView` object. You can check it out in the docs [here](https://api.highcharts.com/android/highcharts/com/highsoft/highcharts/core/HIChartView.html#theme). 
Sample usage:
```chartView.theme = "dark-unica"```

**Comment by ismailtosun** [comment]
thank u

**Comment by chitgoks** [comment]
> Hello @ismailtosun ! You can find `theme` property in the `HIChartView` object. You can check it out in the docs [here](https://api.highcharts.com/android/highcharts/com/highsoft/highcharts/core/HIChartView.html#theme). Sample usage: `chartView.theme = "dark-unica"`

the doc does not mention what kind of themes are available
