### ISSUE TITLE
Is it possible to show percentance on Sunburst Chart ?

### ISSUE THREAD

**Issue by ismailtosun** [highcharts/highcharts-android#185]

**Comment by soommy12** [comment]
Hi @ismailtosun ! What do you mean? Where do you like to see those percentages?

**Comment by ismailtosun** [comment]
hello,thanks for your help
I want to show point percantage instead of point value 
<img width="749" alt="Screen Shot 2020-12-29 at 13 02 57" src="https://user-images.githubusercontent.com/5730271/103275925-4686cb00-49d6-11eb-87bf-802366aa090d.png">

**Comment by soommy12** [comment]
You can use data label formatter. It can be done by native `HIFunction` callback or JS code provided in a string using formatetter. Example formatter:
```
function () {
     return Math.round(100 * this.y / this.total) + '%';
     }
```
