### ISSUE TITLE
x-axis label click event callback

### ISSUE THREAD

**Issue by bitfield66** [highcharts/highcharts-android#186]
Hi

Is there any option to implement and handle callbacks for x-axis label ? - any type of chart

**Comment by bitfield66** [comment]
*Forgot to mention
it's regarding click events for x-axis label

**Comment by soommy12** [comment]
Hi @bitfield66 ! The only events which are available for x-axis are listed [here](https://api.highcharts.com/highcharts/xAxis.events). Clicks on the x-axis label require a plugin that is unfortunately not available on mobile wrappers.
