### ISSUE TITLE
Disable the datalabels for pie chart in Android.

### ISSUE THREAD

**Issue by Finaureus** [highcharts/highcharts-android#187]
I am using "Pie" chart type and I want to disable the datalabels.
I am trying to disable by accessing disable property for datalabel, but the property seems non-accessible which was accessible earlier.

How to disable datalabels in android please suggest.

**Comment by soommy12** [comment]
HI @Finaureus ! For some time now, the datalabels property type has been an ArrayList. See the example:
```
HIDataLabels dataLabels = new HIDataLabels();
dataLabels.setEnabled(false);
ArrayList<HIDataLabels> dataLabelsList = new ArrayList<>();
dataLabelsList.add(dataLabels);
pie.setDataLabels(dataLabelsList);
```
