### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by dimetil** [highcharts/highcharts-android#188]
Any plans for migration to Maven Central because of Bintray sunset?
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by soommy12** [comment]
Hi @dimetil ! Thank you for noticing this. We are already aware of that. We will migrate before Bintray close.

**Comment by michaelcosta** [comment]
@soommy12 Is there an alternative available? Our builds are failing due to bintray doing `Scheduled brown-out session to warn users about May 1st as sunset date for Bintray.` https://status.bintray.com/ 
Is the recommended action to just use the aar as local dependency
