### ISSUE TITLE
Write jsFunction like iOS when click on slice pie chart or legend

### ISSUE THREAD

**Issue by morhodesly1993** [highcharts/highcharts-android#189]
how can write jsFucntion like in iOS SDK within HIConsumer interface I am trying to change the default animation to custom one

**Comment by soommy12** [comment]
Hi @morhodesly1993 ! You can easily attach `HIFunction` object with the proper jsFunction to any property with that type. When it comes to the animation my guess is that you probably don't need `HIConsumer` but pure javascript code passed as String to `HIFunction` constructor like this: `HIFunction("function() { }")`

**Comment by morhodesly1993** [comment]
@soommy12  Thank you for the response. I try to write a pure js function inside `HIFunction`, but I remember that I need to use the click listener function from `HIConsumer` to navigate to a different activity inside the app.  So is there a way to create a custom js function with click listener in `HIConsumer`?

**Comment by soommy12** [comment]
It is not possible to combine js functions passed via string with our lambda implementation. But I don't really get what you want to achieve. Do you want to change the activity after changing the animation? You can also provide your iOS implementation, maybe that will help me understand your goals.

**Comment by morhodesly1993** [comment]
So my team and I try to custom-click on pie slice and legend. we want to update the animation for both pie slice and legend. Right now when you click on the legend the slice disappears but we don't want that to happen. We want when to click on the legend the slice to come out and come back in if you click on the slice or legend. Also when the slice is out or been click on it we want the user to navigate to a different page in the app.
here is a code for iOS version :
`HIFunction(closure: { (context) in
             // 2 click detected now navigate to different page with slice properties 
            }
        }, jsFunction: "function(e) {this.select(); if (this.selected) {chart.tooltip.refresh(this);}; e.preventDefault();}", properties: ["this.y", "this.name", "this.selected"])`

**Comment by soommy12** [comment]
@morhodesly1993 At this moment there is no option for combining jsFunction with lambda callback.

**Comment by morhodesly1993** [comment]
Alright thank you
