### ISSUE TITLE
Bug using funnel chart-Uncaught Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=funnel

### ISSUE THREAD

**Issue by robinbaby12** [highcharts/highcharts-android#192]
1. First I am setting bar chart in the view. 
2. When i select the funnel chart from the spinner i got Uncaught Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=funnel error.
 The link given in the error is not helping.
3. When I set funnel chart as first it working perfectly

**Comment by soommy12** [comment]
Hi @robinbaby12 ! Try to add `funnel` plugin to your chart:

```chartView.plugins = new ArrayList<>(Arrays.asList("funnel"));```
