### ISSUE TITLE
Android Highchart dialog fragment

### ISSUE THREAD

**Issue by fasi1208** [highcharts/highcharts-android#193]
I am unable to load the chart on a dialog fragment. Anything else `com.highsoft.highcharts.core.HIChartView` is  working perfect

`<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:padding="10dp"
    android:scrollbars="none">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/white"
        android:orientation="vertical"
        android:padding="10dp">

        <com.highsoft.highcharts.core.HIChartView
            android:id="@+id/goly_gauge"
            android:layout_width="match_parent"
            android:layout_height = "350dp"

            />

        <com.highsoft.highcharts.core.HIChartView
            android:id="@+id/golm_gauge"
            android:layout_width="match_parent"
            android:layout_height="350dp"
            />

          <Button
            android:id="@+id/ok"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:text="OK" />
    </LinearLayout>

</ScrollView>`

**Fragment**

`final Dialog dialog = new Dialog(getActivity());
        dialog.setContentView(R.layout.product_sales_layout);`
        
**Error**

`Binary XML file line #15 in com.thumbsol.accuratemobileassetsmanagament:layout/product_sales_layout: Error inflating class <unknown>`

**Comment by hetsgandhi** [comment]
I am also facing the same issue. @soommy12

**Comment by hetsgandhi** [comment]
@fasi1208 Did you get the solution?
