### ISSUE TITLE
Datalabels on export not showing all of the points

### ISSUE THREAD

**Issue by RikySaepuloh** [highcharts/highcharts-android#194]
Hi @soommy12 , hope you're doing fine.
currently I'm working on how to show datalabels on export.
I've read some of this articles :
https://api.highcharts.com/android/highcharts/com/highsoft/highcharts/Common/HIChartsClasses/HIExporting.html
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/exporting/chartoptions-data-labels/

here's my code (kotlin)

        val myhashmap= HashMap<String,HIFoundation>()
        myhashmap["series"] = HISeries().apply {
            dataLabels= arrayListOf(HIDataLabels().apply {
                enabled=true
                format="{y:.2f} M"
            })
        }

        options.exporting=HIExporting().apply {
            enabled=true
            chartOptions=myhashmap
        }

I've encountered some problems, the data labels only showing in some of the point.
my expectation is to show data labels from all of the points and series.

![chchch](https://user-images.githubusercontent.com/48169520/118601263-105ab400-b7dc-11eb-8fc4-391fba4ba633.jpeg)

**Comment by soommy12** [comment]
Hi @RikySaepuloh ! That's a nice question! For me your code works perfectly, I can see all datalabels in the exported image. Can you please share all of your chart options? Maybe something else is messed up.

**Comment by RikySaepuloh** [comment]
I found that the problem is, it is caused by the size of the screen so the datalabel doesn't fully appear.
In this case, I've set the datalabels allowOverlap to true

        val plotOptionss = HashMap<String,Any>()
        val exportPlotOptions= HashMap<String,Any>()
        exportPlotOptions["title"]=HITitle().apply {
            text=mytitle
            style=HICSSObject().apply {
                fontSize="12px"
            }
        }
        exportPlotOptions["subtitle"]=HISubtitle().apply {
            text=mysubtitle
            style=HICSSObject().apply {
                fontSize="8px"
            }
        }
        exportPlotOptions["plotOptions"]=plotOptionss
        plotOptionss["series"] = HISeries().apply {
            dataLabels= arrayListOf(HIDataLabels().apply {
                enabled=true
                format="{y:.2f} M"
                allowOverlap=true
                style=HIStyle().apply {
                    fontSize="8px"
                }
            })
        }
        plotOptionss["column"] = HIColumn().apply {
            dataLabels= arrayListOf(HIDataLabels().apply {
                enabled=true
                format="{y:.2f} M"
                allowOverlap=true
                style=HIStyle().apply {
                    fontSize="8px"
                }
            })
        }

        options.exporting=HIExporting().apply {
            enabled=true
            showTable=true
            chartOptions=exportPlotOptions
        }

**Comment by RikySaepuloh** [comment]
and @soommy12  how to export chart as well as the **data table** (below the chart image). 
if you noticed, I've set showTable to true in options.exporting
But it didn't work and do nothing. Something wrong in my code?
