### ISSUE TITLE
How to make HIColor class Serializable?

### ISSUE THREAD

**Issue by PallaviTapkir** [highcharts/highcharts-android#195]
I want make HIColor class Serializable. But, the file is read only.
I am facing an exception ```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object 
Caused by: java.io.NotSerializableException: com.highsoft.highcharts.common.HIColor
```

**Comment by soommy12** [comment]
Hi @PallaviTapkir ! Unfortunatelly, the `HIColor` class cannot be serializable by design. We will take it into consideration in the next release. Thank you for pointing that out!
