### ISSUE TITLE
Enable the datalabels for bar chart in Android

### ISSUE THREAD

**Issue by fasi1208** [highcharts/highcharts-android#196]
I am using "Bar" chart type and I want to enable the datalabels.
The method that is  used  in the example is not working anymore and giving me error 

` HIPlotOptions plotOptions = new HIPlotOptions();
        plotOptions.setBar(new HIBar());
        plotOptions.getBar().setDataLabels(new HIDataLabels());
        plotOptions.getBar().getDataLabels().setEnabled(true);
        options.setPlotOptions(plotOptions);
`
**error** 

> error: incompatible types: HIDataLabels cannot be converted to ArrayList plotOptions.getBar().setDataLabels(new HIDataLabels());

How to enable datalabels in android please suggest.

**Comment by soommy12** [comment]
Hi @fasi1208 ! Some time ago the data labels stuff changed, now we have to pass an array list of the data labels to the setter. It can be done like this:
```
HIDataLabels dataLabels1 = new HIDataLabels();
HIPlotOptions plotOptions = new HIPlotOptions();
plotOptions.setSeries(new HIBar());
ArrayList<HIDataLabels> dataLabelsList = new ArrayList<>();
dataLabelsList.add(dataLabels1);
plotOptions.getSeries().setDataLabels(dataLabelsList);
options.setPlotOptions(plotOptions);
```
