### ISSUE TITLE
Redraw chart after selection is changed

### ISSUE THREAD

**Issue by fasi1208** [highcharts/highcharts-android#197]
I am using a spinner and on selection changes, I am calling a function that displays a chart. I have two spinners one is a category and the second is the product. In category spinner, there are two options one is `Group Wise` second is `Product  Wise`. By default, the product (second spinner) and chart layout are not visible. 

When  I select the  `Group Wise` two bar charts are displayed along with values. When I select `Product Wise` the second spinner is visible and the chart layout visibility is `gone`. From this spinner, I have an option to choose a product. After I choose the product the charts are visible again and I am able to see them but the values are displayed for old i.e. chart is not redrawn. 

I have tried `chart.redraw()` method but it's not working for me 

       `HIBar bar1 = new HIBar();
        bar1.setName("Sale Value");
        Number[] bar1Data = new Number[]{mon1,mon2,mon3};
        bar1.setData(new ArrayList<>(Arrays.asList(bar1Data)));
        bar1.setColorByPoint(true);

        HIDataLabels dataLabels = new HIDataLabels();
        dataLabels.setEnabled(true);
        ArrayList<HIDataLabels> dataLabelsList = new ArrayList<>();
        dataLabelsList.add(dataLabels);
        bar1.setDataLabels(dataLabelsList);

        HILegend hiLegend = new HILegend();
        hiLegend.setEnabled(false);
        options.setLegend(hiLegend);

        options.setSeries(new ArrayList<>(Collections.singletonList(bar1)));

        golmChart.setOptions(options);
        golmChart.redraw();
`

**Comment by soommy12** [comment]
@fasi1208 chart redraw will work only if the chart detects an actual change in its options. Make sure that there is a change in those. You can also try another method `chartView.update(options, true)` which will also update the chart along with animation but again, the options has to be changed somehow in comparison to the already attached old ones.
