### ISSUE TITLE
Highchart on orientation changes (landscape) didn't works as expected

### ISSUE THREAD

**Issue by RikySaepuloh** [highcharts/highcharts-android#198]
At first, my chart is showing no problems and behave properly.
But when I try to change my phone orientation to landscape, the activity is refreshing it's content.
So I was implementing these codes into my activity manifest

            android:configChanges="orientation|screenSize"

The activity is not refreshing until I realize that this brought up a  new problem.

**The chart width is only the show half of the screen.**
I've tried to use :
chart.update method to update chart options width ❌ (failed, width still half of the screen)

            val halfScreen=HIOptions().apply {
                chart=HIChart().apply {
                    width=getScreenWidth(getActivity())/2.5 //just an attempt to change the width to a different length
                } 
            }

            binding.chartView.update(halfScreen,true)

get screen width when orientation changes to landscape and set it to the chartview width ❌ (failed, width still half of the screen)

          binding.chartView.layoutParams.width= getScreenWidth(getActivity()) //attempt to change width to the maximum size of the screen

Portrait :
![nuh](https://user-images.githubusercontent.com/48169520/120123540-99f58300-c1d9-11eb-9490-c65e7ae7ffdd.jpeg)

Landscape :
![gugu](https://user-images.githubusercontent.com/48169520/120123552-a7127200-c1d9-11eb-8513-cd4089d4c10d.jpeg)

in the end, what are causing this problems?
is it the manifest code ?
the webview of chartView that is buggy?
is the chart.update not update at all?
do I have to redraw the chartView ?
or is it something wrong with my life ? (obviously)

**NOTE**

xml codes :

            <com.google.android.material.card.MaterialCardView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_margin="10dp"
                app:cardCornerRadius="10dp"
                app:cardElevation="0dp"
                app:strokeColor="@color/black"
                app:strokeWidth="0.5dp">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="vertical"
                    android:padding="10dp">

                    <RelativeLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content">

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_centerVertical="true"
                            android:text="Comparement\n 2016-2021 "
                            android:textColor="@color/mainText"
                            android:textSize="12sp" />

                        <com.google.android.material.tabs.TabLayout
                            android:id="@+id/tablayout"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_alignParentEnd="true"
                            app:tabIndicatorFullWidth="false"
                            app:tabMinWidth="0dp"
                            app:tabMode="scrollable"
                            app:tabTextAppearance="@style/MineCustomTabText">

                            <com.google.android.material.tabs.TabItem
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:text="Yoy" />

                            <com.google.android.material.tabs.TabItem
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:text="Current" />
                        </com.google.android.material.tabs.TabLayout>

                    </RelativeLayout>

                    <RelativeLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content">

                        <com.highsoft.highcharts.core.HIChartView
                            android:id="@+id/chartView"
                            android:layout_width="match_parent"
                            android:layout_height="250dp"
                            android:visibility="gone" />

                    </RelativeLayout>
                </LinearLayout>
            </com.google.android.material.card.MaterialCardView>

custom function:

    fun getScreenWidth(activity: Activity): Int {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            val windowMetrics = activity.windowManager.currentWindowMetrics
            val insets = windowMetrics.windowInsets
                .getInsetsIgnoringVisibility(WindowInsets.Type.systemBars())
            windowMetrics.bounds.width() - insets.left - insets.right
        } else {
            val displayMetrics = DisplayMetrics()
            activity.windowManager.defaultDisplay.getMetrics(displayMetrics)
            displayMetrics.widthPixels
        }
    }

**Comment by RikySaepuloh** [comment]
oh I forgot to mention, I use the @belovictor approachment method to populate the chart data (asynchronously).

Just in case somebody struggles the same problem I did. The solution with doing setWillNotDraw(true) immediately after findViewById and then doing setWillNotDraw(false) after getting data asynchronously and setting chart options in Retrofit callback worked for me!

_Originally posted by @belovictor in https://github.com/highcharts/highcharts-android/issues/35#issuecomment-466731595_

just in case this method brought up my current problem.
because your solution in that issues is to provide the chart with empty options, not to set setWillNotDraw to false and changed it later.

**Comment by soommy12** [comment]
Hi @RikySaepuloh ! Thank you for the question and detailed description. The `WebView` sometimes behaves strangely. Setting the chart width on its options won't work because it sets the width of the chart in the webview container. What you want is changing the width of that container which is the chart view itself. So, yes, you need invalidate the view and then use `redraw()` method on `chartView` to let the chart fill the new calculated width (but keep in mind that redraw will work only if chart detects option change, so please make a small change in those). Let me know if that worked out. If not, I will make a further investigation.

**Comment by RikySaepuloh** [comment]
@soommy12 I've tried to use these codes on configuration changes:

            val smallUpdate=HIOptions().apply{
                title=HITitle().apply {
                    text="Try Chart Landscape"
                }
            }
            binding.chartView.layoutParams.width= getScreenWidth(getActivity())
            binding.chartView.update(smallUpdate,true)
            binding.chartView.invalidate()
            binding.chartView.redraw()

but nothing happened, it still half of the screen.

Can you provide codes example for me? I'm afraid if I use the wrong codes.

**Comment by soommy12** [comment]
Your code should work. Try to move the `chartView` outside the relative layout container.
