### ISSUE TITLE
How to remove the "Export" menu from the chart

### ISSUE THREAD

**Issue by DanGTZ** [highcharts/highcharts-android#2]
I can see that, by default, the export top right menu icon is displayed.
I have constructed the exact same options object that I use on the web version, but I'm still having the export menu icon displayed on Android, whereas it is not displayed on the web version.
How to remove it?
I tried options.exporting = null; and options.navigation = null; but none of them changed the result, as, by default, both fields are already null.
Thanks.

**Comment by soommy12** [comment]
Hi @DanGTZ  ! To disable export icon do the following code:
```
chartView.options = new HIOptions();
chartView.options.exporting = new HIExporting();
chartView.options.exporting.enabled = false;
```
If you want to manage fields which are in ```HIOptions``` object you need to assign that object first. Only then you can refer to more nested fields.

**Comment by DanGTZ** [comment]
Thanks, tired it and it works!
Sorry, it's a bit confusing to have to instantiate a HIExporting object in order to deactivate it. I was thinking that if there is no HIExporting object (null) then the chart would not display exporting-related features.

**Comment by soommy12** [comment]
Your're welcome! Note that the library has some fields set by default. To change them from Android perspective you need to instantiate the Java object which is responsible for the specific option - in this case: exporting.

**Comment by dewendra-grmtech** [comment]
In my case its not working give me some solution.
        HIOptions options = new HIOptions();
        HIChart chart = new HIChart();
        chart.setType("column");
        options.setChart(chart);
        HITitle title = new HITitle();
        title.setText("Demo chart");
        options.setTitle(title);
        HISpline spline = new HISpline();
        spline.setData(new ArrayList<>(Arrays.asList(0.3,5.3,8.0,9.1,3.2,5.4,4.0,4.2,2.1,10.0)));
        options.setSeries(new ArrayList<HISeries>(Collections.singletonList(spline)));
        chartView.setOptions(options);

**Comment by fasi1208** [comment]
> Hi @dangtz ! To disable export icon do the following code:
> 
> ```
> HIChartView chartView = (HIChartView) findViewById(R.id.chartView);
> chartView.options = new HIOptions();
> chartView.options.exporting = new HIExporting();
> chartView.options.exporting.enabled = false;
> ```
> 
> If you want to manage fields which are in `HIOptions` object you need to assign that object first. Only then you can refer to more nested fields.

It doesn't works for me aswell
