### ISSUE TITLE
Bintray 403 Forbidden

### ISSUE THREAD

**Issue by ergunkocak** [highcharts/highcharts-android#200]
Hello,

I started receiving : 

Could not GET 'https://highsoft.bintray.com/Highcharts/com/highsoft/highcharts/highcharts/8.0/highcharts-8.0.pom'. Received status code 403 from server: Forbidden

from my MSAppCenter builds.

How can i solve this?

Best

**Comment by ergunkocak** [comment]
Will there be a mavenCentral support?

**Comment by shanselm-ergon** [comment]
I opened a discussion in their forum, but still not available.

https://www.highcharts.com/forum/viewtopic.php?f=9&t=46035

**Comment by soommy12** [comment]
Hi @ergunkocak ! Yes, it will be mavenCentral support. We are working on this and it will available along with 9.1.1 release.

**Comment by Daniel-sims** [comment]
@soommy12 Is there any updates on this? My CI is now failing as it's getting forbidden trying to access bintray.

https://dl.bintray.com/sysdata/maven/com/highsoft/highcharts/highcharts/8.1.2/highcharts-8.1.2.pom

**Comment by tkosev** [comment]
Is there any solution on this matter ? I am facing the same issue... Kind regards

**Comment by JuanPabloNarvaezPacheco** [comment]
Is there any solution on this matter ? I am facing the same issue... Kind regards
https://highsoft.bintray.com/Highcharts/com/highsoft/highcharts/highcharts/9.0.1/highcharts-9.0.1.pom

**Comment by Daniel-sims** [comment]
The solution I found to this, was to download the AAR manually and add it into my project. Less than ideal, but it seems like the only way until the project is uploaded to a supported repository.

**Comment by lesongvi** [comment]
> The solution I found to this, was to download the AAR manually and add it into my project. Less than ideal, but it seems like the only way until the project is uploaded to a supported repository.

Yes, It's the only way to solve this issue

**Comment by soommy12** [comment]
Due to the Bintray sunset we were forced to migrating to a different service and that will be done in the next month. Until then you can easily download the AAR version of the library and manually add it to the project. I'm really sorry for inconvenience and thank you in advance for your patience.

**Comment by soommy12** [comment]
Hello all! Since version 9.2.2 Highcharts Android is now available through JitPack. To get it please add to your root build.gradle file:
```
repositories {
    maven { url 'https://jitpack.io' }
}
```
and then to you app build.gradle file:
```
dependencies {
    implementation 'com.github.highcharts:highcharts-android:v9.2.2'
}
```
