### ISSUE TITLE
Error inflating class com.highsoft.highcharts.core.HIChartView

### ISSUE THREAD

**Issue by irfanismaya20** [highcharts/highcharts-android#201]
public class HiLineChartView extends LinearLayout {

    private Context context;
    private String message = "NOT SET";

    public HiLineChartView(Context context, AttributeSet attrs, String message) {
        super(context, attrs);
        this.context = context;
        this.message = message;
        init();
    }

    public void init() {
        inflate(this.context, R.layout.hilinechart, this);
    }
}

**Comment by irfanismaya20** [comment]
I'm trying bridging to react native but not working. anyone to help me?

**Comment by Splact** [comment]
When in `createViewInstance` try to pass `context.getBaseContext()` instead of the `ThemedReactContext`.

```java
public HiLineChartView createViewInstance(ThemedReactContext context) {
    final HiLineChartView v = new HiLineChartView(context.getBaseContext());
    ...
```

PS: I'm working on the same stuff, with the above I solved the `inflating class` error, but the view is still empty.

**Comment by soommy12** [comment]
He @irfanismaya20 , thank you for the question! There is no need to bridge to react native by yourself. There is a [deticated library ](https://github.com/highcharts/highcharts-react-native)for that already!
