### ISSUE TITLE
Touch listener for chart view

### ISSUE THREAD

**Issue by bitfield66** [highcharts/highcharts-android#202]
How can we handle touch events for high chart view?

I have a use case when user scrolls over points on the graph I need to disable nested scrolling

**Comment by soommy12** [comment]
Hi @bitfield66 ! Sorry for the late response. The touch event can be handled like we normally do all click listeners. Can you please explain further what are your expectations? I don't think I fully understand your example. Sharing some code would also help with that.

**Comment by bitfield66** [comment]
i see mouse over and mouse out events worked for my use case
