### ISSUE TITLE
Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by rmbhati** [highcharts/highcharts-android#203]
Could not GET 'https://highsoft.bintray.com/Highcharts/com/highsoft/highcharts/highcharts/9.0.1/highcharts-9.0.1.pom'. Received status code 403 from server: Forbidden

Can any help me to solve this error?

**Comment by kmopaleki** [comment]
Is there any update on this?  We are using 7.0.3 and would like to now when/if that will available on maven?

**Comment by soommy12** [comment]
Hi @rmbhati . Yes, we are currently migrating to a different service and it will be available on the maven next month. Currently you can download an AAR and attach it to your project.

**Comment by rmbhati** [comment]
@soommy12  Is this migrating on new  code?

**Comment by soommy12** [comment]
Hi @rmbhati ! The library is now available to download through Jitpack now. Please follow the readme instructions to attach it to your project.
