### ISSUE TITLE
status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by SanDyLibs** [highcharts/highcharts-android#204]
Could not GET 'https://highsoft.bintray.com/Highcharts/com/highsoft/highcharts/highcharts/9.0.1/highcharts-9.0.1.aar'. Received status code 403 from server: Forbidden.

**Comment by soommy12** [comment]
Hi @SanDyLibs , thanks for the question . We are currently migrating to a different service and it will be available on the maven next month. Currently you can download an AAR and attach it to your project.
