### ISSUE TITLE
Could not HEAD 'https://highsoft.bintray.com/Highcharts/com/highsoft/highcharts/highcharts/6.1r/highcharts-6.1r.pom'. Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by georrge1994** [highcharts/highcharts-android#205]
Hi, after Android studio updates I have updated gradle to v 7.0.0, So after that I can not get access to lib in maven.

**Comment by soommy12** [comment]
Hi @georrge1994 ! This is happening becouse the current hosting service is down. We are in the process of the migration to other service. You can follow for any updates [here](https://github.com/highcharts/highcharts-android/issues/200).
