### ISSUE TITLE
setMouseOver callbacks

### ISSUE THREAD

**Issue by bitfield66** [highcharts/highcharts-android#206]
Hi,

I am using setMouseOver() function to track points on the graph. Below is the code snippet

HIEvents hiEvents = new HIEvents();
hiEvents.setMouseOver(new HIFunction(
  f->{
     Object xAxisValue = f.getProperty("x");
     Object yAxisValue = f.getProperty("y");
    graphListener.onMouseOver(xAxisValue,yAxisValue);
},new String[]{"x","y"}));

In debug build, I can receive callbacks on the mouse over, but on release build, I am facing the below issue:

Uncaught TypeError: Native.androidHandler is not a function

**Comment by soommy12** [comment]
Hi @bitfield66 ! Do you have `minifyEnabled` set to `true` in your project for release build? If yes, please disable it. In case you need this enabled we will have to make a change in the library in future release.

**Comment by bitfield66** [comment]
Hi, @soommy12 we cannot disable minifyEnabled on release builds. Anyway, I found a solution we can add the below rule to proguard to make it work (but it's not recommended).

-keepclassmembers class * {
  @android.webkit.JavascriptInterface <methods>;
}

Thanks for your update

**Comment by soommy12** [comment]
Yes, that will also work. Totally forgot about that. Good you found it yourself.
