### ISSUE TITLE
Image loading issue

### ISSUE THREAD

**Issue by AlexandruHulpe94** [highcharts/highcharts-android#207]
Hello,
after using the aar while waiting for 9.1.2 release image loading doesn't work anymore.
Here is the code:
` ```
HIDataLabels dataLabels = new HIDataLabels();
        dataLabels.setEnabled(true);
        dataLabels.setDistance(13);
        dataLabels.setConnectorShape("straight");
        dataLabels.setConnectorWidth(0);
        dataLabels.setConnectorPadding(0);
        dataLabels.setPadding(0);
        dataLabels.setFormat(
                "<div style=\"width: 25px; height: 25px; overflow: hidden; \">  <object id=\"svg1\" data=\"{point.icon}\" " +
                        "type=\"image/svg+xml\" style=\"width: 25px; height: 25px; \"><img src=\"{point.backupIcon}\" style=\"width: 25px;" +
                        "\"/></object></div>");
        dataLabels.setFormatter(new HIFunction(
                "function () { return this.y >= 5 ? '<img src=\"' + this.point.icon + '\" style=\"width:25px; height:25px;\"/>' : null; }"));
        dataLabels.setUseHTML(true);
        ArrayList<HIDataLabels> dataLabelsList = new ArrayList<>();
        dataLabelsList.add(dataLabels);
        plotOptions.getPie()
                .setDataLabels(dataLabelsList);

        String[] centerList = new String[]{"50%", "50%"};
        plotOptions.getPie()
                .setCenter(new ArrayList<>(Arrays.asList(centerList)));
        options.setPlotOptions(plotOptions);`
```

**Comment by soommy12** [comment]
Hi @AlexandruHulpe94 ! Thank you for the question. I will check it out.

**Comment by AlexandruHulpe94** [comment]
@soommy12 Thank you. Any news ?

**Comment by soommy12** [comment]
@AlexandruHulpe94 The code you provided is working in the current release.
