### ISSUE TITLE
Treemap read vector drawable xml to show in data labels

### ISSUE THREAD

**Issue by niteshnarayan** [highcharts/highcharts-android#209]
Hi,

Is there an example which demonstrates how to read a local android image asset (e.g. a vector drawable xml file) and prepare custom data labels for treemap graph?

TYI

p.s. obviously this is not a bug, so kindly update the status as appropriate, thanks!

**Comment by soommy12** [comment]
Hi @niteshnarayan ! Thanks for your question. There is no a dedicated example but we will work out something.

**Comment by MikolajMichalczak** [comment]
Hi, here is one of the possibilities using the `file:///android_res/` path: https://github.com/highcharts/highcharts-android/issues/152#issue-662600352. Another option is to convert a drawable to a bitmap and then to a base64 string, and include it in an `<img>` tag as follows: `<img src="data:image/png;base64,iVBORw0KG..." />`.
