### ISSUE TITLE
HIPoint missing x / y coordinates

### ISSUE THREAD

**Issue by shanselm-ergon** [highcharts/highcharts-android#212]
The HIPoint class is missing the x / y coordinates in the version v9.2.2 of the Android library. In the iOS API documentation (https://api.highcharts.com/ios/highcharts/) theses values are still available. There is currently no Android documentation for v9.2.2, but in 9.0.1 these values were available and could be set. 

Why were the x and y coordinates removed?

In our chart, we use an ArrayList of HIPoints as data for a HISeries and it worked all well till v9.2.2.

Thanks

**Comment by shanselm-ergon** [comment]
As far as I see here https://api.highcharts.com/class-reference/Highcharts.Point the point still has an x and y coordinate. But not sure if this is the current API or a general documentation. To me, it looks like it is just missing in Android, but I did not a lot of research here. 

Thanks for checking back with the JS developers.

**Comment by soommy12** [comment]
Yes but I was talking about this e.g. https://api.highcharts.com/highcharts/series.pie.point which is very important because this is why it is also missing in Android. Will back with proper information.

**Comment by soommy12** [comment]
@shanselm-ergon I'm back with new info. This is a bug which has its root a little bit deeper than we expected. We already put that into works, we will try publish a hot fix in the coming days if that will be possible. Otherwise it will happen along with new version library release.

**Comment by shanselm-ergon** [comment]
Happy New Year

Are there any news about this issue? What is the timeline for it?

Thanks

**Comment by soommy12** [comment]
Hi @shanselm-ergon ! Happy New Year! New version should be ready for next week.

**Comment by soommy12** [comment]
Hi @shanselm-ergon ! I am happy to say that this bug is fixed in the latest release :)
