### ISSUE TITLE
HISeries shadow is just a boolean in Android

### ISSUE THREAD

**Issue by frangulyan** [highcharts/highcharts-android#216]
The shadow property of HILine class is HIShadowOptionsObject in iOS, but it is just a boolean in Android, although HIShadowOptionsObject class exists in Android. How should I set shadow properties on Android?

**Comment by soommy12** [comment]
Hello @frangulyan ! This is a known bug, some classes are missing in current release we are working to solve it and it will be fixed in the next release which will happen hopefully this week.

**Comment by soommy12** [comment]
Hi @frangulyan ! I am happy to say that this bug is fixed in the latest release :)
