### ISSUE TITLE
Does this library has built-in support to plot graph for days, weeks, months and years break down of input data

### ISSUE THREAD

**Issue by pradeep-orbi** [highcharts/highcharts-android#232]
Does this library has built-in support to plot graph for days, weeks, months and years break down of input data ?
Is it possible to customise this library and build charts that look something like shown in below screenshots ?

<img src="https://user-images.githubusercontent.com/78588549/173177197-85029e2e-c7a4-4ac4-a550-787c387aacd1.png" width="300" height="400"/> <img src="https://user-images.githubusercontent.com/78588549/173177203-8b91c4c1-127a-4316-85e5-779426dd2b9b.png" width="300" height="400"/> <img src="https://user-images.githubusercontent.com/78588549/173177204-09d38ddd-44af-4cd2-856f-90d0aa7a110c.png" width="300" height="400"/> <img src="https://user-images.githubusercontent.com/78588549/173177206-62d83e72-5574-404b-84a7-00395edb21a1.png" width="300" height="400"/>

https://stackoverflow.com/questions/72426937/android-charting-library-with-inbuilt-support-to-plot-graph-for-days-weeks-mon

**Comment by pradeep-orbi** [comment]
@soommy12 I'm not able to run the demo app from Android studio. Can you please help me to solve this error ?
Tried restarting and invalidating cache and all that, but still no luck.

<img width="1440" alt="Screenshot 2022-06-14 at 7 13 18 PM" src="https://user-images.githubusercontent.com/78588549/173592644-64ab6303-ec78-4281-88ab-6137b246355a.png">

**Comment by pradeep-orbi** [comment]
@soommy12 Please update the code in demo app. Looks like it is very old. I'm not able to run it.

**Comment by soommy12** [comment]
@pradeep-orbi thanks for the info. We are currently investigating the problem with demo app.

**Comment by MikolajMichalczak** [comment]
The HighFit demo app has been updated and should now work properly. Feel free to reopen the issue if you have any further questions.
