### ISSUE TITLE
Using highcharts-android in jetpack compose

### ISSUE THREAD

**Issue by VahidGarousi** [highcharts/highcharts-android#233]
Hello, I hope you are well
I have trouble with this library in compose
can you help me?

Please download and run the attached project
The result you will see is that the chart is not displayed

[My Application.zip](https://github.com/highcharts/highcharts-android/files/8934812/My.Application.zip)

**Comment by VahidGarousi** [comment]
@soommy12 can you help me?

**Comment by soommy12** [comment]
@VahidGarousi this library wasn't developed with Jetpack Compose integration in mind. We will definitely look into it but nothing to announce yet.

**Comment by VahidGarousi** [comment]
@soommy12 
I had checked the approach you mentioned but to be more sure, I rechecked and attached the result.

The chart was not displayed correctly


[My Application.zip](https://github.com/highcharts/highcharts-android/files/9077548/My.Application.zip)

**Comment by haemi** [comment]
did you find a solution for this? My chart is drawn correctly the first time I show it, but when used in a HorizontalPager it doesn't work as expected

**Comment by aswinachuthanpalat** [comment]
@soommy12 Hi Soommy any update on the possibility of getting compose version of this?

**Comment by soommy12** [comment]
We are aware of the problem but there are no active works towards solving integration with compose, I'm really sorry about that.

**Comment by aswinachuthanpalat** [comment]
> We are aware of the problem but there are no active works towards solving integration with compose, I'm really sorry about that.

Thank you so much for your quick response. I have a general question also. I have the license purchased and I am confused where I should put the license key. Do you have any documentation in Android?

**Comment by wangqi1221** [comment]
@VahidGarousi Hi, Has your problem been solved? I now also want to use highcharts in my jetpack compose project.But I can’t display the charts either.

**Comment by wangqi1221** [comment]
@haemi Hi, Can you use and display highcharts in a jetpack compose project? Can you tell me how you did it? Thanks.

**Comment by VahidGarousi** [comment]
> @VahidGarousi Hi, Has your problem been solved? I now also want to use highcharts in my jetpack compose project.But I can’t display the charts either.

Hello, I did not use this library and did not review it

**Comment by caycekoehler** [comment]
@soommy12 wanted to touch base on this. Are there any efforts that can be worked on or reviewed for this topic?

**Comment by MikolajMichalczak** [comment]
Hi all!
Sorry for the late response. Here is a way to use Highcharts with Jetpack Compose.
Firstly, create an XML layout with HIChartView:
```xml
<?xml version="1.0" encoding="utf-8"?>

<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.highsoft.highcharts.core.HIChartView
        android:id="@+id/chartView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</FrameLayout>
```
Secondly, inflate the layout in the factory block and get a reference to HIChartView in the update block:
```kotlin
@Composable
fun HighChartsView() {
    AndroidView(
        modifier = Modifier.fillMaxSize(),
        factory = {
            View.inflate(it, R.layout.chart, null)
        },
        update = {
            val chartView = it.findViewById<HIChartView>(R.id.chartView)
            with(chartView) {
                val chart = HIChart().apply { type = "column" }
                val options = HIOptions().apply {
                    this.chart = chart

                    val title = HITitle()
                    title.text = "Demo chart"
                    this.title = title

                    val series = HIColumn()
                    series.data = ArrayList(
                        listOf(
                            49.9,
                            71.5,
                            106.4,
                            129.2,
                            144,
                            176,
                            135.6,
                            148.5,
                            216.4,
                            194.1,
                            95.6,
                            54.4
                        )
                    )
                    this.series = ArrayList(Collections.singletonList(series))
                }
                this.options = options
            }
        }
    )
}
```

**Comment by srenrd** [comment]
Hi this example only works for static data.
If the Composable is depending on a dynamic state like `data: ArrayList<Double> = ArrayList(emptyList<Double>())` which later gets updated to `data = ArrayList(listOf(0.159, 0.159, 0.156))` the chart is still empty.

Is there some kind of function that should be called when series changes? Like notifyDataSetChanged().

**Comment by caycekoehler** [comment]
> Yea sadly this doesn't seem to resolve any issues. It almost seems like the update function is never called in any capacity.

Ignore this.... My build excluded a dependency that wasn't throwing logcat errors so the Update was crashing without giving information as to why. This actually works.

**Comment by MikolajMichalczak** [comment]
@srenrd, please try this implementation (update the chart options in the update method):
```kotlin
@Composable
fun HighChartsView() {
    var data: List<Double> by rememberSaveable { mutableStateOf(emptyList()) }

    LaunchedEffect(true) {
        delay(5000)
        data = listOf(
            49.9,
            71.5,
            106.4,
            129.2,
            144.0,
            176.0,
            135.6,
            148.5,
            216.4,
            194.1,
            95.6,
            54.4
        )
    }
    AndroidView(
        modifier = Modifier.fillMaxSize(),
        factory = {
            val view = View.inflate(it, R.layout.chart, null)
            val chartView = view.findViewById<HIChartView>(R.id.chartView)
            with(chartView) {
                val chart = HIChart().apply { type = "column" }
                val options = HIOptions().apply {
                    this.chart = chart

                    val title = HITitle()
                    title.text = "Demo chart"
                }
                this.options = options
            }
            view
        },
        update = {
            val chartView = it.findViewById<HIChartView>(R.id.chartView)
            val series = HIColumn()
            series.data = ArrayList(data)
            val options = chartView.options.apply {
                this.series = ArrayList(Collections.singletonList(series))
            }
            chartView.update(options)
        }
    )
}
```

**Comment by srenrd** [comment]
Thanks `chartView.update()` was the method i was looking for.

**Comment by VahidGarousi** [comment]
> @VahidGarousi Hi, Has your problem been solved? I now also want to use highcharts in my jetpack compose project.But I can’t display the charts either.

It seems to work properly
