### ISSUE TITLE
Make example works on Chipmunk Android Version (Latest)

### ISSUE THREAD

**Issue by avigpietro** [highcharts/highcharts-android#235]
Hello guys, I had some problems to make the example on this repo runs on latest version of Android Studio, I created fixes, but I am currently not authorized to make Pull Requests, if you have interest please give me permission I send the PR

**Comment by soommy12** [comment]
Hi @avigpietro ! Thanks for your input but we have been are already making improvements for the demo app with new versions of the android in mind.
