### ISSUE TITLE
Plot line is not showing 

### ISSUE THREAD

**Issue by TanyaYu** [highcharts/highcharts-android#238]
Hello,
I am trying to add a plot line to the yAxis. The chart draws the series but not the plot line. Am I missing something? I can't figure out why it isn't showing.

```kotlin
val chartView: HIChartView = findViewById(R.id.chart)

val options = HIOptions()

val chart = HIChart()
chart.type = "column"
options.chart = chart

val yAxis = HIYAxis()

val plotLine = HIPlotLines()
plotLine.value = 50.0
plotLine.width = 2
plotLine.color = HIColor.initWithName("red")
yAxis.plotLines = arrayListOf(plotLine)

options.yAxis = arrayListOf(yAxis)

val series = HIColumn()
series.data = arrayListOf(49.9, 71.5, 106.4, 129.2, 144, 176, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4)
options.series = arrayListOf(series)

chartView.options = options
```

**Comment by soommy12** [comment]
Hi @TanyaYu ! Thank you for the question, there is some problem with plot lines colors serialization in the current library version. As a workaround please do not use `HIColor` class. You can set the color directly by string like this: ```plotLine.color = "red"```

**Comment by TanyaYu** [comment]
@soommy12 thanks! It worked.
