### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by TanyaYu** [highcharts/highcharts-android#239]
I have an empty android project and it runs just fine. But when I add HighChart integration to it the build fails. All I did was adding a single line `implementation 'com.github.highcharts:highcharts-android:10.1.0'` to app dependencies. If this line is commend out the project is able to build again. Interestingly, a clean build is always successful, but not an incremental build. 

Every time I get this error
```
Execution failed for task ':app:packageDebug'.
Changes are not tracked, unable determine incremental changes.
```
I run gradle build task with --info option and discovered these exceptions
`java.io.FileNotFoundException: /Users/tanya/AndroidStudioProjects/chart/app/build/intermediates/compressed_assets/debug/out/assets/js/lib/export-csv.js.jar (Operation not permitted)`
`java.io.UncheckedIOException: Failed to create MD5 hash for file '/Users/tanya/AndroidStudioProjects/chart/app/build/intermediates/compressed_assets/debug/out/assets/js/lib/export-csv.js.jar' as it does not exist.`

I don't have this problem with my other projects running in the same environment. It seems that only projects with HighCharts are affected. I will appreciate any help to address this issue. 

My environment: 
```
macOS 12.3.1
Android Studio Chipmunk | 2021.2.1 Patch 1
Gradle 7.3.3
AGP 7.2.1
Gradle JDK 11.0.2
Kotlin 1.6.21
```

**Comment by raf18seb** [comment]
Hi @TanyaYu,

Thank you for writing to us with your issue. Due to the vacation period, getting a reply might take more time than usual (our Android developer is on vacation now, back in the office next week). Sorry for the inconvenience.

**Comment by soommy12** [comment]
Hi @TanyaYu ! Thanks for the question, do you have `minifyEnabled` set to true in your `build.gradle` file? That may be a problem.

**Comment by TanyaYu** [comment]
@soommy12 I have `minifyEnabled` set to false.

**Comment by soommy12** [comment]
@TanyaYu looks really strange to me. I just created a new raw project and attached the dependency and it didn't happen to me. Can you share your chart options? My guess is that you're using some of the library features which require some additional Highcharts dependency that is not attached to our wrapper.

**Comment by TanyaYu** [comment]
@soommy12 thanks for checking. In my case it's enough to just add the Highchart dependency to the project to replicate the issue (even without creating any Highchart options). Here is a [project example](https://github.com/TanyaYu/chart) I'm having an issue with. 

I've done some experiments and here is what I've found.
1. The issue only replicates on macOS. I could't replicate it on Ubuntu 18.04 with the same environment variables. 
2. As soon as I remove the Highchart dependency from the project the issue disappears. 
3. I found a [similar problem](https://developer.android.com/studio/known-issues#incremental-file-watching) on the Android Studio and AGP known issues page. For a workaround, they recommend moving the project’s directory to the user directory, which I did, but it didn't help. 
4. Downgrading to AGP 4.2.0 and Gradle 6.7.1 resolved the issue. 

I hope this is helpful.

**Comment by TanyaYu** [comment]
Correction to my last message: downgrading to Gradle 7.2 resolves this issue. 

Here is a couple more of my findings:
1. Windows 10 is not affected.
2. I get these warnings when building with Gradle 7.3+

`Cannot access output property 'outputDir' of task ':app:compressDebugAssets' (see --info log for details). Accessing unreadable inputs or outputs has been deprecated. This will fail with an error in Gradle 8.0. Declare the task as untracked by using Task.doNotTrackState(). Consult the upgrading guide for further information: https://docs.gradle.org/7.5.1/userguide/upgrading_version_7.html#declare_unreadable_input_output`

`Cannot access input property 'assets' of task ':app:packageDebug' (see --info log for details). Accessing unreadable inputs or outputs has been deprecated. This will fail with an error in Gradle 8.0. Declare the task as untracked by using Task.doNotTrackState(). Consult the upgrading guide for further information: https://docs.gradle.org/7.5.1/userguide/upgrading_version_7.html#declare_unreadable_input_output`

I get them only on MacOS. Removing HighCharts dependency from the project eliminates these warnings.

**Comment by soommy12** [comment]
@TanyaYu Thank you for all information. I will need some time for investigation. I will be back with any news I'll get!

**Comment by MikolajMichalczak** [comment]
In the project example, this issue is relevant for neither the mentioned 10.1.0 version nor the 11.4.0 version. In the future, running `./gradlew clean` can resolve such issues.
