### ISSUE TITLE
Android SDK Highchart

### ISSUE THREAD

**Issue by sagesurfer-kishor** [highcharts/highcharts-android#240]
updateGraph(); // This function is for load graph.

When i am calling this function from outside like oncreate and all it working fine.

But not working when i received fitnesdata from google fit android sdk. Graph is not loading.

Waiting for your quick response.

  Fitness.getHistoryClient(requireContext(), getGoogleSigningAccount())
                    .readData(mDataReadRequest)
                    .addOnCompleteListener(new OnCompleteListener<DataReadResponse>() {
                        @Override
                        public void onComplete(@NonNull Task<DataReadResponse> task) {

                        }
                    })
                    .addOnSuccessListener(new OnSuccessListener<DataReadResponse>() {
                        @Override
                        public void onSuccess(DataReadResponse dataReadResponse) {
                            updateGraph();
                        }
                    });

**Comment by raf18seb** [comment]
Hi @sagesurfer-kishor,

Thank you for writing to us with your issue. Due to the vacation period, getting a reply might take more time than usual (our Android developer is on vacation now, back in the office next week). Sorry for the inconvenience.

**Comment by sagesurfer-kishor** [comment]
Hope you will update soon for this so i can delivery stuff.

**Comment by sagesurfer-kishor** [comment]
i can provide your license ID if you need from me.. i thought that you have large number of team so other android developer can get resolution for this.

**Comment by sagesurfer-kishor** [comment]
Waiting for your feedback

**Comment by sagesurfer-kishor** [comment]
Error : HIOptions not attached. Chart won't render without options.

**Comment by soommy12** [comment]
hi @sagesurfer-kishor ! Thank you for waiting. It looks like you are missing the chart options setter which is required for `HIChartView` to render properly.  In your `updateGraph()` method at the end of all your options, you should have this line:
```
chartView.setOptions(options);
```
you can also provide the contents of this method for us. That will be helpful resolve your issue. Also, regarding the Google Fit API integration - please make sure all the graph update is done on the UI thread. The chart view is a normal android view so the process of drawing cannot be done in the background if you want to see the change in the graph.
