### ISSUE TITLE
Is it possible to update a chart in Highcharts Android with new data points w/o reloading the entire graph?

### ISSUE THREAD

**Issue by teraiyamayurcontact** [highcharts/highcharts-android#244]
[[](url)](https://imgur.com/a/ZydkvE2)

on left & right arrow click i want update graph according to new data but it is not working.

i am looking for solution in native android sdk.

Thanks in advance

**Comment by soommy12** [comment]
Hi @teraiyamayurcontact ! Thanks for the question. It is possible! You can add the following code to your listener:
```
        exampleButton.setOnClickListener(view -> {
            HIColumn newColumn = new HIColumn();
            Number[] newColumnData = new Number[] { 0.22441811642798026, 0.7513558282273284, 0.47233378113842406, 0.448150689615636, 0.3796370223648643 };
            newColumn.setData(new ArrayList<>(Arrays.asList(newColumnData)));
            newColumn.setName("New column");
            options.setSeries(new ArrayList<>(Collections.singletonList(newColumn)));
            chartView.update(options);
        });
```
The example is using column series but you can use whatever you want.

**Comment by teraiyamayurcontact** [comment]
Uncaught ReferenceError: updateOptions is not defined
Uncaught ReferenceError: chart is not defined

i am receiving above log.
