### ISSUE TITLE
Click Events on Xaxis labels

### ISSUE THREAD

**Issue by VishwasNagarkar** [highcharts/highcharts-android#245]
I am not able to apply click Listener on Xaxis labels

**Comment by soommy12** [comment]
Hi @VishwasNagarkar ! Thank you for the question. Unfortunately, this is not available for mobile. This functionality is provided by `custom-events` plugin which is not supported on Highcharts Android.

**Comment by VishwasNagarkar** [comment]
Thanks for the reply @soommy12 , is there any future plan to integrate this on Highcharts Android.
