### ISSUE TITLE
Yaxis title Android SDK

### ISSUE THREAD

**Issue by teraiyamayurcontact** [highcharts/highcharts-android#246]
i have tried below all option. but not working as expected.

1)
HIFunction mn=new HIFunction( f -> "" + f.getProperty("point.y") + " h",
                    new String[]{"x", "y"});
            HILabels mf=new HILabels();
            mf.setFormatter(mn);
            yAxis.setLabels(mf);

2) HIFunction mn=new HIFunction( f -> "" + f.getProperty("this.y") + " h",
                    new String[]{"x", "y"});
            HILabels mf=new HILabels();
            mf.setFormatter(mn);
            yAxis.setLabels(mf);

3)HIFunction mn=new HIFunction( f -> "" + f.getProperty("value") + " h",
                    new String[]{"x", "y"});
            HILabels mf=new HILabels();
            mf.setFormatter(mn);
            yAxis.setLabels(mf);

3)HIFunction mn=new HIFunction( f -> "" + f.getProperty("this. value") + " h",
                    new String[]{"x", "y"});
            HILabels mf=new HILabels();
            mf.setFormatter(mn);
            yAxis.setLabels(mf);

Review below attached screenshot. Thanks in advance

![Untitled](https://user-images.githubusercontent.com/10277602/201604416-c34ceb03-cc87-4082-b0c0-81c7d4a778b8.png)

**Comment by soommy12** [comment]
Hi @teraiyamayurcontact ! Thank you for the question. Can you explain further what you want to achieve? At first glance, I can see that you don't need to use `HIFunction` to set labels for y-axis - those are set automatically.

**Comment by teraiyamayurcontact** [comment]
i need Y-axis format like below screenshot.

![graph_v1](https://user-images.githubusercontent.com/10277602/201667332-8adf6f93-564a-4705-9198-9229090eceed.png)

**Comment by soommy12** [comment]
Hi, sure, you can try this code:
```
HIYAxis yAxis = new HIYAxis();
yAxis.setLabels(new HILabels());
yAxis.getLabels().setFormatter(new HIFunction(
	f -> f.getProperty("value") + "°",
	new String[] {"value"}
));
options.setYAxis(new ArrayList<HIYAxis>(){{add(yAxis);}});
```
