### ISSUE TITLE
Need onclick event in tooltip 

### ISSUE THREAD

**Issue by supriyakhankarnw18** [highcharts/highcharts-android#248]
Hi Team,
I need to add button in tooltip and onclick of that button need to open native popup. 

I referred below URL. We are able to add button in tooltip but how to attach native click event. Please help.

https://support.highcharts.com/support/solutions/articles/44001710646-how-to-add-clickable-button-in-tooltip-for-highcharts-android-wrapper-

**Comment by soommy12** [comment]
Hi @supriyakhankarnw18 ! Unfortunately, you won't be able to define your own native calls inside a pure javascript code. I'm really sorry about that.
