### ISSUE TITLE
X-axis underline android sdk

### ISSUE THREAD

**Issue by teraiyamayurcontact** [highcharts/highcharts-android#249]
i want remove underline in X-axis in android sdk

![8](https://user-images.githubusercontent.com/10277602/202693459-3047d164-f17e-42f4-8b0b-a88d13e14cd5.png)

**Comment by soommy12** [comment]
Looks like you're using drilldown here. You can disable the text decoration by this code:
```
HIDrilldown drilldown = new HIDrilldown();
drilldown.setActiveDataLabelStyle(new HICSSObject());
drilldown.getActiveDataLabelStyle().setTextDecoration("none");

```
