### ISSUE TITLE
After Search 

### ISSUE THREAD

**Issue by ASumIT2016** [highcharts/highcharts-android#25]

**Comment by sebastianbochan** [comment]
Hi @ASumIT2016 
Please provide any details of your case and then reopen the ticket.

**Comment by ASumIT2016** [comment]
i added search functionality  on   recycler view after search when i click on recycler view item i am opening  charts look like this
![screenshot_1538544845](https://user-images.githubusercontent.com/26159831/46529268-95a32b80-c8b3-11e8-93aa-c052c60fa932.png)
