### ISSUE TITLE
Regarding Y-Axis title

### ISSUE THREAD

**Issue by teraiyamayurcontact** [highcharts/highcharts-android#251]
Hello,

Please review attached photo with orange mark. i don't want all letter as capital in native android sdk.

![1_1](https://user-images.githubusercontent.com/10277602/203466516-c32dd1d5-956e-484c-9e14-b251c0780742.png)

**Comment by soommy12** [comment]
Hi @teraiyamayurcontact . For more advanced `HITitle` customization you can always use `HIStyle`. You can also share your current implementation, we can figure out something together.

**Comment by teraiyamayurcontact** [comment]
HIYAxis yAxis = new HIYAxis();
            yAxis.setTitle(new HITitle());

            yAxis.getTitle().setUseHTML(true);
            yAxis.getTitle().setText("<html><body><b>Number of sleep duration</b></body></html>");

**Comment by soommy12** [comment]
If you're using HTML you can use either:
```<body style="text-transform:lowercase;">```
or
```<body style="text-transform:capitalize;">```
