### ISSUE TITLE
Regarding Documentation of Android Wrapper for the HighCharts Android.

### ISSUE THREAD

**Issue by babure** [highcharts/highcharts-android#253]
I started working with highcharts android since a week, i used highcharts website for the sample code, but I noticed that the charts and sample code does not match and the there are errors in the sample java code provided,many methods does not accept the same parameters which given in the sample java code, is there any way you guys can update the code in the website with new code which match the graph shown.
If you can do this, it would be a great help.

**Comment by soommy12** [comment]
hi @babure ! Thank you for your post. Yes, we will update all the demo examples. Do you have some specific ones in mind so we could start with those?

**Comment by babure** [comment]
The organization chart is present in ios and js but not in android, can you please do that.

**Comment by soommy12** [comment]
I will forward the information about the required demos update to the crew but unfortunately, there is no ETA for any of those.

**Comment by babure** [comment]
The organization chart is present in ios and js but not in android, can you please do that.
