### ISSUE TITLE
Can we do data grouping?

### ISSUE THREAD

**Issue by kaanakell** [highcharts/highcharts-android#258]
https://api.highcharts.com/highstock/plotOptions.series.dataGrouping is this feature available in android version?

**Comment by soommy12** [comment]
Hi @kaanakell ! I'm sorry but this field is not available in the android wrapper. It may be a bug, I will investigate

**Comment by kaanakell** [comment]
@soommy12 thank you for the reply one last question can I use this library with kotlin

**Comment by soommy12** [comment]
Yes you can @kaanakell !

**Comment by MikolajMichalczak** [comment]
`plotOptions.series.dataGrouping` is available only in Highstock, which does not have a mobile version.
