### ISSUE TITLE
Unnecessary assets

### ISSUE THREAD

**Issue by phlpl** [highcharts/highcharts-android#259]
Following on from this [previous ticket](https://github.com/highcharts/highcharts-android/issues/72), i've noticed when analysing our APK that there are some assets bundled in the aar that don't seem necessary and take up space, like the Christmas card images from 2020 and 2021.

![Screenshot 2023-03-13 at 13 56 14](https://user-images.githubusercontent.com/9218510/224724563-5f8c2cbf-0e9c-490c-95bb-94cf95c53617.png)

**Comment by soommy12** [comment]
You're right @phlpl ! Since our wrapper library assets are given to us we do not have a direct influence on what resides in the package but I will definitely rise this up.

**Comment by shubham-prakash123** [comment]
@soommy12 Is there any update on removing these assets files. As it is significantly increasing the APK size.

**Comment by soommy12** [comment]
@shubham-prakash123 I'm really sorry but we cannot remove those assets
