### ISSUE TITLE
Percentages Not getting localised Issue

### ISSUE THREAD

**Issue by shekharshelke07** [highcharts/highcharts-android#261]
Hi,

I'm getting an issue with the percentage localization.  

![Percentages Localization Issue - android](https://github.com/highcharts/highcharts-android/assets/70220444/e34975a1-063b-41df-a45c-1d752962c9b4)

As shown in the above image, I'm not getting localized percentages in Android but getting in iOS. I have written the same js function in both iOS & android codes and passed it to the formatter.

`"function() { if ((this.total - Math.floor(this.total)) == 0) { return Intl.NumberFormat('\(currentLanguage)', { style: 'percent', minimumFractionDigits: 0}).format(this.total / 100) } else { return Intl.NumberFormat('\(currentLanguage)', { style: 'percent', minimumFractionDigits: 2}).format(this.total / 100) } }"`

in the currentLanguage I'm passing the locale for the current language. 

Could anyone please help me to resolve this issue?
Thank you!

**Comment by vaidehi-110997** [comment]
I am also facing the same issue while localizing the tags percentage in Android. The number formatter of Intl is not working on Android.

**Comment by KanchanWaghmare** [comment]
I'm also facing the same issue.

**Comment by vijayradke** [comment]
@soommy12 Could you please guide how to fix this?

**Comment by soommy12** [comment]
Hi all, this is a bug in the Android library. It will probably be fixed in the future release.

**Comment by MikolajMichalczak** [comment]
Hi all!
Apologies for the delayed response. I've attempted to use formatting with `Intl.NumberFormat` on a random chart  and ended up with the following testing code and result: 
```kotlin
HIChart().apply {
    setNumberFormatter(
        HIFunction("function() { var number = 0.251;  var option = { style: 'percent', minimumFractionDigits: 2, maximumFractionDigits: 2 }; var formatter = new Intl.NumberFormat('ar-EG', option); return formatter.format(number); } ")
    )
}
```
![image](https://github.com/highcharts/highcharts-android/assets/51120965/6973abb0-7176-479a-b51b-5e2bd3e27601)

If you still encounter any issues, please provide me with a specific code example. Please double-check the correctness of your locales argument and take into consideration that I am using the latest library version.
