### ISSUE TITLE
Line is greyed out when turned off and on again via legend

### ISSUE THREAD

**Issue by haemi** [highcharts/highcharts-android#264]
I have a spline chart with e.g. 4 series; when I tap on one of the series in the legend, it's greyed out there and disappears in the chart - as expected.

When I tap it again it gets the full opacity in the legend and the chart (as expected), but the other lines appear greyed out. Is this expected behavior or a bug? Can I change this somehow?

**Comment by soommy12** [comment]
Yes, this is expected behaviour. WebView focus collides with other Android touch effects and that is why it sometimes causes that kind of issue. We don't have a solution for that yet although we are constantly looking.

**Comment by MikolajMichalczak** [comment]
Hi @haemi,
This behavior results from the Android WebView specification and gaining focus after a click (similar to hover on a website). If you tap anywhere in the chart area, this focus should be lost.
