### ISSUE TITLE
Set different colors for HiZones

### ISSUE THREAD

**Issue by Francesco96it** [highcharts/highcharts-android#265]
I tried to set different fill color, line color and dashType for each zone, but the last set color or dashType is applied to all other Hizones.
the only solution i found is to add a different series for each value, but the series are not correctly assigned to the categories in the xAxys.
I need help for this issue.

**Comment by soommy12** [comment]
Since the answer is [already here](https://www.highcharts.com/forum/viewtopic.php?f=9&p=187397#p187397) I am closing this issue.
