### ISSUE TITLE
loadJSONOptions doesn't show export button

### ISSUE THREAD

**Issue by nectar1** [highcharts/highcharts-android#268]
Hello 

I use **HIChartView** with **loadJSONOptions** method.
Looks like all options are applied correctly except `exporting` 
```
val options = HashMap<String, Any>()
options["exporting"] = mapOf("enabled" to true)
hiChartView.loadJSONOptions(options)
```

Share button doesn't appear with or without the `exporting`.

**Comment by soommy12** [comment]
Hi @nectar1 ! You don't need this method to set up the export button. You can set the exporting purely by Java/Kotlin.
```
val exporting = HIExporting()
exporting.enabled = true
options.exporting = exporting
```

**Comment by nectar1** [comment]
Hi @soommy12 !
Thank you for answer.
I know about it. 
But I need to load all setup using 'loadJSONOptions'.

**Comment by MikolajMichalczak** [comment]
Hello @nectar1,

Thank you for your patience regarding the exporting issue with loadJSONOptions. I've managed to address this concern, and the fix will be available in the upcoming release.

Moving forward, the export button will be visible by default regardless of the chart setup method. If needed, it can be hidden by utilizing `exporting: { enabled: false }`.

Thank you for your understanding, and please stay tuned for the next release to benefit from the fix.

**Comment by MikolajMichalczak** [comment]
Closing because the issue has been addressed in the latest version that has already been released. Feel free to reopen the ticket if you have any further questions.
