### ISSUE TITLE
Type mismatch between documentation and version 11.2.0

### ISSUE THREAD

**Issue by shanselm-ergon** [highcharts/highcharts-android#272]
I just tried to update to the new 11.2.0 version of the library and found an issue but I don't know if the issue is, that the docs are outdated, or if the type is wrong (to me it might be the second one).

https://api.highcharts.com/android/highcharts/com/highsoft/highcharts/common/hichartsclasses/HICSSObject.html
The color was a HiColor object until version 11. In the library it is now a string. If it should be a string, please update the docs AND define the format of the expected color string. If not, please provide a fix of the library.

Thank you

**Comment by shanselm-ergon** [comment]
This issue originated in https://github.com/highcharts/highcharts-android/issues/267

**Comment by MikolajMichalczak** [comment]
Thank you for pointing this out! We appreciate your feedback. We're currently addressing this issue and plan to update the documentation soon. I'll keep you updated on our progress.

**Comment by MikolajMichalczak** [comment]
Appreciate your patience! The documentation has been updated to reflect the correct type for the `color` attribute, now expecting a `String` format. If you encounter any further discrepancies or need additional assistance, please let us know.

**Comment by shanselm-ergon** [comment]
@MikolajMichalczak thank you for updating the documentation. Now, the API is in sync with iOS. Unfortunately, the documentation is not really helpful, respectively misleading. 

```
public void setColor(java.lang.String color)
Color used in the element. The 'contrast' option is a Highcharts custom property that results in black or white, depending on the background of the element.
```

There is no `contrast` option, or I don't understand the second sentence. Furthermore, the documentation does not define, what kind of string can be set as value. From iOS we know, that it can be any in CSS allowed color string ("red", "#ABABAB", "rgba(255, 255, 255, 0)"). It would be nice if the documentation would mention this.

**Comment by MikolajMichalczak** [comment]
@shanselm-ergon the description of this method in the documentation aligns with the documentation for iOS as well as for the web. The default color setting is "contrast", which is a pseudo color that Highcharts picks up and applies the maximum contrast to the underlying point item, for example the bar in a bar chart.
