### ISSUE TITLE
Bug using lollipop chart-Uncaught Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=lollipop

### ISSUE THREAD

**Issue by sw-tt-tusharojha** [highcharts/highcharts-android#273]
We are implementing chart in android but we are getting below error

Uncaught Error: Highcharts error #17: [www.highcharts.com/errors/17/?missingModuleFor=lolipop](https://www.highcharts.com/errors/17/?missingModuleFor=lolipop)

Please provide solution asap

Thanks

**Comment by sw-tt-vahidabanushaikh** [comment]
We are implementing chart in android and we are facing same issue .
Please provide solution asap.

Thanks.

**Comment by MikolajMichalczak** [comment]
Hi, I've just created a funnel chart using version 11.3.0 of the library, following the demo provided at https://www.highcharts.com/demo/android/funnel, and I encountered no errors.

Could you please provide me with some code that you're using to create a chart? 
Additionally, please take into consideration the context of the error and verify the type of chart and series you're creating. From your description, it seems like you're using a funnel chart but also incorporating some lollipop functionality.

**Comment by sw-tt-vahidabanushaikh** [comment]
Hello,
We are trying to achieve this graph in our android application .and the dependency for android throws an error lolipop module is missing in it.

https://www.highcharts.com/docs/chart-and-series-types/lollipop-series

Could you please help us with the solution .
![highchart_error](https://github.com/highcharts/highcharts-android/assets/98090296/501020fe-021a-4ac6-86e0-db1830505ce4)

Thank you.

**Comment by MikolajMichalczak** [comment]
Try adding `chartView.plugins = mutableListOf("lollipop", "dumbbell")` and please let me know about the result.

**Comment by sw-tt-vahidabanushaikh** [comment]
Hello,

It works for us now .
![image](https://github.com/highcharts/highcharts-android/assets/98090296/6c0545f5-9cfe-4cad-a819-fabc65b3839b)

Thank you.
