### ISSUE TITLE
Maximum number of categories that can be viewed and then scroll

### ISSUE THREAD

**Issue by Bocci94** [highcharts/highcharts-android#275]
Hi everyone, I have a graph where on the X axis I have the months and on the Y axis the amounts for each month.

For example, if I have from January to December but I want to show only the last 5 months and by scrolling to the right the previous months will be shown?

**Comment by MikolajMichalczak** [comment]
Hi @Bocci94!
I suggest using `HIScrollablePlotArea`. By setting `minWidth` properly, you can achieve behavior pretty similar to the one described by you. You can also set the initial scrolling position with `scrollPositionX` (ranging from 0 to 1). Here's an implementation example:
```kotlin
val chart = HIChart().apply {
    scrollablePlotArea = HIScrollablePlotArea().apply {
        minWidth = 1000
        scrollPositionX = 1
    }
}
```
If you want more control about range, try combining it with `xAxis` `setExtremes()` method.

**Comment by MikolajMichalczak** [comment]
Please feel free to reopen the ticket if you have any further questions.
