### ISSUE TITLE
Demo example crashing in Android Compose

### ISSUE THREAD

**Issue by srenrd** [highcharts/highcharts-android#276]
Hi, I'm trying out this lib. But just by crating the example i ran into problems.

implementation("com.github.highcharts:highcharts-android:11.4.0")

java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.gson.JsonObject com.google.gson.JsonObject.getAsJsonObject(java.lang.String)' on a null object reference at com.highsoft.highcharts.core.HIChartView.onSizeChanged(SourceFile:211)

AndroidView(
        modifier = modifier,
        factory = { context ->
            HIChartView(context)
        }, update = { highChart ->
            highChart.apply {
                val chart = HIChart().apply {
                    type = "column"
                }
                val title = HITitle().apply {
                    text = "Demo Chart"
                }
                val series = HIColumn().apply {
                    data = ArrayList(
                        mutableListOf(
                            49.9,
                            71.5,
                            106.4,
                            129.2,
                            144,
                            176,
                            135.6,
                            148.5,
                            216.4,
                            194.1,
                            95.6,
                            54.4
                        )
                    )
                }
                val options = HIOptions().apply {
                    setChart(chart)
                    setTitle(title)
                    setSeries(ArrayList(Collections.singletonList(series)))
                }
                update(options)
            }
        }
    )

**Comment by MikolajMichalczak** [comment]
Hi @srenrd!
This library wasn't developed with Jetpack Compose integration in mind. However, you should change `update(options)` to `highChart.options = options` - the chart won't render without the options attached.

**Comment by srenrd** [comment]
Hi, i changed the line, same error.

**Comment by MikolajMichalczak** [comment]
Could you please try using library version 11.3.0 and inform me about the outcome?

**Comment by srenrd** [comment]
11.3.0 does not crash.
Interesting :).

**Comment by MikolajMichalczak** [comment]
As I mentioned, some features are not currently optimized for Compose. While you can still use it, we can't guarantee full stability. For now, sticking with version 11.3.0 is probably your best option. However, I'll attempt to address this specific issue. If successful, it will be included in the next release. Thank you for your understanding.

**Comment by MikolajMichalczak** [comment]
@srenrd did you manage to display a chart after downgrading the library version?

**Comment by srenrd** [comment]
Nope, i get a blank screen when using the above code.

**Comment by MikolajMichalczak** [comment]
@srenrd, please try using this solution: https://github.com/highcharts/highcharts-android/issues/233#issuecomment-2042505233 .

**Comment by srenrd** [comment]
Yes that works. Thanks!
