### ISSUE TITLE
Want to hide tooltip when clicked on outside

### ISSUE THREAD

**Issue by sw-tt-tusharojha** [highcharts/highcharts-android#278]
I am using multiple highchart graph each having series with tooltip I want to  disappear tooltip after touch to another one graph series clicked.

@soommy12 Can you please help

**Comment by MikolajMichalczak** [comment]
Hi @sw-tt-tusharojha!
I'm not entirely clear on the behavior you're aiming for. Could you please share a screenshot or, even better, some code?
You can try adding a single tooltip with the `shared` flag set to `false`.
```kotlin
val tooltip = HITooltip()
tooltip.shared = false
options.setTooltip(tooltip)
```
This will display a separate tooltip for every clicked series.

**Comment by sw-tt-tusharojha** [comment]
![Screenshot_20240405_114226](https://github.com/highcharts/highcharts-android/assets/121864573/a08df1c2-1061-45e8-b464-9b57f5668bbd)

@MikolajMichalczak
As in above Screenshot, I have multiple graphs and multiple tooltip is showing for each graph I want that if one tooltip of specific graph is open then all tooltip of other graph is hide

**Comment by MikolajMichalczak** [comment]
@sw-tt-tusharojha are these charts somehow synchronized? How does it appear from your implementation perspective? It's important for me to understand this to provide the best answer.

**Comment by sw-tt-tusharojha** [comment]
@MikolajMichalczak 
No chart is not synchronized. Different tooltip can be shown at a time for different series based on touch gesture
We are calling api and setting data in graph and same tooltip also on some logic

**Comment by MikolajMichalczak** [comment]
Clicking on another chart will hide the tooltip by default, as you can see in the video below:

https://github.com/highcharts/highcharts-android/assets/51120965/3aea65bf-0733-498b-9218-f50c4b75218a

Considering that these are separate chart views and the Android focus specification, you must handle other cases on your own.
For example, you can add mouseOver events to the charts and when invoked, hide other tooltips using the `tooltip.hide()` method.
See an example for the line chart:
```kotlin
val line = HILine().apply {
    point = HIPoint().apply {
        events = HIEvents().apply {
            mouseOver = HIFunction(
                HIConsumer { _ ->
                    otherChartView.post {
                        otherChartView.options.tooltip.hide()
                    }
                },
                arrayOf("x", "y"),
            )
        }
    }
}
```

**Comment by sw-tt-tusharojha** [comment]
can you provide any brief sample code implementation if possible

**Comment by MikolajMichalczak** [comment]
@sw-tt-tusharojha, here is a sample Fragment of code with two testing charts utilizing the solution I mentioned earlier. It handles only two charts and hides the tooltip not only on click, but also on other events. If you would like to handle more charts, you will need to scale this implementation on your own.

```kotlin
class ChartFragment : Fragment() {
    private var _binding: FragmentChartBinding? = null
    private val binding get() = _binding!!
    private lateinit var chartViews: List<HIChartView>

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentChartBinding.inflate(inflater, container, false)

        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        chartViews = listOf(binding.hc1, binding.hc2)
        chartViews.forEach { setupChart(it) }
    }

    private fun setupChart(chartView: HIChartView) {
        val options = HIOptions()

        val title = HITitle()
        title.setText("Logarithmic axis demo")
        options.setTitle(title)

        val xaxis = HIXAxis()
        xaxis.setTickInterval(1)
        options.setXAxis(ArrayList(listOf(xaxis)))

        val yaxis = HIYAxis()
        yaxis.setType("logarithmic")
        yaxis.setMinorTickInterval(0.1)
        options.setYAxis(ArrayList(listOf(yaxis)))

        val tooltip = HITooltip()
        tooltip.setHeaderFormat("<b>{series.name}</b><br />")
        tooltip.setPointFormat("x = {point.x}, y = {point.y}")
        options.setTooltip(tooltip)

        val otherChart = chartViews.firstOrNull { it != chartView }

        val line = HILine().apply {
            if (otherChart == null) return
            point = HIPoint().apply {
                events = HIEvents().apply {
                    mouseOver = HIFunction(
                        HIConsumer { _ ->
                            otherChart.post {
                                otherChart.options.tooltip.hide()
                            }
                        },
                        arrayOf("x", "y"),
                    )
                }
            }
        }
        line.setPointStart(1)
        line.setData(ArrayList(mutableListOf(1, 2, 4, 8, 16, 32, 64, 128, 256, 512)))

        options.setSeries(ArrayList(listOf(line)))

        chartView.setOptions(options)
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }

    companion object {
        const val TAG = "ChartFragment"
        fun newInstance() = ChartFragment()
    }
}
```

**Comment by sw-tt-tusharojha** [comment]
Thanks For sample code

**Comment by sw-tt-tusharojha** [comment]
yes you can
