### ISSUE TITLE
Want to show WorldMap? Can I do it in Android. I can't use WebView because I would have to make the world dynamic. 

### ISSUE THREAD

**Issue by iamraajkanchan** [highcharts/highcharts-android#279]

**Comment by MikolajMichalczak** [comment]
Hi @iamraajkanchan!
If you're aiming to create Highcharts Maps specifically for native Android, then unfortunately, the official Android integration doesn't currently support them. If you're uncertain about integration compatibility with Highcharts products, be sure to check the Feature Support Table available here: https://www.highcharts.com/integrations/.

**Comment by iamraajkanchan** [comment]
> Hi @iamraajkanchan! If you're aiming to create Highcharts Maps specifically for native Android, then unfortunately, the official Android integration doesn't currently support them. If you're uncertain about integration compatibility with Highcharts products, be sure to check the Feature Support Table available here: https://www.highcharts.com/integrations/.

Thank you @MikolajMichalczak for replying and clearing the doubt regarding the integration. I will close this issue and I really hope if Android Developers could get the opportunity to integrate HighChart Maps in future.
