### ISSUE TITLE
Scroll in XAxis 

### ISSUE THREAD

**Issue by adirahman** [highcharts/highcharts-android#28]
can i make like this
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/yaxis/inverted-bar-scrollbar

**Comment by soommy12** [comment]
Hi @adirahman ! The example you've posted is Y Axis scrolling. This is Highstock feature. I posted the workaround for this in  [here](https://github.com/highcharts/highcharts-android/issues/22#issuecomment-426222491).
