### ISSUE TITLE
Increased app size

### ISSUE THREAD

**Issue by RadostinMarinov21** [highcharts/highcharts-android#281]
I noticed a similar [issue](https://github.com/highcharts/highcharts-android/issues/259) before, and it seems to be getting worse. We are seriously considering replacing highcharts If it persists. I managed to fix it by adding the following code to our build.gradle.kts file but I'm unsure if this might accidentally exclude necessary parts of the library. Do you think you could apply a similar fix on your end?

```
android {
    packaging {
        androidResources {
            ignoreAssetsPatterns.add("graphics*")
        }
    }
}
```

**Comment by MikolajMichalczak** [comment]
Hi @RadostinMarinov21!
Thank you for reaching out about this issue. I'll do my best to look into the situation and get back to you with a response as quickly as possible. Your concern about potentially excluding necessary parts of the library is valid, so I'll investigate thoroughly before providing any recommendations.

**Comment by MikolajMichalczak** [comment]
@RadostinMarinov21 After careful consideration, we have decided to release the next version without the mentioned folder. We believe this will help address the issue you're experiencing. If you encounter any further problems or have any feedback after the update, please don't hesitate to let us know.

**Comment by MikolajMichalczak** [comment]
@RadostinMarinov21  Version 11.4.3 has been released and is now available.

**Comment by RadostinMarinov21** [comment]
Thank you for your fast response and for resolving the issue so quickly.
