### ISSUE TITLE
ResetZoom button no longer (11.4.5+) shown on zoom

### ISSUE THREAD

**Issue by jacobmattsson** [highcharts/highcharts-android#289]
I was using 11.4.3 of the Android wrapper and I had zooming enabled in my charts. When a chart was zoomed (by user), the ResetZoom button was automatically shown. 

After having upgraded to 11.4.5, the ResetZoom button is no longer shown on (user/touch-initiated) zoom. Have the functionality changed in 11.4.5, or is this perhaps a bug? 

Notice that I use the exact same chart options (and data) in both cases; the only thing that differs is the Android wrapper version (11.4.3 vs 11.4.5).

Thanks a lot! And sorry for spamming you with issues! I'm very happy with the Android wrapper (apart from these issues)! ;-)

**Comment by MikolajMichalczak** [comment]
HI @jacobmattsson!

This issue seems to be a bug in the core library rather than the mobile wrappers.
The problem has already been reported, and I’ll keep you updated on any progress. 
Thank you for your patience!

**Comment by jacobmattsson** [comment]
Thanks for you quick response, @MikolajMichalczak!

Could please link to that issue in the core library!?

I can confirm that this bug remains in version 11.4.7 of the Android wrapper.

I found a work around for this problem though, thanks to your tip in #287. 😃 

By applying that event listener on both the X and Y axis, the 'reset zoom' button is automatically shown when the user zoom in and it is also (with my addition, see 289) hidden when the button is pressed and when user zooms back out to the default zoom.
