### ISSUE TITLE
Data time scope

### ISSUE THREAD

**Issue by nivCoindash** [highcharts/highcharts-android#29]
Hey, 
Iv data for 3 months. 
and i want the user to be able to choose between 24 hours, 7 days and 1 month view.
how can i do it? 

Thank you! 
Niv

**Comment by soommy12** [comment]
Hi @nivCoindash , the exact solution you talk about is presented in the example app in [here](https://github.com/highcharts/highcharts-android/blob/master/Example/HighFit/app/src/main/java/com/highsoft/highfit/AreaChartFragment.java#L98).

**Comment by soommy12** [comment]
Hi @nivCoindash ! The exact solution you talk about is presented in the example [here](https://github.com/highcharts/highcharts-android/blob/master/Example/HighFit/app/src/main/java/com/highsoft/highfit/AreaChartFragment.java#L105).

**Comment by soommy12** [comment]
Hi @nivCoindash ! The exact solution you talk about is presented in example [here](https://github.com/highcharts/highcharts-android/issues/29).

**Comment by soommy12** [comment]
Hi @nivCoindash ! The exact solution you talk about is presented in example [here](https://github.com/highcharts/highcharts-android/issues/29).

**Comment by nivCoindash** [comment]
Hi @soommy12 

i'm currently using this way - 

`vChart.options.xAxis[0].min = DateUtils.getTimeAgo(minTime)
        vChart.options.xAxis[0].max = DateUtils.getCurrentTimeStamp()
        vChart.reload()`

it is working fine but the problem is that the y axis is not changing so the chart looks like a straight line

**Comment by soommy12** [comment]
The code you provided is not enough to reproduce the problem you point to. I tested it and it works as intended. Can you please provide more details?

**Comment by nivCoindash** [comment]
for example if you set a bank account balance for the past 3 month. 
the current balance is 2000 dollar.
in those 3 month the changes were max 5% and -5% (min change to 1900$ and max of 2100$) 
so instead of showing y axis min of around 1900 dollar and max of 2100 dollar its showing min of 1000$ and max of 5000$ (prices are for the purposes of the example) 

I need the graph to be more zoomed.

**Comment by soommy12** [comment]
In such case you can use `yAxis.setMin()` and `yAxis.setMax()` values to fit your scope.

**Comment by nivCoindash** [comment]
Yes, i saw this option but i order to achieve this i need to loop the data and find what is the lowest point and what is the highest.. 

there is another way to achieve it?

thank you for you help!

**Comment by soommy12** [comment]
Please notice that if you `setSeries` in your listener (`onClick` for example) the chart axes will automatically adapt. You have disabled them so you cannot see the change. Do not `chartView.reload()` in case you want to see the animation of decreasing/increasing series and axes.

**Comment by nivCoindash** [comment]
can you show me an example?
I didnt get it

Thank you

**Comment by soommy12** [comment]
Yes, sure. Here you have to code:

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_issues);

        Button btn = findViewById(R.id.btn);
        btn.setText("Series update");
        HIChartView chartView = findViewById(R.id.hc);
        HIOptions options = new HIOptions();

        HIPlotOptions plotOptions = new HIPlotOptions();
        plotOptions.setArea(new HIArea());
        plotOptions.getArea().setData(randData(10));

        options.setSeries(new ArrayList<>(Collections.singletonList(plotOptions.getArea())));
        options.setPlotOptions(plotOptions);

        chartView.setOptions(options);

        btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                HIArea area = new HIArea();
                area.setData(randData(5));
                options.setSeries(new ArrayList<>(Collections.singletonList(area)));
            }
        });
    }

    private ArrayList randData(int bound){
        ArrayList<Integer> data = new ArrayList<>();
        Random r = new Random();
        for(int i = 0 ; i < 10 ; i ++){
            data.add(r.nextInt(bound));
        }
        return data;
    }
```
And the example in action:

![example-vid-01](https://user-images.githubusercontent.com/23573237/47636187-c5aeb900-db57-11e8-97c8-da4bbecee9fa.gif)

**Comment by nivCoindash** [comment]
oh ok, so there no way to render the graph by setting min and max? 

how i doing that - 
` vChart.options.xAxis[0].min = DateUtils.getTimeAgo(minTime)
        vChart.options.xAxis[0].max = DateUtils.getCurrentTimeStamp()
        vChart.reload()`

**Comment by soommy12** [comment]
Axes min and max are set based on the series. That is why series always fit into the axes. Setting min and max on your own is ok if you want to limit visible series points or show the chart scale by setting it much higher than actual series min/max. If you will add this lines to the example which I posted above it will be clear for you:
```
        HIYAxis hiyaxis = new HIYAxis();
        hiyaxis.setMax(6);
        options.setYAxis(new ArrayList<>(Collections.singletonList(hiyaxis)));
```
Additionally, if you want to set the bounds dynamically you need to set the whole set of axes in an options object. That is because ArrayLists doesn't have a mechanism which let us observe changes on specific elements. We need to change the whole set instead. Using the example above again, it would look like this:

```
        btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                HIArea area = new HIArea();
                area.setData(randData(5));
                options.setSeries(new ArrayList<>(Collections.singletonList(area)));
                HIYAxis hiyaxis = new HIYAxis();
                hiyaxis.setMax(8);
                hiyaxis.setMin(-3);
                options.setYAxis(new ArrayList<>(Collections.singletonList(hiyaxis)));
            }
        });

```

**Comment by soommy12** [comment]
I didn't meet such behaviour. Are you sure you didn't mess up with chart scale? I was testing this with few data sets but it didn't occur.
