### ISSUE TITLE
PieChart java.lang.ClassCastException: java.lang.String cannot be cast to com.highsoft.highcharts.core.HIFoundation

### ISSUE THREAD

**Issue by Child0fTheSun** [highcharts/highcharts-android#292]
Hi, I'm trying to create a pie chart and I keep getting the same error:
java.lang.ClassCastException: java.lang.String cannot be cast to com.highsoft.highcharts.core.HIFoundation

Could you please help me figure out what I'm doing wrong?

Here's the code for the chart:

`val chartView = binding.hpie
        val options = HIOptions()

        val chart = HIChart()
        chart.type = "pie"
        options.chart = chart

        val title = HITitle()
        title.text = "Demo chart"

        options.title = title

        val credits = HICredits()
        credits.text = ""

        val series = HIPie()
        series.type = "pie"
        series.data = arrayListOf(
            data.pieChart.totalResolved,
            data.pieChart.totalNotResolved,
            data.pieChart.totalOverdue
        )
        series.dataLabels = arrayListOf(
            getString(R.string.content_resolved),
            getString(R.string.content_not_resolved),
            getString(R.string.content_overdue)
        )
        series.colors = ArrayList<String>(
            mutableListOf(
                "#99ff98", "#feff98", "#FFAB98"
            )
        )

        options.series = ArrayList(listOf(series))
        chartView.options = options`

**Comment by MikolajMichalczak** [comment]
Hi @Child0fTheSun!

I assume you'd like to display a specific string next to each data point in the series.

I suggest using an approach where you create `HIData()` objects with a name, value, and color for each data point. Then, you can create `HIDataLabels()` with a custom format to display the specified name.

The code would look as follows:
```kotlin
val chartView = binding.hpie
val options = HIOptions()

val chart = HIChart()
chart.type = "pie"
options.chart = chart

val title = HITitle()
title.text = "Demo chart"

options.title = title

val credits = HICredits()
credits.text = ""

val series = HIPie()
series.type = "pie"

val data1 = HIData().apply {
    name = getString(R.string.content_resolved)
    y = data.pieChart.totalResolved
    color = HIColor.initWithHexValue("99ff98")
}
val data2 = HIData().apply {
    name = getString(R.string.content_not_resolved)
    y = data.pieChart.totalNotResolved
    color = HIColor.initWithHexValue("feff98")
}
val data3 = HIData().apply {
    name = getString(R.string.content_overdue)
    y = data.pieChart.totalOverdue
    color = HIColor.initWithHexValue("FFAB98")
}

val dataLabel = HIDataLabels().apply {
    enabled = true
    format = "<b>{point.name}</b>"
}

series.dataLabels = arrayListOf(dataLabel)
series.data = arrayListOf(data1, data2, data3)

options.series = ArrayList(listOf(series))
chartView.options = options
```
Please let me know if this solves your issue.

**Comment by Child0fTheSun** [comment]
Thank you, this worked great
