### ISSUE TITLE
can this library support lower api level?

### ISSUE THREAD

**Issue by JokerHYC** [highcharts/highcharts-android#30]
lots of user still have lower api level phone.
but use your library only support api level 21 and higher...

**Comment by JokerHYC** [comment]
i found HIChartView.reload() requires api 19 which has used webview.evaluateJavascript() new added in api 19.
public boolean shouldOverrideUrlLoading(WebView var1, WebResourceRequest var2) which requires api 21 .
i think that safely use can be api 19 and higher.
lower than api 19 which also has solutions  by making custom js bridge.

**Comment by soommy12** [comment]
Hi @JokerHYC ! Thanks for your question. At this moment I can't remember why API 21 was chosen. I will investigate. If this will be possible, you can be sure this will be introduced in _6.2_.

**Comment by JokerHYC** [comment]
i tried overwrite your api config at api 16 it crushed by missing method evaluateJavascript().
then i turn to api 19 , so far so good.

**Comment by soommy12** [comment]
In the current release min SDK is set to 19 @JokerHYC . Thanks for you suggestion :)
