### ISSUE TITLE
Setting UTC is invalid.

### ISSUE THREAD

**Issue by SmallWinter** [highcharts/highcharts-android#32]
HITime hiTime = new HITime();
hiTime.setUseUTC(false);
hiOptions.setTime(hiTime);

_______________________________________
The HIOptions setting UTC is invalid.

**Comment by soommy12** [comment]
Hi @SmallWinter , did you set your options on the chart view? `chartView.setOptions(hiOptions);` If yes, please provide more code and explain what do you mean by _invalid_.
