### ISSUE TITLE
highchats add plot line in xaxis base line

### ISSUE THREAD

**Issue by ArunVicky001** [highcharts/highcharts-android#34]
Hi, 

Please tell me how to draw the plot Line in xAxis base line, Which means the zeroth position of xAxis. I found the below code in javascript the same I want to achieve in android 

xAxis: {
            categories: [
                'Week 1',
                'Week 2',
                'Week 3',
                'Week 4',
                'Week 5',
                'Week 6',
                'Week 7',
                'Week 8'],
            plotLines: [{
                color: '#FF0000',
                width: 1,
                value: 0,
                dashStyle: "dash"
            }]  

here you can see the plot line was added in the xAxis with values, For reference please check this link http://jsfiddle.net/phpdeveloperrahul/gm74d/

**Comment by soommy12** [comment]
Hello @ArunVicky001 ! To implement plotline you need to create `HIPlotLine` object, set the same values as you posted in Javascript code and set plotline to xAxis object. This is initialized in exactly the same way as the other chart options.

**Comment by ArunVicky001** [comment]
Okay thanks for your reply, I have solved this issue already.
