### ISSUE TITLE
highcharts with Retrofit async data load

### ISSUE THREAD

**Issue by belovictor** [highcharts/highcharts-android#35]
Hi,

I'm trying to use highcharts inside RecyclerView. I need to show a list of spline charts and every chart is initialised inside a separate ViewHolder. I get highcharts view when ViewHolder is created:
`mItemHighcharts = itemView.findViewById(R.id.item_highcharts);`
Then I add data when ViewHolder is binded:
`                HISpline series = new HISpline();
                series.setColor(HIColor.initWithRGB(0x4C, 0xAF, 0x50));
                series.setShowInLegend(false);
                series.setEnableMouseTracking(false);
                series.setData(new ArrayList<>(Arrays.asList(0.3,5.3,8.0,9.1,3.2,5.4,4.0,4.2,2.1,10.0)));
                HIOptions options = mItemHighcharts.getOptions();
                options.setSeries(new ArrayList<HISeries>(Collections.singletonList(series)));
                mItemHighcharts.setOptions(options);
                mItemHighcharts.reload();
`
And everything works fine when I add series with static data. But when I try to load data from API using Retrofit 2 and add it to the chart exactly the same way but in a Retrofit callback, some mysterious things start to happen. Data is not shown in charts and I get this messages in the log:
2018-11-12 12:58:43.125 8731-8731/com.thingenix.tngxio E/libHC: Uncaught ReferenceError: updateOptions is not defined
2018-11-12 12:58:43.127 8731-8731/com.thingenix.tngxio E/libHC: Uncaught ReferenceError: Highcharts is not defined
2018-11-12 12:58:43.132 8731-8731/com.thingenix.tngxio E/libHC: Uncaught ReferenceError: updateOptions is not defined
2018-11-12 12:58:43.133 8731-8731/com.thingenix.tngxio E/libHC: Uncaught ReferenceError: Highcharts is not defined
2018-11-12 12:58:43.138 8731-8731/com.thingenix.tngxio E/libHC: Uncaught ReferenceError: updateOptions is not defined
2018-11-12 12:58:43.140 8731-8731/com.thingenix.tngxio E/libHC: Uncaught ReferenceError: Highcharts is not defined

If I start scrolling down through the charts, the new charts which appear load data just fine and show it, but some of them are still empty and cause the same messages in the log. When I scroll back to the start of the chart list, first charts which happened to be empty are populated with data.

This only happens when data is added in Retrofit 2 callback.
Any ideas on what can cause it?

**Comment by belovictor** [comment]
Thank you for your fast response!
I wasn't clear enough, probably, but the whole code block which I quoted, where I create series, add data and set it to highcharts, is run from the callback. Or do you mean I need to create an empty series before making an API call and set it to highcharts and then create a new series object with data in API callback and set it to highcharts again?

**Comment by soommy12** [comment]
> Or do you mean I need to create an empty series before making an API call and set it to highcharts and then create a new series object with data in API callback and set it to highcharts again?

This is what I meant :)

**Comment by soommy12** [comment]
These messages are understandable as `RecyclerView` tries to draw `HIChartViews` which didn't have a chance to load its scripts and doesn't have its options set yet. You need to specify options as fast as possible. Creating `HIChartView` is totally achievable in `RecyclerView`. There was a question about doing an API call for data https://github.com/highcharts/highcharts-android/issues/5 and question about recycler view https://github.com/highcharts/highcharts-android/issues/11 . Maybe those can help. I can't do much more without your recycler view adapter snippet.

**Comment by belovictor** [comment]
Just in case somebody struggles the same problem I did. The solution with doing setWillNotDraw(true) immediately after findViewById and then doing setWillNotDraw(false) after getting data asynchronously and setting chart options in Retrofit callback worked for me!

**Comment by anarghya-das** [comment]
@belovictor You are a life-saver. I was struggling with this and couldn't find anything until I saw this post and setWillNotDraw worked like a charm. THANK YOU!

**Comment by VitKap** [comment]
The same problem occured to me, when loading data from db (Room). It seems that this problem appears only on Android 10 devices. "SetWillNotDraw" solved the problem for me.

**Comment by tvtruong3964** [comment]
> Just in case somebody struggles the same problem I did. The solution with doing setWillNotDraw(true) immediately after findViewById and then doing setWillNotDraw(false) after getting data asynchronously and setting chart options in Retrofit callback worked for me!

Wow, Thank you so much, I've been searching for this for a month and still no answer, now everything work perfect, Thank you :)
