### ISSUE TITLE
how to get the chart selection index

### ISSUE THREAD

**Issue by MahiSuba** [highcharts/highcharts-android#36]
Hi I have a chart which contain 2 HILine and 2 HIColumn if I click on the chart in any position I want to get the exact index of all chart values. Could you please tell me how to get the values. 

Thanks.

**Comment by soommy12** [comment]
Hello @MahiSuba ! Thanks for the question. To get the series exact index you need to use `HIFunction`. It's described in [readme](https://github.com/highcharts/highcharts-android/blob/master/README.md).

**Comment by MahiSuba** [comment]
Thanks for your response, But I can't pass the x values to another method

**Comment by MahiSuba** [comment]
I want get the x values alone it return x and y axis always

**Comment by soommy12** [comment]
If you want x values only just put `x` in the second `HIFunction` argument. Inside the callback, you can pass the value wherever you want using `f.getProperty("x")`.
