### ISSUE TITLE
How to enable the marker which is presented in the chart 

### ISSUE THREAD

**Issue by ArunVicky001** [highcharts/highcharts-android#37]
Hi,

Am using two HILine in a chart, When i click on the chart I wanted to highlight both HILine's marker at the same index also I have to show plotband in the same index place . My requirement is to highlight the markers which is presented in the chart not to the selected line.  Could you please tell me how to achieve that. 

Thanks.

**Comment by soommy12** [comment]
Hello @ArunVicky001 ! To highlight markers from both of your series use `tooltip.setShared(true)`. When it comes to plot bands you may make use of [this](https://www.highcharts.com/docs/chart-concepts/plot-bands-and-plot-lines) article.
