### ISSUE TITLE
Error:Failed to resolve: com.highsoft.highcharts:6.0.2:

### ISSUE THREAD

**Issue by abhishekhzb** [highcharts/highcharts-android#4]
I am using Android Studio 3.0.1 & when i added 

dependencies {
    compile 'com.highsoft.highcharts:6.0.2'
}

As mentioned in the document i'm getting this error 

```
  Error:Failed to resolve: com.highsoft.highcharts:6.0.2:
  <a href="openFile:D:/Other Projects/HighCharts2/app/build.gradle">Open File</a>
```

I also tried with add .aar file to libs that time 
` HIGChartView chartView = (HIGChartView) findViewById(R.id.hc); `

not able to resolve.....   `HIGChartView` i also downloaded you project by github & the app is runnig without issue but why problem with my project.

**Comment by soommy12** [comment]
Hi @abhishekhzb ! Unfortunatelly _Highcharts Android_ is not avilable from jcenter yet so you need to add library manually. You can do that by following direct instructions from **A)** point from readme.

**Comment by abhishekhzb** [comment]
I added by A) point from readme.  but my project not able to find out the class HIGChartView

**Comment by soommy12** [comment]
Can you provide your build.gradle files?

**Comment by abhishekhzb** [comment]
My build.gradle(Module: App) 

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.kabloom.highchartdemo"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

repositories{
    flatDir{
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    compile (name: 'highcharts-release', ext:'aar')
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}
`

**Comment by soommy12** [comment]
Seems ok. What exact error do you get, can you please show the log?

**Comment by abhishekhzb** [comment]
This is my MainActivity 

```
package com.kabloom.highchartdemo;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
 

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        
        HIGChartView chartView = (HIGChartView) findViewById(R.id.hc); //This line Showing red color with HIGChartView , i also used Ctrl+space can't able to find out the class.
    }
}
```

**Comment by soommy12** [comment]
You forgot about imports:
```
import com.highsoft.highcharts.Core.*;
import com.highsoft.highcharts.Common.HIChartsClasses.*;
```
Please note that the library need **Gson** to work so add it in your dependencies this:
```
compile 'com.google.code.gson:gson:2.8.0'
```

**Comment by abhishekhzb** [comment]
Again getting error after added as you mentioned above.
```
Error:(16, 9) error: cannot find symbol class HIGChartView
Error:(16, 35) error: cannot find symbol class HIGChartView
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by soommy12** [comment]
Ah, it's the typo. The class name is **HIChartView** not **HIGChartView**

**Comment by abhishekhzb** [comment]
Thank you so much by made changes as you mentioned above , app is  running with correct graph.

**Comment by soommy12** [comment]
Hello @abhishekhzb ! The wrapper is now available to download from Bintray. To download it follow the instructions included in the new readme.

**Comment by abhishekhzb** [comment]
Hello @soommy12  I have not checked it.

**Comment by Dushyant-123** [comment]
cannot find symbol class HIGChartView. even try with a .aar file or add a dependency in gradle.

**Comment by abhishekhzb** [comment]
Hi, @Dushyant-123  
The class name is HIChartView not HIGChartView.

**Comment by Dushyant-123** [comment]
But In Hightchart Library when you see code of demo . they are using HIGChartVIew

 HIGChartView chartView = (HIGChartView) findViewById(R.id.hc);

        HIOptions options = new HIOptions();
		
        HIChart chart = new HIChart();
        chart.type = "column";
        options.chart = chart;

        HITitle title = new HITitle();
        title.text = "Monthly Average Rainfall";
        options.title = title;

**Comment by soommy12** [comment]
Hi @Dushyant-123  
Unfortunately, the demos on the site are outdated. The update is coming next week. `HIChartView` class is the proper one, @abhishekhzb  is right

**Comment by Dushyant-123** [comment]
@soommy12  thanks for the information. when I implement high chart with HIChart().  then in this example how to implement the zoom feature

**Comment by Dushyant-123** [comment]
@soommy12  thanks for the information. when I implement hight chart using  HIChart(). then how can I zoom chart in Android and Ios

**Comment by soommy12** [comment]
@Dushyant-123 The GitHub is our bug tracker, so for general support questions please use StackOverflow / Forum or E-mail.

**Comment by karthik-dusk** [comment]
Failed to resolve: com.highsoft.highcharts:highcharts:6.1r

**Comment by SatishGummanu** [comment]
@soommy12  I'm getting below error.

FragmentHorizontalcolChartBinding.java:12: error: cannot find symbol
import com.highsoft.highcharts.Core;

**Comment by usmanmagdynamics** [comment]
Could not determine the dependencies of task ':app:compileDebugKotlin'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find :highcharts-release:.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
