### ISSUE TITLE
HighCharts setEvents 

### ISSUE THREAD

**Issue by saravananraj21** [highcharts/highcharts-android#41]
Hi
I am loading a pie chart with values and set a click event on it.When i click on it another chart of type area loads with some values by calling reload().The next case is that when i click on area chart I have to load another chart with some data which is similar to drilldown. The issue i face here is when I click on area chart I cannot handle the click event.It's showing some error like this

`E/libHC: Uncaught ReferenceError: Android4 is not defined`

I am facing this issue whenever i reload the another chart with some values(chart reloading is fine but can't handle the click event).

Can you please help me regarding the above issue!

Thanks in advance!!

**Comment by soommy12** [comment]
Hello @saravananraj21 ! Thanks for the question. The `reload()` method will be deprecated in the next release because of this problem. Click events are injected dynamically for your chart and after reloading the chart context is lost.  As the reload method is re-generating the chart, I suggest you update required chart options with the help of setters.

**Comment by saravananraj21** [comment]
Hi @soommy12 ! Thanks for the update. I have another query in chart types such as sunburst, pareto and sankey diagram! When I tried to implement these charts it showed the following error

`E/libHC: Uncaught Error: Highcharts error #17: www.highcharts.com/errors/17`

Is this an issue with the library?

**Comment by soommy12** [comment]
This is a core library error, if you put the link in the browser you will get the description. Basically, series which you listed in the post needs plugins attached.

**Comment by saravananraj21** [comment]
Where can I find those plugins and how to configure it?

**Comment by soommy12** [comment]
You can find all the plugins [here](https://www.highcharts.com/products/plugin-registry). In Android library you can add them like this: 
```
hiChartView.plugins = new ArrayList<>();
hiChartView.plugins.addAll("name-of-the-plugin");
```

**Comment by saravananraj21** [comment]
Hi @soommy12 !
Thanks ! It worked!

**Comment by saravananraj21** [comment]
> Hello @saravananraj21 ! Thanks for the question. The `reload()` method will be deprecated in the next release because of this problem. Click events are injected dynamically for your chart and after reloading the chart context is lost. As the reload method is re-generating the chart, I suggest you update required chart options with the help of setters.

Hi @soommy12 . I tried the method you suggested by setting the hiOptions in setters but couldn't achieve the click event.Can you help me with some sample code for that!

**Comment by soommy12** [comment]
You can check the sample code in [readme](https://github.com/highcharts/highcharts-android/blob/master/README.md) (the example with `setEvents()` is in the end). If this won't help, please provide additional info about your requirements or post here some snippet.

**Comment by saravananraj21** [comment]
I have separate class for each chart type.Based on the chart type i will call each class

Below is the sample of my code
`public class PieChart extends HighChartsFragment implements Constants{
    int lint_drilldown_count = 0;
    public HIOptions setOptionsforPieChart(){
		//Getting hiOptions from setter
        HIOptions hiOptions = highChartsOptions.getHiOptions();
        try {
            //Form Data required for Chart
            


            //Set Chart Type
            HIChart chart = new HIChart();
            chart.setType("pie");
            hiOptions.setChart(chart);

            //Set Title
            HITitle hiTitle = new HITitle();
            hiTitle.setText(lstr_chart_title);
            hiOptions.setTitle(hiTitle);

            HIExporting exporting = new HIExporting();
            exporting.setEnabled(true);
            hiOptions.setExporting(exporting);

            //Set Credits
            HICredits credits = new HICredits();
            credits.setEnabled(false);
            hiOptions.setCredits(credits);

            //Set Tooltip
            HITooltip tooltip = new HITooltip();
            tooltip.setPointFormat("{series.name}: <b>{point.percentage:.1f}%</b>");
            hiOptions. setTooltip(tooltip);

            //Set Plot Options
            HIPlotOptions plotOptions = new HIPlotOptions();
            plotOptions.setPie(new HIPie());
            plotOptions.getPie().setAllowPointSelect(true);
            plotOptions.getPie().setCursor("pointer");
            plotOptions.getPie().setDataLabels(new HIDataLabels());
            plotOptions.getPie().getDataLabels().setEnabled(true);
            plotOptions.getPie().getDataLabels().setFormat("<b>{point.name}</b>: {point.percentage:.1f} %");
            plotOptions.getPie().getDataLabels().setStyle(new HIStyle());
            plotOptions.getPie().getDataLabels().getStyle().setColor("black");
            hiOptions.setPlotOptions(plotOptions);

            //Set Data for Chart
            HIPie pie = new HIPie();
            pie.setName(lstr_display_name);

            for (int lint_i = 0 ; lint_i < jsonarr_chart_data.length() ; lint_i++)
            {
                //Set data for chart
            }



            pie.setData(series_data);
            try {
                pie.setPoint(new HIPoint());
                pie.getPoint().setEvents(new HIEvents());
                pie.getPoint().getEvents().setClick(new HIFunction(
                        f ->{
                            lint_drilldown_count++;
                            try {
                               
                            } catch (JSONException e) {
                                e.printStackTrace();
                            }
                           
                        },
                        new String[] {"name", "y"}
                ));
            }catch (Exception e)
            {
                e.printStackTrace();
            }




            ArrayList series = new ArrayList<>();
            series.add(pie);
            hiOptions.setSeries(series);
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        return hiOptions;
    }
}
`

**Comment by soommy12** [comment]
The only thing which your HIFunction is doing is incrementing `lint_drilldown_count` value. Please, try to give me more details about your goals.

**Comment by saravananraj21** [comment]
After setting click event on pie chart, based on the value from the pie chart i am retrieving the data for another chart from database and trying to reload the chart at the same index.

` HIChartView hiChartView = (HIChartView)high_chart_fragment_view.findViewById(Integer.parseInt(index));
manager.setChart( hiChartView , c ,lstr_graph_type,true , chart_data, chart_index , highChartsOptions);
hiChartView.reload();`

After this in the charts manager based on the chart type it will call the respective class.

I have made the context and highChartOptions as static and also passing the highChartsOptions to the respective chart class and with the help of the highChartsOptions i am getting the hioptions from the pojo class as the code mentioned in my previous comment.

The issue here is i'm able to reload the chart but can't set click events for the chart.

**Comment by soommy12** [comment]
Do you use `HIDrilldown` class in your chart options? If yes, did you attach `drilldown` as plugin? What is the purpose of `lint_drilldown_count` variable? What is your `manager.setChart()` method doing? Seems like you want to load a new series with new values for each data point value on your basic, first-loaded chart. If yes, drill-down will be much easier to implement but you will need to get all the data from your database at once.

**Comment by saravananraj21** [comment]
Hi @soommy12 ! I want to reload a different chart with different values, for that HIDrilldown will not be suitable because it loads the same type of chart with different values.

**Comment by pawelfus** [comment]
Hi @saravananraj21 
Due to the christmas time it will take some time until we are able to look into a solution.
Thank you for your patience.
