### ISSUE TITLE
HIStyle Deprecated 

### ISSUE THREAD

**Issue by ArunVicky001** [highcharts/highcharts-android#43]
Hi I am using `HIStyle` for Chart styling, in 6.2 version it has been deprecated, Instead it ask us use `HICSSObject` but it's not working properly, 

In the below code snippet the style is not applying to the to the HITitle class

     ```
       HICSSObject ChartTitleStyle = new HICSSObject();
        ChartTitleStyle.setColor("black");
        ChartTitleStyle.setFontSize("11px");
        ChartTitleStyle.setFontFamily("Arial");

       HITitle ChartTitle = new HITitle();
        ChartTitle.setText("Welcome");
        ChartTitle.setStyle(ChartTitleStyle);
```

**Comment by soommy12** [comment]
Hello @ArunVicky001 ! Your code works properly. Are you sure you set your title to options?

**Comment by ArunVicky001** [comment]
Yes I set the title to my `Option` `options.setTitle(ChartTitle);` I think `HICSSObject` is not working for `HITitle` alone.

**Comment by ArunVicky001** [comment]
@soommy12 Thanks for your response
 
But the `HICSSObject` works for HIXAxis and HIYAxis

```
xaxis.getLabels().setStyle(hicssObject);
yaxis.getLabels().setStyle(hicssObject);
```

Because of this i Just downgrade the `HIghChart` library, please tell is there is any other way to use `HICSSObject` class?

**Comment by ArunVicky001** [comment]
I am sorry, The above code is works for you? the same code is not working for me. Chart title always be in GRAY colour with default font size.

**Comment by soommy12** [comment]
Yes, it's working like a charm. You probably have overridden your `HITitle` somewhere later.
![screenshot_1545044561](https://user-images.githubusercontent.com/23573237/50083399-ef00d280-01f3-11e9-87bd-845943d91327.png)

**Comment by ArunVicky001** [comment]
Thank you very much for your clear update I will look into my code

**Comment by soommy12** [comment]
Well, I copy-pasted your code and it works. This is the result:
![screenshot_1545051596](https://user-images.githubusercontent.com/23573237/50088810-5fafeb00-0204-11e9-8dbe-3c3a687e07da.png)
Are you sure you're not playing around with the title somewhere else in your code?

**Comment by ArunVicky001** [comment]
Oh no What version are you using? Am using this version `implementation 'com.highsoft.highcharts:highcharts:6.2'`

Let me update the version and check.

**Comment by soommy12** [comment]
I tested it both on `6.2` and `7.0`

**Comment by ArunVicky001** [comment]
Have checked with your 

> Well, I copy-pasted your code and it works. This is the result:
> ![screenshot_1545051596](https://user-images.githubusercontent.com/23573237/50088810-5fafeb00-0204-11e9-8dbe-3c3a687e07da.png)
> Are you sure you're not playing around with the title somewhere else in your code?

I just created the sample application and implemented one single chart, added styles to the HITitle but still its not working. I am not sure what I am missing here.

**Comment by ArunVicky001** [comment]
I am curious to know how its working for you ?

**Comment by ArunVicky001** [comment]
I just checked with your source from my end, that code also not working with the custom style (`HICSSObject`) of `HITitle`

**Comment by ArunVicky001** [comment]
There is something gone wrong please guide me to do that in the correct way.

**Comment by ArunVicky001** [comment]
We have tried the same code in different machine there also we are getting the same issue. 
here is our build.gradle file code 
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.varunagiri.myapplication"
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

repositories {
    maven {
        url "https://highsoft.bintray.com/Highcharts"
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.highsoft.highcharts:highcharts:7.0'
    implementation 'com.google.code.gson:gson:2.8.1'
}
`

**Comment by soommy12** [comment]
I tried the same on the separate project. Found that there is a problem with style serialization, this happens surprisingly only for `HITitle` at this moment. I am working on it.

**Comment by ArunVicky001** [comment]
Ufff Thank god.

**Comment by ArunVicky001** [comment]
May i please to know is the updates regarding the issue?

**Comment by ArunVicky001** [comment]
HI, 
`HIItemStyle` functionality and `HIDataLabels` labelFormatter with different colours using jsfunction is also not working in the `HICSSObject` class please check.

**Comment by sebastianbochan** [comment]
Hi @ArunVicky001,
Due to the christmas time it will take some time until we are able to look into a solution.
Thank you for your patience.

**Comment by royorange** [comment]
Version: 7.0
Hi, @soommy12 
I also face the similar issue.
The HICSSObject is not work for the HiTitle, but works well for HILabels.
Here is my code:      

        HIYAxis yaxis1 = new HIYAxis();
        HILabels labels1 = new HILabels();
        labels1.setFormat("{value}°C");
        HICSSObject hicssObject = new HICSSObject();
        hicssObject.setColor("rgb(144,237,125)");
        labels1.setStyle(hicssObject);
        yaxis1.setLabels(labels1);

        HITitle ytitle = new HITitle();
        ytitle.setText("Temperature");
        ytitle.setStyle(hicssObject);
        yaxis1.setOpposite(true);
        yaxis1.setTitle(ytitle);
        
![image](https://user-images.githubusercontent.com/12166563/50417738-ec8d2100-0862-11e9-9f91-f5f1c0f4a5d1.png)

I set the same color to title and label, but only label works.
Thanks.

**Comment by ArunVicky001** [comment]
@sebastianbochan  and @soommy12 Thank you very much for this library and your support, We all waiting for your next (HICSSObject working) version.

**Comment by soommy12** [comment]
@ArunVicky001 @royorange the update is scheduled for this week.

**Comment by ArunVicky001** [comment]
@soommy12 Thanks for your response.

**Comment by ArunVicky001** [comment]
@soommy12 May I please to know the update regarding the HICSSObject?

**Comment by soommy12** [comment]
@ArunVicky001 new version was released last week and the bug fix was included [in the changelog](https://github.com/highcharts/highcharts-android/releases/tag/v7.0.1).

**Comment by ArunVicky001** [comment]
> HI,
> `HIItemStyle` functionality and `HIDataLabels` labelFormatter with different colours using jsfunction is also not working in the `HICSSObject` class, please check.

Thanks you very much latest update the HITitle style is working fine, 
  
Hi as I mentioned earlier `HIDataLabels` labelFormatter with `HIFunction` is not working 
previously it was worked with HIStyle I was used the below method, 

`public HIDataLabels dataLabelsYoY() {
        HIStyle dataLableStyle = new HIStyle();
        dataLableStyle.setFontSize("10px");

        HIDataLabels dataLabels = new HIDataLabels();
        dataLabels.setEnabled(true);
        dataLabels.setCrop(false);
        dataLabels.setOverflow(false);
        dataLabels.setUseHTML(true);
//        String jsfunction = "function() { var percentile = Number(((this.y - this.point.prior) / this.point.prior * 100).toFixed(0)); var yData = this.y; if (yData > 100) { yData = Highcharts.numberFormat(yData, 0, ',', ','); } var labelValue; var percent = percentile; labelValue = '<span style = ' + 'color:#000' + '>'+yData+'</span>'; if (yData == 0) { labelValue += ''; } else { labelValue += '<span style =' + 'color:#e28507' + ';font-weight:bold' + '>' + ' (' + percent + ')</span>'; } return labelValue; }";
      
        HIFunction labelFormatter = new HIFunction(jsfunction);
        dataLabels.setFormatter(labelFormatter);
        dataLabels.setStyle(dataLableStyle);

        return dataLabels;
    }`

previously it was like this, Could you please help on this?  
<img width="167" alt="sample" src="https://user-images.githubusercontent.com/34921497/50823301-a7d0b200-1359-11e9-8dae-5dacdf443eb2.png">

Thanks!

**Comment by soommy12** [comment]
@ArunVicky001 I will investigate this problem. Can you please upload again the second image? I cannot view it.

**Comment by ArunVicky001** [comment]
@soommy12 Uploaded the image please check

**Comment by soommy12** [comment]
@ArunVicky001 Can you please share more code? Would be perfect if you could provide the series initialization snippet.

**Comment by ArunVicky001** [comment]
@soommy12 I have updated the code below please check 

``` 

       chartView = (HIChartView) findViewById(R.id.hc);
        HIOptions options = new HIOptions();

        HITooltip tooltip = new HITooltip();
        tooltip.setFormatter(new HIFunction("function() {return false;}"));
        tooltip.setShared(true);
        options.setTooltip(tooltip);

        HIChart chart = new HIChart();
        chart.setEvents(new HIEvents());
        chart.setType("line");

        options.setChart(chart);
        chart.getAnimation();

        HIExporting exporting = new HIExporting();
        exporting.setEnabled(false);
        options.setExporting(exporting);

        HICredits credits = new HICredits();
        credits.setEnabled(false);
        options.setCredits(credits);

        HICSSObject ChartTitleStyle = new HICSSObject();
        ChartTitleStyle.setColor("red");
        ChartTitleStyle.setFontSize("15px");
        ChartTitleStyle.setFontFamily("Arial");

        HITitle title = new HITitle();
        title.setText("First Chart");
        title.setStyle(ChartTitleStyle);
        options.setTitle(title);

        String categories[] = new String[0];
        categories = new String[]{"100Kg", "200Kg", "300Kg", "400Kg", "500Kg", "600Kg", "700Kg", "800Kg", "900kg", "1000kg", "1100kg", "1200kg", "1300kg", "1400kg", "1500kg"};

        HIMarker marker = new HIMarker();
        marker.setEnabled(true);

        final HIXAxis xaxis = new HIXAxis();
        xaxis.setLabels(new HILabels());
        xaxis.setTickmarkPlacement("on");

        HICSSObject hicssObject = new HICSSObject();
        hicssObject.setFontFamily("Arial");
        hicssObject.setFontSize("10px");

        xaxis.getLabels().setStyle(hicssObject);
        xaxis.getLabels().setY(0);
        xaxis.getLabels().setStep(2);
        xaxis.setCrosshair(new HICrosshair());
        xaxis.getLabels().setRotation(270);
        xaxis.setCategories(new ArrayList<>(Arrays.asList(categories)));
        options.setXAxis(new ArrayList<HIXAxis>() {{
            add(xaxis);
        }});

        final HIYAxis yaxis = new HIYAxis();
        yaxis.setLineWidth(1);
        yaxis.setGridLineWidth(1);
        yaxis.setLabels(new HILabels());
        yaxis.getLabels().setStyle(hicssObject);
        yaxis.getLabels().setX(-3);
        yaxis.setTitle(new HITitle());
        yaxis.getTitle().setText("");
        options.setYAxis(new ArrayList<HIYAxis>() {{
            add(yaxis);
        }});

        ArrayList<Map<String, Object>> TotalValues = new ArrayList<Map<String, Object>>();
        Number[] seriesOfNumbers = {834, 503, 177, 658, 031, 831, 133, 175, 503, 177, 658, 031, 831, 133, 175};

        int k = 0;
        while (k < 15) {
            Map<String, Object> MyData2 = new HashMap<>();
            MyData2.put("y", seriesOfNumbers[k]);
            MyData2.put("prior", "1351");
            TotalValues.add(MyData2);
            k++;
        }

        HICSSObject dataLableStyle = new HICSSObject();
        dataLableStyle.setFontSize("10px");

        HIDataLabels dataLabels = new HIDataLabels();
        dataLabels.setEnabled(true);
        dataLabels.setCrop(false);
        dataLabels.setOverflow(false);
        dataLabels.setUseHTML(true);
        String jsfunction = "function() { var percentile = Number(((this.y - this.point.prior) / this.point.prior * 100).toFixed(0)); var yData = this.y; if (yData > 100) { yData = Highcharts.numberFormat(yData, 0, ',', ','); } var labelValue; var percent = percentile; labelValue = '<span style = ' + 'color:#000' + '>'+yData+'</span>'; if (yData == 0) { labelValue += ''; } else { labelValue += '<span style =' + 'color:#e28507' + ';font-weight:bold' + '>' + ' : ' + percent + '</span>'; } return labelValue; }";

        HIFunction labelFormatter = new HIFunction(jsfunction);
        dataLabels.setFormatter(labelFormatter);
        dataLabels.setStyle(dataLableStyle);

        HILine line1 = new HILine();
        line1.setName("line1");
        line1.setDataLabels(dataLabels);
        line1.setColor(HIColor.initWithRGBA(0, 155, 255, 1));
        line1.getDataLabels().setY(-30);
        line1.getDataLabels().setRotation(270);
        line1.setData(new ArrayList<>(TotalValues));
        line1.setPoint(new HIPoint());
        line1.getPoint().setEvents(new HIEvents());
        options.setSeries(new ArrayList<HISeries>(Arrays.asList(line1)));

        chartView.setOptions(options);  
```
it shows the result like below (the chart datalabel should display with two colors but it doesn't take those colors which I mention in the JS function)

<img width="364" alt="sample" src="https://user-images.githubusercontent.com/34921497/50840825-635d0a80-1389-11e9-873b-d78a830732f4.png">

expected result is 

<img width="167" alt="sample" src="https://user-images.githubusercontent.com/34921497/50840944-a3bc8880-1389-11e9-9bfd-2ab1668e5cb2.png">

**Comment by ArunVicky001** [comment]
@soommy12 Did you check the code?

**Comment by soommy12** [comment]
@ArunVicky001 when it comes to `HIDataLabels` rotation parameter things are more complicated. The core library has to do many background processes and during those, the styling is lost. The workaround for it can be done by direct manipulation on SVG object. It can be done like this:
        
```
String colorizedItems = "function colorizeItems() { var chart = this, each = Highcharts.each, dl; each(chart.series, function (serie) { each(serie.data, function (point) { dl = point.dataLabel && point.dataLabel.element; if (dl && dl.childNodes) { dl.childNodes[3].setAttribute('fill','#e28507'); } }); }); }";

HIChart chart = new HIChart();
chart.setEvents(new HIEvents());
chart.getEvents().setLoad(new HIFunction(colorizedItems));
chart.getEvents().setRedraw(new HIFunction(colorizedItems));
chart.setType("line");
options.setChart(chart);
```

**Comment by ArunVicky001** [comment]
@soommy12 In the above solution you are reinitiating the Events `chart.setEvents(new HIEvents());` If I did like that the previous Events not are not working 

Example Initially I have set Event for hovering the chart 

`HIChart chart = new HIChart();
        chart.setEvents(new HIEvents());
        chart.setType("line");
        chart.getEvents().setLoad(new HIFunction(
                "function () { this.series[0].data[5].setState('hover'); this.series[1].data[5].setState('hover'); }"
        ));
        options.setChart(chart)` 

this events are not working, Could you please tell how to achieve both?

**Comment by soommy12** [comment]
All you have to do is combine these two functions into one string as if you do it in Javascript

**Comment by ArunVicky001** [comment]
Super, I combine those two JS function into one now both functions are working fine.
Thanks you!
