### ISSUE TITLE
How to invoke the HIFunction programmatically

### ISSUE THREAD

**Issue by ArunVicky001** [highcharts/highcharts-android#44]
Hi,
How to do the click event in the specified index programmatically, for example if i click on the chart HIEvents will be trigger and HIFunction will be call. Exactly the same process I want to in programmatically. 

Please tell the possible way to achieve this.
Thanks.

**Comment by soommy12** [comment]
Hi, I'm afraid that I don't get what you mean. Could you please explain in more details by saying invoking `HIFunction` programmatically?

**Comment by ArunVicky001** [comment]
Here is my `HILine` creation core 

HILine line1 = new HILine();
        line1.setName("line1");
        line1.setDataLabels(dataLabels);
        line1.setColor(HIColor.initWithRGBA(0, 155, 255, 1));
        line1.getDataLabels().setY(-30);
        line1.getDataLabels().setRotation(270);
        line1.setData(new ArrayList<>(Arrays.asList(43934, 52503, 57177, 69658, 97031, 119931, 137133, 154175)));


        line1.setPoint(new HIPoint());
        line1.getPoint().setEvents(new HIEvents());
        line1.getPoint().getEvents().setClick(new HIFunction(
                f -> {
                    double xVal = (double) f.getProperty("x");
                    int indx = (int) xVal;
                    double rem = xVal - indx;
                    if (rem > 0.5) {
                        indx += 1;
                    }
                    getSelectedValues(indx);
                },
                new String[]{"x"}
        ));

if I click on the line which is there in the chart this method  `(line1.getPoint().getEvents().setClick(new HIFunction(....)`  will return the index (selection index value) of the line.  

So here I want skip the click and programmatically pass some values to make the click. 

Is it possible in this library?

**Comment by soommy12** [comment]
You can pass your own method in the callback which takes values from the chart as parameters. In that way, you can put whole logic into a separate method without affecting your options readability. For example:

```
 line1.getPoint().getEvents().setClick(new HIFunction(
                f -> {
                    myMethod(f.getProperty("x"), f.getProperty("y"));
                },
                new String[]{"x", "y"}
        ));

```

**Comment by ArunVicky001** [comment]
There is no difference between my code and your example , both methods are only called when i click on the chart. 
<img width="317" alt="screen shot 2018-12-17 at 4 33 55 pm" src="https://user-images.githubusercontent.com/34921497/50083509-0c489780-021a-11e9-992e-04c9e92e556b.png">

Actually my requirement is while loading the chart I want to enable all the markers which there in the last position without clicking the chart.

**Comment by soommy12** [comment]
So, your requirement is slightly different. If you want to achieve something during load you should use `setLoad()` method instead of `setClick()`. Unfortunately, the native solution for this is still in works but you can still make it. For such events, you can inject pure `Javascript` code into your `HIFunction` object. 
```
        HITooltip tooltip = new HITooltip();
        options.setTooltip(tooltip);
        HIChart chart = new HIChart();
        chart.setEvents(new HIEvents());
        chart.getEvents().setLoad(new HIFunction(
                "function () { this.series[0].data[0].setState('hover'); this.series[1].data[4].setState('hover'); }"
        ));
        options.setChart(chart);
```
This solution gives the hover for specific points, obviously. Depending on your implementation, you can iterate over all data points in choosen series to set such state for all of them.

**Comment by ArunVicky001** [comment]
Thank you I will use this method.

**Comment by ArunVicky001** [comment]
Wow its working perfect. `"function () { this.series[0].data[5].setState('hover'); this.series[1].data[5].setState('hover'); }"`  Could please tell how to enable the crosshair in the same position.

**Comment by pradeep-orbi** [comment]
How to set tooltip for a point at load time programmatically ?
