### ISSUE TITLE
Changing color of y-axis values and x-axis values

### ISSUE THREAD

**Issue by Yusuf3650** [highcharts/highcharts-android#45]
Hi, thanks for the library!
I have issues in changing the color of y-axis values, x-axis values and the text color of the dot + text: 

As you can see here, you can not see the x-axis and y-axis values and the text next to the dot is black, but i need it to be grey_300: 

<img width="315" alt="skaermbillede 2018-12-22 kl 15 53 38" src="https://user-images.githubusercontent.com/26247082/50375686-f49a5600-0601-11e9-84ad-3c29f7397059.png">

If it's possible I also need to deactivate the inactive mode, so that it doesn't go inactive on click.

**Comment by Yusuf3650** [comment]
Update: I figured out that how to turn minor tick too the wanted color, but I am stuck in how to change the colors of the x-axis and y-axis values. Also the the color of the text next to the dot.

**Comment by ArunVicky001** [comment]
For changing the xAxis and yAxis colour you need to set style for the `HIXAxis` and `HIYAxis` classes and for changing the dot and label refer `HILegend` class

**Comment by sebastianbochan** [comment]
Hi @ArunVicky001,
Due to the christmas time it will take some time until we are able to look into a solution.
Thank you for your patience.

**Comment by Yusuf3650** [comment]
Thanks for the reply both of you. I hope it's not too much to ask for, but I would really like to see some examples. I have looked into HILegend, HIMarker etc, but can't figure it out. 

Yes, of course Sebastian. I Wish you both a great day!

**Comment by Yusuf3650** [comment]
Thank you very much! I figured it out by doing what ArunVicky001 told, and it worked. It looks like this:

<img width="319" alt="skaermbillede 2018-12-26 kl 00 44 47" src="https://user-images.githubusercontent.com/26247082/50427403-9098bb80-08a7-11e9-81ad-ee65c6281376.png">

I have one last question in this thread though. How can I disable the inactive function? I dont wan't it to go inactive on click on marker + text
