### ISSUE TITLE
Scroll in  horizontal when scale

### ISSUE THREAD

**Issue by royorange** [highcharts/highcharts-android#47]
Hi,
It's not able to scroll horizontal after I scale the chart.
I have set the HIScrollablePlotArea with minWidth, but it performs strange and still not work when scaled.
Is there any advice?
Thanks!

**Comment by sebastianbochan** [comment]
Hi @royorange ,
Due to the christmas time it will take some time until we are able to look into a solution.
Thank you for your patience.

**Comment by soommy12** [comment]
Hi @royorange , thanks for your question! Can you please share some snippet to help us reproduce the issue?

**Comment by royorange** [comment]
When user scale the chart in the mobile, they can't  scroll horizontal.
Is there some advice?

**Comment by soommy12** [comment]
Let's say you have `zoomType` set to **X** in your chart. After you zoom your chart you can still scroll it horizontally using two fingers.

**Comment by royorange** [comment]
Thanks for your response @soommy12 .
Seems two fingers can scroll when scale up. But it still scroll hard, seems have some gesture conflict(sometimes it will scroll and sometimes will scale).
This library [https://github.com/PhilJay/MPAndroidChart](url) works well in gesture.
Is that possible to scroll only by one finger like this one? 
It's more fit the habit of using mobile.
Thanks!

**Comment by soommy12** [comment]
Two fingers scrolling is caused by tooltip which updates as the finger moves on a device. In the other words: showing tooltip is following touch move. This is set by default. To enable scrolling with just one finger you need to disable this feature for the tooltip:
```
        HITooltip tooltip = new HITooltip();
        tooltip.setFollowTouchMove(false);
        options.setTooltip(tooltip);
```

**Comment by royorange** [comment]
It works, thanks.
