### ISSUE TITLE
Set Plot Gradient

### ISSUE THREAD

**Issue by Yusuf3650** [highcharts/highcharts-android#48]
How do I set the color of the plot to gradient just like this?

<img width="1165" alt="skaermbillede 2018-12-26 kl 00 44 12" src="https://user-images.githubusercontent.com/26247082/50427548-5af5d180-08ab-11e9-9c67-d07d31773e0e.png">

**Comment by sebastianbochan** [comment]
Hi @royorange ,
Due to the christmas time it will take some time until we are able to look into a solution.
Thank you for your patience.

**Comment by soommy12** [comment]
Hello @Yusuf3650 ! Plot gradient colour is set on a series of your choice. The gradient usage is described in [readme](https://github.com/highcharts/highcharts-android/blob/master/README.md). Use `setFillColor()` method on the series and pass your gradient there:
```
        HIArea area = new HIArea();
        HIGradient gradient = new HIGradient(0, 0, 0, 1);
        LinkedList<HIStop> stops = new LinkedList<>();
        stops.add(new HIStop(0, HIColor.initWithName("SkyBlue")));
        stops.add(new HIStop(1, HIColor.initWithName("white")));
        area.setFillColor(HIColor.initWithLinearGradient(gradient, stops));
```

**Comment by abusternielsen** [comment]
Thanks for your reply. It works perfectly. I have one last question, but i'll ask it in a new thread.
