### ISSUE TITLE
plot series are behind each other

### ISSUE THREAD

**Issue by abusternielsen** [highcharts/highcharts-android#49]
For some reason it stacks on each other, in a way so it looks like the series stacks behind each other and blends the colors of the series together. Also the marker in the 2nd series looks like it's behind the first series. I have 3 images to illustrate the problem:

<img width="318" alt="skaermbillede 2019-01-02 kl 19 17 10" src="https://user-images.githubusercontent.com/46161955/50605913-280f9700-0ec4-11e9-8722-23309960ae7d.png">

<img width="318" alt="skaermbillede 2019-01-02 kl 19 22 47" src="https://user-images.githubusercontent.com/46161955/50605929-31006880-0ec4-11e9-94db-34cf28e75adc.png">

<img width="318" alt="skaermbillede 2019-01-02 kl 19 23 03" src="https://user-images.githubusercontent.com/46161955/50605936-352c8600-0ec4-11e9-9147-c7a5c80b9eda.png">

CO2 serie is not currently working.

Is there a way to make the colors of the plots not to blend in with each other, so I can see the selected colors for each series?

**Comment by soommy12** [comment]
Hello @abusternielsen ! In such a situation, you have two options. 

You can change the order of your series while setting them to options (the last one is the most on top):
`options.setSeries(new ArrayList<>(Arrays.asList(humidity, temperatur)));`

or you can add an index for each (the highest number is the most on top):
`series.setIndex(0);`
