### ISSUE TITLE
Failed to resolve: com.highsoft.highcharts:highcharts:7.0.1

### ISSUE THREAD

**Issue by ercandemirtekin** [highcharts/highcharts-android#50]
Hi,

I am new on using the library and we are trying if it fits our need. I have written compile 'com.highsoft.highcharts:highcharts:7.0.1' in app gradle dependencies part and tried to sync but I took the error : Failed to resolve: com.highsoft.highcharts:highcharts:7.0.1

Any idea? I am waiting for quick responses,

Thanks

**Comment by soommy12** [comment]
Hi @ercandemirtekin ,

please read the [readme](https://github.com/highcharts/highcharts-android/blob/master/README.md) file on **Preparing your project** subpoint **A)** .

**Comment by ercandemirtekin** [comment]
Hi,

With adding maven repository it could build but it gave this 
:AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="com.highsoft.highcharts" to force usage (may lead to runtime failures)

It is written as the library compatible with 5.0 and later but now it suggest at least 19 as it may lead to run time failures. We should support our app for minSdk 16 and later. Would you guarentee that the app works smoothly with the devices less than minSdk 19?
