### ISSUE TITLE
Format Y axis labels with calcuations

### ISSUE THREAD

**Issue by Geowan** [highcharts/highcharts-android#51]
I have used highcharts with javascript and i would format Y axis like
      

                          labels: {
                            formatter: function () {
                                let d = parseInt(this.value);
                                if (d === 0) {
                                    return '0 sec';
                                }
                                d = Number(d);
                                const h = Math.floor(d / 3600);
                                const m = Math.floor(d % 3600 / 60);
                                const s = Math.floor(d % 3600 % 60);

                                const hDisplay = h > 0 ? h + (h === 1 ? ':' : ' h, ') : '';
                                const mDisplay = m > 0 ? m + (m === 1 ? ':' : ' m, ') : '';
                                //const sDisplay = s > 0 ? s + (s === 1 ? ':' : ' s ') : '';
                                return hDisplay + mDisplay;
                            }
                        }

On my android app i have the following

           yAxisLabels.setFormatter(
                 new HIFunction({
                    //here am stuck   
              })
           );

How do i impleement a formatted y axis labels using the above logic but with java with the HIFunction

**Comment by Geowan** [comment]
Hi @soommy12  do you have an example of doing this with a lamabada function, Looking at the one at the documentation where do i include a return statement with my formatted value, its not very clear on how ill achieve this

**Comment by soommy12** [comment]
Well, it's very easy as lambda let's you return statements. It is just normal block of code which you include in brackets
```
 yAxisLabels.setFormatter(
             new HIFunction({
                  f -> {
                   // your code with return statement;
                  return "" + f.getProperty("this.value");
            },
            new String[] {"this.value"}
          })
       );
```

**Comment by soommy12** [comment]
I am sorry, use `value` instead of `this.value`.

**Comment by Geowan** [comment]
Thanks this works
