### ISSUE TITLE
How to sync Chart click event between two charts? 

### ISSUE THREAD

**Issue by ArunVicky001** [highcharts/highcharts-android#54]
Hi, I am showing two different chart in the same view when I click the first chart the selection should reflect to the second chart in the same index. Could you please tell me how to achieve this?
Thanks!

**Comment by soommy12** [comment]
HI @ArunVicky001 , thanks for the question. Do you have two charts in one `HIChartView` or two separate views?

**Comment by ArunVicky001** [comment]
Hi Thanks for your response, 

I am having `HIChartView` in two different view.

**Comment by soommy12** [comment]
If you have two separate `HIChartView`'s the library doesn't provide a mechanism to sync them. Although, feel free to create your own logic for this.

**Comment by soommy12** [comment]
I am sorry, at first I thought you mean multiple series in one chart. There is no way to have multiple chart objects in one `HIChartView`. In the Android Wrapper one `HIChartView` is always one chart.

**Comment by ArunVicky001** [comment]
Okay Thank you!

**Comment by ArunVicky001** [comment]
Have one more question in this thread, Could you please tell how to enable `HICrosshair()` in particular index in the chart?
