### ISSUE TITLE
Proguard - E/libHC: Uncaught ReferenceError: updateOptions is not defined

### ISSUE THREAD

**Issue by Shakezulla57** [highcharts/highcharts-android#55]
Are there any known proguard rules needed? I'm getting `E/libHC: Uncaught ReferenceError: updateOptions is not defined` when using proguard but not otherwise. I get the axes and labels drawn, but the actual chart doesn't appear.

I know internally gson is being used so maybe we need specific gson rules?

**Comment by soommy12** [comment]
Hello @Shakezulla57 , thanks for your question. Gonna investigate your problem.

**Comment by Shakezulla57** [comment]
Hi @soommy12 
Thanks for taking a look, any update? Any more information you need from me?

**Comment by Shakezulla57** [comment]
Still getting the same error
I'm using these rules

```
# highcharts
-keep class com.highsoft.highcharts.** { *; }
-keepclassmembers class fqcn.of.class.containing.hichartview {
   public *;
}
-keepclassmembers class fqcn.of.javascript.interface.for.webview {
   public *;
}
```

**Comment by pradeep-orbi** [comment]
> Yes, in general, the Highcharts Android wrapper is using WebView where the chart is embedded. You should keep the class which contains `HIChartView`:
> 
> ```
> -keepclassmembers class fqcn.of.class.containing.hichartview {
>    public *;
> }
> ```
> 
> Hope this helps.

I'm facing the same issue. How to resolve this ?  I have added the following in the proguard rules file, but still not working
```
-keepclassmembers class com.files.ui.activity.ChartViewActivity {
   public *;
}
```
