### ISSUE TITLE
Using Android Studio 3.3 'compile' is obsolete and has been replaced with 'implementation'

### ISSUE THREAD

**Issue by abhishekhzb** [highcharts/highcharts-android#56]
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: app

**Comment by soommy12** [comment]
Hello @abhishekhzb ! This is only Android Studio information about gradle configuration. It has nothing to do with the library :)

**Comment by abhishekhzb** [comment]
Thanks for the reply , i solved the issue.

**Comment by kasumbarobert** [comment]
@abhishekhzb  How did you solve this problem?
