### ISSUE TITLE
Charts in recyclerview got repeat 

### ISSUE THREAD

**Issue by royorange** [highcharts/highcharts-android#57]
Hi, I use chart in recyclerView to display a chart list.
When I scroll up the list, some element got repeat, and after notify, some charts are displayed in the 
wrong position.
This seems a reuse issue, and all the native component works well especially the HiChartsView.
I found a method `reload()`, and it can solved the problem.
But this method was **deprecated** and show the animation every time it called and caused a bad performance.
Is there some solution or workaround for this?
Thanks~

**Comment by royorange** [comment]
It seems set `HIPlotOptions.getSeries().setClip(false)` can be a workaround for `reload()`?

**Comment by soommy12** [comment]
Hello  @royorange , thanks for your question. The charts positioning in your recycler view is not defined by the Highcharts library. 
When it comes to `reload()` method. It is deprecated because of matters which you already mentioned. That is why _chart update feature_ was introduced. The usage is very easy: just use setters when you need to update your chart. Keep in mind though that it won't work in fields which are of `ArrayList` type cause they do not provide this mechanism.

**Comment by royorange** [comment]
Thanks for your response @soommy12 . The setters you mean is `setOptions`?

**Comment by soommy12** [comment]
Yes, for example. But this will work for any field in options too.

**Comment by royorange** [comment]
The original issue is happened after I set option.
``` 
ItemChartBinding binding = helper.getBinding();  
binding.title.setText(item.getTitle());
binding.charts.setOptions(item.getHiChartOptions());
```
And I always see the same chart in the wrong position.
Maybe it's a webview issue?

**Comment by soommy12** [comment]
Could you explain in detail what do you mean by _the same chart_ and _wrong position_, please?

**Comment by royorange** [comment]
Currently, I handle it as below:
```
        ItemChartBinding binding = helper.getBinding();
        binding.title.setText(item.getTitle());
        binding.charts.setOptions(item.getHiChartOptions());
        if(!item.isDisplayed()){
            item.setDisplayed(true);
        }else{
            item.getHiChartOptions().getPlotOptions().getSeries().setClip(false);
        }
        binding.charts.reload();
```
And the chart's animation will only be executed when the first time the chart is scrolled in the screen.
Any better advices @soommy12 ?

**Comment by soommy12** [comment]
Yes, the animation should run when you see the chart for the first time - that is correct. Is this your adapter code?

**Comment by royorange** [comment]
@soommy12 For example：
The content in the red rect is the first position
![image](https://user-images.githubusercontent.com/12166563/51594777-2d468b80-1f30-11e9-94d3-aa864d22145f.png)
And when the position is 8, it appears again
![image](https://user-images.githubusercontent.com/12166563/51594849-52d39500-1f30-11e9-94a9-f4a9f6027b59.png)
You can see the title is different(It's a textview).
And every time when the recycler adapter callback called, I always set the option to the chart.
When I called `reload()`, it works well.

**Comment by royorange** [comment]
Yes, it's my adapter code.

**Comment by soommy12** [comment]
Looks like a bigger problem. Could you please share how options for your charts are initialized? Are you sure you're not giving the same data for series on different charts?

**Comment by soommy12** [comment]
Thanks @royorange . I will try to reproduce your issue now.

**Comment by soommy12** [comment]
Does your adapter override `getItemId()` and `getItemViewType()` methods? As I said the library has nothing to do with the RecyclerView order of items.
If you want to set the data to your chart after receiving data from backend you should set your `RecyclerView`'s adapter AFTER fetching data. No need to initiate a chart without options. Of course, you can do that (but to have empty white view you need to set empty text view and disable both credits and exporting because they are set by default even in empty options)

**Comment by soommy12** [comment]
I know that you have one view type but recycler view needs to know which view bind to the specific position. Please, override those two methods in your adapter like this: 
```
    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public int getItemViewType(int position) {
        return position;
    }
```

It applies to every `RecyclerView` and it's not content depended.
Speaking of the chart data - if it's wrong it's up to you. The library takes data which you give.
When it comes to the exception, without this you won't have an idea why the chart didn't render.

**Comment by royorange** [comment]
@soommy12 thanks for your response.
`getItemId` is always overrided in my base adapter.
I tested let `getItemViewType` return position, it works but I think it has some better solution.
Let `getItemViewType` return position will call much more `onCreateView` which will cause a bad performance(because of the inflate method).
I printed the log, this problem always happened when adapter reuse a viewHolder .
The layout contains not only the chartView and every other view works well (like the text in textView) except the chartView.
Maybe it is related to the observer-mode？

**Comment by soommy12** [comment]
Well, it seems that you have done everything properly in here. If you are setting the data after the response from a server you should notify the adapter so it calls `onBindViewHolder` where the options would be set again. No need for calling reload. Anyways, you pointed it right - the problem can be related to the observers. If yes, the library will definitely need a fix. 
However, I couldn't reproduce your problem. Could you please share some more code or send me a sample demo (via e-mail or here) which will be representing the same problem? I need some more snippets from you to analyse it better.

**Comment by royorange** [comment]
Ok, I will try to write a demo later.

**Comment by royorange** [comment]
@soommy12 I send a demo to your email, please check.

**Comment by soommy12** [comment]
Thanks @royorange ! I got the mail and will check the project out

**Comment by adenisyuk** [comment]
@soommy12 , any updates on this?

In our project, we have only one HIChartView on the screen, which is bound to the ObservableField<HIOptions> via data binding.

And as @royorange mentioned  - only the first call to hiChartView.setOptions() results in rendering the chart data. All subsequent calls don't cause redrawing the chart. 

HIChartView.reload() fixes the issue, but it's deprecated.
If it is deprecated, what is the new suggested way to update the data? [Documentation](https://api.highcharts.com/android/highcharts/) doesn't explain this. 
In your [sample app](https://github.com/highcharts/highcharts-android/blob/master/Example/HighFit/app/src/main/java/com/highsoft/highfit/AreaChartFragment.java)  deprecated reload() method is still used, btw  (comment it and you'll see the issue).

We are currently on an evaluation phase (try and play with different charting libs) and HighCharts for now is kinda winning... but this issue looks like a blocker and might change the decision.

Highly appreciate your input

**Comment by soommy12** [comment]
Hi @adenisyuk ! Thanks for your post. I am already working on the issue. Thanks for mentioning the demo app, I will update it as fast as the problem will be solved. Speaking of the documentation - you are right. It doesn't explain what is the proper alternative to reload. The next library update is on its way. The docs will be changed and I consider adding a short note in the readme as well.

**Comment by soommy12** [comment]
Hi @royorange ! Can you please give me write permissions to your demo repository?

**Comment by royorange** [comment]
Hi @soommy12 , sorry for my late reply. I have added you as a collaborator.
