### ISSUE TITLE
Lengend and y-axis title position 

### ISSUE THREAD

**Issue by royorange** [highcharts/highcharts-android#59]
Hi,
My case is:
1. set the legend in the left&top of the chart with floating (not set title in the chart).
2. set the unit in the top of the y-axis.
---
**For the first one**,
 when I set chart title with empty string, the top space seems become 0.
Thus, if I want to put the legend on the top of the chart, I have to set spaceTop and minus Y (like y=-40) to locate.(And sometimes it doesn't work well).
![image](https://user-images.githubusercontent.com/12166563/51601945-aa79fc80-1f40-11e9-8671-7b6880f8dd1b.png)

**For the second**, 
I set the title of y like:align=high,rotation=0,verticalAlign=top, and it can not be set on the top of the y-axis.
![image](https://user-images.githubusercontent.com/12166563/51602076-0a70a300-1f41-11e9-8aa7-f251a69e2491.png)

Any  advices?
Thanks.

**Comment by soommy12** [comment]
Hello @royorange !

The legend will be located as you specified when you use this code:
```
HILegend legend = new HILegend();
legend.setAlign("left");
legend.setVerticalAlign("top");
legend.setFloating(true);
options.setLegend(legend);
```
Although, if you want both title and legend _left_ and _top_ you still need to find out the best fitting position for you with setting Y properly.

When it comes to yAxis title you should use offset:
```
hiyAxis.setTitle(new HITitle());
hiyAxis.getTitle().setText("%");
hiyAxis.getTitle().setOffset(0);
hiyAxis.getTitle().setAlign("high");
hiyAxis.getTitle().setRotation(0);
hiyAxis.getTitle().setY(-15);
hiyAxis.getTitle().setX(-15);
```
You can play around with Y and X to get the best look for your requirements.

**Comment by royorange** [comment]
Thanks @soommy12 !
Seems because the empty title of the chart, I have to set the SpacingTop to the chart  , which based on the size of the curves. 
Thanks for your code.
