### ISSUE TITLE
Legend Border and Scrollbar

### ISSUE THREAD

**Issue by SSJ2912** [highcharts/highcharts-android#61]
Legend border provides outline on all 4 sides for the Legend. Is it possible to have border on only one side of the legend ?
Legend provides a navigation (with arrows) for long list of data. Is it possible to have the legends scrolled without clicking the navigation Button

**Comment by soommy12** [comment]
Hi @SSJ2912 ! If you have a long legend and `maxHeight` is set the buttons for scrolling are always visible. There is no other way for legend scrolling. If those buttons don't show up or they do not work as intended please explain this behavior for us so we can help.

When it comes to the border for your legend - it is totally achievable. Please share your chart options so we can understand your exact needs.

**Comment by SSJ2912** [comment]
Hi @soommy12 , I have attached a sample Chart Options with border. I would like to provide top border. The resulting Border would appear such that it divides the Chart View and Legend into segments.

```
            val options = HIOptions()
            options.chart = HIChart()
            options.chart.type = "line"
            val xAxis = HIXAxis()
            val categoriesList = arrayListOf("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
            xAxis.categories = categoriesList
            options.xAxis = arrayListOf(xAxis)
            
            val yAxis1 = HIYAxis()
            yAxis1.title = HITitle()
            yAxis1.crosshair = HICrosshair()
            yAxis1.title.text = "Series A"

            val yAxis2 = HIYAxis()
            yAxis2.title = HITitle()
            yAxis2.title.text = "Series B"
            yAxis2.opposite = true
            yAxis2.crosshair = HICrosshair()
            options.yAxis = arrayListOf(yAxis1 , yAxis2)

            options.legend = HILegend()
            options.legend.floating = false
            options.legend.borderWidth = 2
            options.legend.layout = "horizontal"
            options.legend.width = 300

            val map = hashMapOf<String , ArrayList<Double>>("Series A" to arrayListOf(395000.0, 90000.0, 940000.0, 890000.0) ,
                    "Series B" to arrayListOf(470050.0, 107100.0, 1020456.0, 1006750.0))
            val dataSeries = arrayListOf<HISeries>()
            for(key in map.keys)
            {
                val series = HISeries()
                series.data = map[key]

                series.name = key
                if(options.yAxis.size > 1) {
                    series.yAxis = getXAxisPosition(key , options.yAxis)

                }
                dataSeries.add(series)
            }
            options.series = dataSeries
```

**Comment by soommy12** [comment]
You can achieve this by using chart custom load event done in pure Javascript injected directly to your options object. Remove your legend border and try this:
```
HIChart chart = new HIChart();
chart.setEvents(new HIEvents());
chart.getEvents().setLoad(new HIFunction("function () { var chart = this, r = chart.renderer, legend = chart.legend.group, y = legend.translateY; r.path(['M', 0, y, 'L', chart.plotLeft + chart.plotWidth, y]) .attr({ 'stroke-width': 2, stroke: 'red', zIndex: 1 }) .add() }"));
options.setChart(chart);
```
Feel free to edit this custom function to meet your needs.

**Comment by SSJ2912** [comment]
Thank you  @soommy12 , The border works good. 
For Legend Scrolling , Android usually provide scrolling for List of data. It would be a little odd to provide click to scroll down. Isn't there any other way to overcome this problem

**Comment by soommy12** [comment]
Unfortunately, there is no support for legend scrolling. The Android library is wrapping the core Higcharts thus there won't be such feature.
