### ISSUE TITLE
Credits set click event

### ISSUE THREAD

**Issue by Geowan** [highcharts/highcharts-android#62]
I can set credits via

        HICredits hiCredits = new HICredits();
        hiCredits.setText(AppHelper.PROMO_TEXT);
        HICSSObject hicssObject = new HICSSObject();
        hicssObject.setFontSize("8sp");
        hicssObject.setFontWeight("400");
        hiCredits.setStyle(hicssObject);
        hiCredits.setEnabled(true);
        options.setCredits(hiCredits);

But one issue is on the click event. How do i set the click event of the credits to execute another function like open a dialog

so something like

         hiCredits.setOnClickListener(new ....)//how do i set this?

I know you can setHref via  hiCredits.setHref("mywebsite");  but i would like to have the click event

**Comment by soommy12** [comment]
Hi @Geowan . Unfortunately, the library classes don't support native click listeners. This is because the core library (which is wrapped by Java code) has its own ones. `HIChartView` classes represents the core library options which you can set. They are not separate views.
