### ISSUE TITLE
Time format in tooltip

### ISSUE THREAD

**Issue by royorange** [highcharts/highcharts-android#65]
Hi,
my tooltip is shown like:
![image](https://user-images.githubusercontent.com/12166563/51811250-15cc2180-22e7-11e9-8353-c7c565451398.png)
but I want to set the time format like "Thursday, Nov 29, 2018".
I see a property `xDateFormat` in the html but not in java method which for format.
Is it possible to add this method or is there some other solution?
Thanks.

**Comment by royorange** [comment]
Seems `tooltip.setHeaderFormat("{point.key:%A, %b %d, %Y}<br/>");` can format it. 😑

**Comment by soommy12** [comment]
That is right, `tooltip.setHeaderFortmat()` can do that. You can use a `formatter` too which takes `HIFunction` as the parameter (where you can use both native Java callback or pure JS).

**Comment by soommy12** [comment]
Yes, sure. First of all, you need to have axis type set to `datetime`:
```
HIXAxis hixAxis = new HIXAxis();
hixAxis.setType("datetime");
HITooltip tooltip = new HITooltip();
tooltip.setXDateFormat("%A, %b %d, %Y");
options.setTooltip(tooltip);
options.setXAxis(new ArrayList<>(Collections.singletonList(hixAxis)));
```
