### ISSUE TITLE
How can i enable multiple export options

### ISSUE THREAD

**Issue by savyad** [highcharts/highcharts-android#68]
I have successfully enabled export option as suggested in readme .But it only get image file how can i get csv,pdf and other formats as shown in android demo on the website.

**Comment by soommy12** [comment]
Hello @savyad ! Thanks for your question. Demos which you can see on the website are done in core Javascript library, only the code which is put there differs. Anyways, csv and pdf options are currently in works.

**Comment by savyad** [comment]
so as for now we can only export image right??so when are you going to release it i.e csv,pdf options

**Comment by savyad** [comment]
ok thanks,just one last question,when i click on the export button the pop gives me options to share the image but i want to download it instead is it possible.

**Comment by soommy12** [comment]
Actually, this is share action only. The saving chart on the local device will be added with pdf feature.
