### ISSUE TITLE
How to reload chart and change the xAxis Categories

### ISSUE THREAD

**Issue by Geowan** [highcharts/highcharts-android#69]
What am trying to achieve is to change the xAxis 

so initially i setup the xAxis with
         
        HIOptions options = new HIOptions();
        HIChart chart = new HIChart();
        chart.setType("column");
        options.setChart(chart);

        HITitle title = new HITitle();
        title.setText(chart_title);
        options.setTitle(title);

        HIXAxis xAxis = new HIXAxis();
        xAxis.setCategories(new ArrayList<>(Arrays.asList(passed_categoriesList)));
        xAxis.setCrosshair(new HICrosshair());
        xAxis.setMin(0);
        xAxis.setMax(2);
        options.setXAxis( new ArrayList<HIXAxis>(){{add(xAxis);}});

        HIYAxis yAxis = new HIYAxis();
        HITitle hiTitle= new HITitle();
        hiTitle.setText("Trucks");
        yAxis.setTitle(hiTitle);
        options.setYAxis(new ArrayList<HIYAxis>(){{add(yAxis);}});

        HIPlotOptions plotOptions = new HIPlotOptions();

        HIColumn hiColumn= new HIColumn();
        hiColumn.setPointPadding(0.2);
        hiColumn.setBorderWidth(0);
        HIDataLabels hiDataLabels = new HIDataLabels();
        hiDataLabels.setEnabled(true);

        hiColumn.setDataLabels(hiDataLabels);
        plotOptions.setColumn(hiColumn);
        options.setPlotOptions(plotOptions);

       chartView.setOptions(options);

Updating xAxis via

After fetching data via volley am trying to set xAxis columns via

          HIXAxis xAxis = new HIXAxis();
         xAxis.setCategories(new ArrayList<>(Arrays.asList(new_categories))); //an array of new
         options.setXAxis( new ArrayList<HIXAxis>(){{add(xAxis);}});
             chartView.setOptions(options);

The above does not update the xAxis colum labels. Also checking on my console am getting an error that

      E/Highcharts: Uncaught ReferenceError: updateOptions is not defined

I have also tried adding  chartView.reload();  but am seeing that this reload is deprecated

How do i perform the reload and change of axis

**Comment by soommy12** [comment]
Hi @Geowan ! Are you using pro guard in your app?

**Comment by Geowan** [comment]
Yes am using proguard to help in minifying the final app

**Comment by soommy12** [comment]
I am asking about the `proguard-rules.pro` content. You need to change it properly to let the library work as it should.
