### ISSUE TITLE
Unable to set FontFamily in chart.style

### ISSUE THREAD

**Issue by SSJ2912** [highcharts/highcharts-android#70]
I am trying to change the font style of a text using Kotlin. Implementing the same in JS works but the Kotlin code doesn't. Please refer the following code snippets.
JS :
```
chart: {
        type: 'column',
        style:{
        fontFamily :"proxima-nova"
        }
    }
```
Kotlin : 
```
val options = HIOptions()
options.chart = HIChart()
options.chart.style = HICSSObject()
options.chart.style.fontFamily = "proxima-nova"
```

**Comment by soommy12** [comment]
HI @SSJ2912 ! Did you attach you `HIChart` object to the options?

**Comment by adenisyuk** [comment]
@soommy12 ,  sorry for jumping in but, based on your response i wonder if proxima-nova (it is a font we want to use for our project) is included in Highcharts Android? 

I'm referring to [https://www.highcharts.com/forum/viewtopic.php?f=9&t=41559&p=145345#p145345](https://www.highcharts.com/forum/viewtopic.php?f=9&t=41559&p=145345#p145345)

**Comment by soommy12** [comment]
I will find out. Meanwhile, can you please share your "hack" which you told about in the forum's?

**Comment by adenisyuk** [comment]
@soommy12 
Sure, here is it

Generally, it works based on the fact that during app's build time all the assets are merged.
So there are four parts.

**First one** - place a custom JS module named `add-font.js` at the app assets folder at path `assets/js/modules/`. Here is it's the content:
```javascript
var css='@font-face{	font-family: "proxima_nova";	font-style: normal;	font-weight: 400;	src: url("charts_injected_font/proxima_nova_regular.otf");} @font-face{	font-family: "proxima_nova";	font-style: normal;	font-weight: 700;	src: url("charts_injected_font/proxima_nova_bold.otf");}';
head=document.head;
style=document.createElement('style');
style.type='text/css';
style.appendChild(document.createTextNode(css));
head.appendChild(style);
```

**Second part** - place a custom font files (`proxima_nova_regular.otf` and `proxima_nova_bold.otf` in our case) at the app assets folder at path `assets/charts_injected_font/`. 

**Third part** - tell the library to load custom JS module mentioned above:
```kotlin
chartView.plugins = mutableListOf(
	"add-font"
)
```

**Fourth part** - set the loaded font globally:
```kotlin
hiOptions.chart = HIChart().apply {
	style = HICSSObject().apply {
		fontFamily = "proxima_nova"
	}
}
```

**Explanation**: loaded custom JS module modifies the HTML page loaded into WebView (which is used by HIChartView internally) and places the font definitions at the head section which are linked to the fonts located at the app's assets:
```javascript
@font-face {
	font-family: "proxima_nova";	
	font-style: normal;	
	font-weight: 400;	
	src: url("charts_injected_font/proxima_nova_regular.otf");
}

@font-face {	
	font-family: "proxima_nova";	
	font-style: normal;	
	font-weight: 700;	
	src: url("charts_injected_font/proxima_nova_bold.otf");
}
```

**Comment by soommy12** [comment]
Thank you @adenisyuk ! I'm glad you did it by yourself :) Wanted to compare it with our approach. Our solution which will be added in a future release  (it's already done for iOS) is very similar. Stay tuned!

**Comment by soommy12** [comment]
@SSJ2912 @adenisyuk The new release gives the opportunity to use[ custom fonts ](https://github.com/highcharts/highcharts-android#custom-fonts)now
