### ISSUE TITLE
AAR bundle contains too much assets

### ISSUE THREAD

**Issue by adenisyuk** [highcharts/highcharts-android#72]
I'm not too familiar with JS, but I suspect not all the assets bundled with AAR should be there.
Each `*.js` file (which i think is obfuscated JS) has siblings like `*.src.js` and `*.js.map` (which i think is a obfuscator mapping file). 

Also, there are a lot of files at `examples` folder (like `area-basic/index.thm`, `box-plot/index.htm` etc). 

Is it ok those JS source and obfuscator mapping files are there, as well as examples? 
`examples` and `js` asset folders are 24Mb alltogether. Without `examples` folder, `src.js` and `js.map` files library size can be reduced by 18.2Mb

**Comment by adenisyuk** [comment]
Adding some screenshots:

![image](https://user-images.githubusercontent.com/1083700/52490875-0fcb2000-2bc6-11e9-806a-c8b0c7f14ec0.png)
![image](https://user-images.githubusercontent.com/1083700/52490879-12c61080-2bc6-11e9-9522-b618640e47e8.png)

**Comment by soommy12** [comment]
Helllo @adenisyuk ! Thanks for your question. We will take it into consideration. At this point, I can say that examples definitely shouldn't be there.

**Comment by soommy12** [comment]
The `src.js` files were here for developing purposes although in the release version they are certainly not needed. The next release will reduce the library size significantly. Thanks for your useful suggestion!

**Comment by adenisyuk** [comment]
I've checked the 7.0.3 version - fixed! 
Thank you, guys!
