### ISSUE TITLE
Highchart date time format not work in android.

### ISSUE THREAD

**Issue by mistrydarshan99** [highcharts/highcharts-android#73]
Hello,

I want to set the date format in x-axis like ("%m-%d %H:%M"). I have passed long formatted date in xaxis. But anyhow code is not worked.

Here is my code:
  
    
**Server response is** :  "[{name: 'Winter 2012-2013',data: [[11100, 0],[11100, 0.28],[11100, 0.25]]}]";

    final HIXAxis xaxis = new HIXAxis();
    xaxis.setType("datetime");
    HIDateTimeLabelFormats formats = new HIDateTimeLabelFormats();
    HIMonth month = new HIMonth();
    month.setMain("%Y/%m");
    formats.setMonth(month);
    HIDay hiDay = new HIDay();
    hiDay.setMain("%d:%m");
    formats.setDay(hiDay);
    xaxis.setDateTimeLabelFormats(formats);
    xaxis.setTickInterval(0.25 * 3600 * 1000);
    options.setXAxis(new ArrayList<HIXAxis>() {{
      add(xaxis);
    }});

    ArrayList<HISeries> list = new ArrayList<>();
    for (IrregularGraphBean listGraph : listGraphs) {
      HISeries series = new HISeries();
      series.setType("spline");
      series.setName(listGraph.getName());
      try {
        JSONArray jsonArray = new JSONArray(listGraph.getData());
        Number[][] seriesData = new Number[jsonArray.length()][2];
        for (int i = 0; i < jsonArray.length(); i++) {
          JSONArray innerArray = jsonArray.optJSONArray(i);
          for (int i1 = 0; i1 < innerArray.length(); i1++) {
            seriesData[i][0] = innerArray.getLong(0);
            seriesData[i][1] = innerArray.getInt(1);
          }
        }
        series.setData(new ArrayList<>(Arrays.asList(seriesData)));
        list.add(series);
      } catch (JSONException e) {
        e.printStackTrace();
      }
    }
    options.setSeries(list);
```

**Comment by soommy12** [comment]
Hello @mistrydarshan99 ! What is the output in your chart? Can you please post a screenshot? What is the exact input format of your date?
