### ISSUE TITLE
Moment.js is not included

### ISSUE THREAD

**Issue by adenisyuk** [highcharts/highcharts-android#75]
In order to show datetime X Axis labels in a different from device timezone, i changed it via:
`hiOptions.time = HITime().apply {
     timezone = "America/Havana"
}`

But it does not work, moreover, there are errors in logcat: https://www.highcharts.com/errors/25/ (Can't find Moment.js library)

**Comment by soommy12** [comment]
Hello @adenisyuk ! What version of the library are you using?

**Comment by adenisyuk** [comment]
7.0.1
Sorry for not mentioning this initially.
Now i see the newer 7.0.3 is available, gonna try it right now

**Comment by adenisyuk** [comment]
Well, it still doesn't work in 7.0.3 :( 
E/Highcharts: Highcharts error #25: www.highcharts.com/errors/25

**Comment by soommy12** [comment]
Yes, that's right. This is an external library which you need to include it by yourself. Although, we still need to implement the handling of external JS libraries.

**Comment by adenisyuk** [comment]
`external library which you need to include by yourself` 

- what is the proper way to do that?
I think it should be done like this:
```kotlin
chartView.plugins = mutableListOf(
	"external_library_name_placed_at_assets_folder"
)
```
But please confirm.


- which exact libraries and their versions should be injected? An example pointed by your documentation uses such libs: `moment.js/2.18.1/moment.min.js`  and `moment-timezone/0.5.13/moment-timezone-with-data-2012-2022.min.js`. Please take a look here: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/time/timezone/

- once again, Highcharts Android says nothing about loading any external library by the library client

**Comment by soommy12** [comment]
@adenisyuk 
After contacting with Highcharts JS developers I back with fresh great news. External JS libraries (which highcharts library uses) will be included in the core so the end user won't need to think about it. That's said the error which this issue tackles will never ever happens. In the easy words: in the future release (probably the next one) setting time to options will be working like a charm.

**Comment by marcinmatczuk** [comment]
@soommy12 , would it mean the JS libraries will be provided in all your framework products including iOS version?

**Comment by soommy12** [comment]
Yes, exactly
