### ISSUE TITLE
can we pass  data from csv file to the graph?

### ISSUE THREAD

**Issue by savyad** [highcharts/highcharts-android#76]
i want to pass data from csv file to the graph,do we have any options like data modules in js

**Comment by soommy12** [comment]
Hello @savyad ! Ofcourse you can. Open your CSV file and parse it to string then pass it to `data.setCsv()`. Check it out:
```
HIData data = new HIData();
// read your csv here
String csv = ....
data.setCsv(csv);
options.setData(data);
```
remember to add a proper plugin:
```
chartView.plugins = new ArrayList<>();
chartView.plugins.add("data");
```
You can find more information [here](https://www.highcharts.com/docs/working-with-data/data-module).

**Comment by savyad** [comment]
Hey i tried what you have suggested earlier thank you very much for that,but
i have further requirements
1)range Selector
2)mutiple scales as  number of series:-
       I have read about "Splines" but it only be initiated with "Series",So how do i acheive it with "HIData"
     as i am loading data from csv file.

Please tell me if above things are currently possible or not..

**Comment by soommy12** [comment]
1) This is not possible, it's part of Highstock only
2) According to [this](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/data/csv/) example, you can add multiple series to options which data will be filled by your `HIData` csv field. When you use `data.csv` you don't use `series.data` but the rest remains the same.

**Comment by savyad** [comment]
so 1st option is not possible right now right,
and what i want to achieve is,the series that is shown in graph via csv i want to set spline for each series and set name to the series too.
Or the only option to achieve above is to pass data as series not from csv.

**Comment by savyad** [comment]
Actually i want to show separate yaxis for each series.i am loading data from csv so how to make separate yaxis dynamically.

**Comment by soommy12** [comment]
When you are using CSV data you instantiate series as normal. The only difference is you won't use `series.data` as it is filled with data from `options.data`. Regarding yaxis, you can add a multiple of them to options and just pass the number of the yaxis which you want to assign to the specific series.

**Comment by savyad** [comment]
this is my csv 
datetime,ch1,ch2
2019-02-26 20:22:22,12,23
2019-02-26 20:22:22,12,23
2019-02-26 20:22:22,12,23
...
and so on,after loading the data the graph shows normally without any errors
following is the source code that i have use:-

```
HIChartView chartView = (HIChartView) findViewById(R.id.shw);

        HIRanges ranges = new HIRanges();

        chartView.plugins = new ArrayList<>();
        chartView.plugins.add("data");

        HIData data = new HIData();

                    try
                    {
                        CSV = show_graph(); //Function to convert csv to STRING.
                    }catch(Exception e)
                    {
                       e.printStackTrace();
                    }
        data.setItemDelimiter(",");
        data.setLineDelimiter("\n");
        System.out.println(CSV);
        data.setCsv(CSV);


        HIOptions options = new HIOptions();
        HICsv csv=new HICsv();


        HIExporting exporting = new HIExporting();
        exporting.setEnabled(false);
        exporting.setCsv(csv);
        HIChart chart = new HIChart();
        chart.setZoomType("x");
        chart.setType("line");
        options.setChart(chart);

        HITitle title = new HITitle();
        title.setText("XXXXX");

        options.setTitle(title);

        options.setData(data);
        options.set
        options.setExporting(exporting);
        chartView.setOptions(options);
```
it automatically detects ch1,ch2 as series of data and make a single y-axis scale.
what i want a separate scale for ch1 and ch2.

**Comment by soommy12** [comment]
As I told you in the previous post:
>Regarding yaxis, you can add a multiple of them to options and just pass the number of the yaxis which you want to assign to the specific series.

In other words: you should create the series without setting the data for them because those will be fetched from `options.data` object. Then you can assign another **yAxis** for them. See the example:
```
        HIYAxis hiyAxis1 = new HIYAxis();
        HIYAxis hiyAxis2 = new HIYAxis();
        hiyAxis2.setOpposite(true);
        options.setYAxis(new ArrayList<>(Arrays.asList(hiyAxis1, hiyAxis2)));

        HILine series1 = new HILine();
        HILine series2 = new HILine();
        series2.setYAxis(1);
        options.setSeries(new ArrayList<>(Arrays.asList(series1, series2)));
```

**Comment by savyad** [comment]
Thanks it worked!!
