### ISSUE TITLE
setExtremes: event.min and event.max are always not NULL

### ISSUE THREAD

**Issue by adenisyuk** [highcharts/highcharts-android#77]
`Highcharts Android v7.0.3`

I'm trying to detect zoom changes:

```kotlin
val xAxis = HIXAxis().apply {
     events = HIEvents().apply {
          setExtremes = HIFunction(
               HIConsumer {
                    val min = it.getProperty("min")
                    val max = it.getProperty("max")
                    Log.e("UTILS", "event: $min  $max")
                },
                arrayOf("min", "max")
          )
     }
}
```

Documentation says 
> When an axis is zoomed all the way out from the "Reset zoom" button, event.min and event.max are null

and it works so when i'm trying to do the same in JsFiddle:
```javascript
xAxis: {    
     events:{
          setExtremes:  function(event) {
               alert(event.min + "  " + event.max)
          }
     }
}
```

But for Android received `min` and `max` are always not nulls

**Comment by adenisyuk** [comment]
I managed to workaround this with following:
```kotlin
val xAxis = HIXAxis().apply {
    events = HIEvents().apply {
        afterSetExtremes = HIFunction(
            HIConsumer {
                val dataMin = it.getProperty("dataMin") as Double
                val min = it.getProperty("min") as Double
                val zoomedIn = dataMin < min
                Log.e("UTILS", "zoomed: $zoomedIn")
            },
            arrayOf("dataMin", "min")
        )
    }
}
```

But i think the behavior described in the first post might be an **issue** for someone.

Now, when i'm able to detect a zoom event, i want to programmatically reset chart's zoom by clicking on the native button in the app. I am able to do that in JsFiddle via `chart.zoomOut(); `, but how do i call the JS function from the native code for such a purpose?  Or maybe there is some other way to reset zoom via native code?

**Comment by adenisyuk** [comment]
NOTE: `Highcharts iOS`'s `HIChartView` has `zoomOut()` method. Any plans on add the same for Android?

**Comment by soommy12** [comment]
Hi @adenisyuk ! I'm glad you managed to do it yourself. When it comes to `zoomOut()` method (and other HIChartView methods) are currently in works. In short: this method will be available.

**Comment by adenisyuk** [comment]
But still, don't you found the behavior described in my initial post (event.min and event.max are always not NULL) as a bug? It behaves not as your documentation says

**Comment by soommy12** [comment]
Hi @adenisyuk ! The new release implements `zoomOut()` method. You can try it now.
