### ISSUE TITLE
Chart touch operations remap

### ISSUE THREAD

**Issue by adenisyuk** [highcharts/highcharts-android#78]
`Highcharts Android v7.0.3`

Is it possible to change the touch gestures for chart operations to following? : 

1. panning is made with one finger gesture
2. zooming is made by pinch to zoom two finger gesture
3. tooltip:
--     appears when user long presses on the chart area
--     follows the finger while the gesture is not interrupted (`MotionEvent.ACTION_MOVE`)
--     disappears when touch gesture is finished (`MotionEvent.ACTION_UP`)

**Comment by soommy12** [comment]
Hi @adenisyuk ! Thanks for your question. When it comes to 1 and 2, there was a question about that already ([link](https://github.com/highcharts/highcharts-android/issues/47)).
As for the tooltip, things are more complicated. There is a `WebView` embedded inside the `HIChartView` which contains the original JS chart. Every touch event which you can set to `HIChartView` doesn't apply directly to specific chart behaviours. Anyways, these matters are still in discussion and we are working hard to make the Highcharts wrapper feels more like normal Android view.

**Comment by MikolajMichalczak** [comment]
Additionally, to make tooltip following the finger, you can use `setFollowTouchMove()` method.
