### ISSUE TITLE
icon in Hiview

### ISSUE THREAD

**Issue by vishalvanpariya** [highcharts/highcharts-android#80]
![ss](https://user-images.githubusercontent.com/27823328/53359174-30ca9980-3958-11e9-831d-e61a2a554a54.jpeg)

What is this right angle icon?
The app crashes whenever I click on it.
How do I hide or remove it?

Give me Some Solution 
Thank You

**Comment by soommy12** [comment]
Hello @vishalvanpariya . This icon is related to the export feature. To make it work you need to add a provider for your app which is described in [readme](https://github.com/highcharts/highcharts-android/blob/master/README.md#additional-info) in detail. You can also disable the export by:
```
   HIExporting exporting = new HIExporting();
   exporting.setEnabled(false);
   options.setExporting(exporting);
```

**Comment by vishalvanpariya** [comment]
Thank You
