### ISSUE TITLE
ScrollablePlotArea makes Y Axis's background to black

### ISSUE THREAD

**Issue by SSJ2912** [highcharts/highcharts-android#81]
I am trying to make my chart view scrollable. When I set scrollablePlotArea, the Y-Axes’ layout is elevated and a black transparent background colour is applied automatically.
I can’t find any property to change its colour. How do I change it?

![screenshot_20190307-143759_ziaanalytics](https://user-images.githubusercontent.com/38619144/53945049-b849a280-40e6-11e9-9d7c-61efa98eb81d.jpg)

**Comment by soommy12** [comment]
Hi @SSJ2912, thanks for your question. This area is white for default. Are you sure you didn't override it or set up `styledMode` flag? Please share your options to let us analyze your problem.

**Comment by SSJ2912** [comment]
No, I didnt set any style property. The only properties that I set related to scrollablePlotArea are : 
```
  chartOption.chart.scrollablePlotArea = HIScrollablePlotArea()
  chartOption.chart.scrollablePlotArea.minWidth = 3000
  chartOption.chart.scrollablePlotArea.scrollPositionX = 0
```

**Comment by soommy12** [comment]
Your `scrollablePlotArea` options are ok. Can you please share the whole chart options which I meant?

**Comment by SSJ2912** [comment]
Found the porblem!. When I set chart.backgroundColor with Hex value, there is no issue.
But when I set it with RGBA as (0 , 0 , 0 , 0.0) , the above problem arises.

```
options.chart.scrollablePlotArea = HIScrollablePlotArea()
options.chart.scrollablePlotArea.minWidth = 3000
options.chart.scrollablePlotArea.scrollPositionX = 0
options.chart.showAxes = true
options.chart.backgroundColor = HIColor.initWithRGBA(0,0,0,0.0)
```

**Comment by soommy12** [comment]
That is correct. The scrollable mask [has fixed opacity](https://github.com/highcharts/highcharts/blob/f69a4f2fe/js/parts/ScrollablePlotArea.js#L175-L183). To achieve transparency you can use `HIColor.initWithRGBA(255, 255, 255 ,0.0)`

**Comment by SSJ2912** [comment]
When I set the above (255,255,255,0.0) to a darker background , the Y Axis pane is shown in White. I need to set the entire Chart to alpha 0, so my chart would adapt to any background . Is there any way to achieve that?

**Comment by soommy12** [comment]
Unfortunately, the opacity for the scrollable mask is not configurable. If you want to have no opacity you need to resign from `scrollablePlotArea`. Anyways, that is the javascript library matter. Feel free to create an issue [there](https://github.com/highcharts/highcharts/issues). If the change will be made on the javascript side it will also be applicable to the mobile wrapper.

**Comment by SSJ2912** [comment]
Hi @soommy12 ,
The solution from their side is setting "fill" through CSS. It is working fine in jsfiddle but I couldn't set it from HIFunction. Is there any way to use CSS from HIFuntion?
```
.highcharts-scrollable-mask {
  fill: rgba(0, 0, 0, 0);
}
```

**Comment by soommy12** [comment]
There is no other way to manipulate CSS other than `HICSSObject`. Although, I just came upon a new idea. I'll find out if enabling passing custom values to `HICSSObject` class can make the colour fill happen.

**Comment by SSJ2912** [comment]
@soommy12  Did you find any solution for the problem?

**Comment by pawelfus** [comment]
FYI: New option will be available since v7.1.1: `chart.scrollablePlotArea.opacity`.

Related PR: https://github.com/highcharts/highcharts/pull/10468

**Comment by SSJ2912** [comment]
Thank you @pawelfus , Can you specify the Estimated Time for that release?

**Comment by pawelfus** [comment]
@SSJ2912 - v7.1.0 was just released (a week ago), so we haven't specified ETA for the next release, sorry. In general we release new version every few weeks.
