### ISSUE TITLE
x-Axis last label is not showing 

### ISSUE THREAD

**Issue by ArunVicky001** [highcharts/highcharts-android#84]
Hi, 

I am trying to display the last label of the xaxis but it not displaying 
here is my code please check and correct me why it's not coming 

        ```
        final HIXAxis xaxis = new HIXAxis();
        xaxis.setLabels(new HILabels());
        xaxis.setTickmarkPlacement("on");

        HICSSObject hicssObject = new HICSSObject();
        hicssObject.setFontFamily("Arial");
        hicssObject.setFontSize("10px");

        xaxis.getLabels().setStyle(hicssObject);
        xaxis.getLabels().setY(0);
        xaxis.getLabels().setStep(2);
        xaxis.setCrosshair(new HICrosshair());
        xaxis.getLabels().setRotation(270);
        xaxis.setShowLastLabel(true);
        xaxis.setCategories(new ArrayList<>(Arrays.asList(categories)));
        options.setXAxis(new ArrayList<HIXAxis>(){{add(xaxis);}});

```
Thanks

**Comment by soommy12** [comment]
Hi @ArunVicky001 ! I will investigate your problem.

**Comment by ArunVicky001** [comment]
okay thank you!

**Comment by soommy12** [comment]
The `setShowLastLabel` is set to `true` by default and applies to the whole xAxis. Can you please explain in detail what are your requirements?

**Comment by ArunVicky001** [comment]
<img width="740" alt="Sample1" src="https://user-images.githubusercontent.com/34921497/55379841-e9798f00-553b-11e9-9e50-3210baf8d70d.png">

the above image is my requirement

**Comment by soommy12** [comment]
The `setStep()` is telling the library which labels to create. For this specific example, after using `setStep(2)` the last label doesn't exist so the `setShowLastLabel()` has no effect. It was also described [here](https://github.com/highcharts/highcharts/issues/9275#issuecomment-479000268) (along with the example workaround which you should use passing JS function to `HIFunction` object as String parameter).

**Comment by ArunVicky001** [comment]
Following the reference you mentioned above I did like this but it's not working 
`String xAxisSetStep = "xAxis: { categories: [ ... ], labels: { formatter: function () { return this.pos % 2 && !this.isLast ? '' : this.value; } } }";
        HIFunction setStep = new HIFunction(xAxisSetStep);
        xaxis.getLabels().setFormatter(setStep);`

could you please tell how to do that

**Comment by soommy12** [comment]
Yes, sure. According to the field names you should copy just formatter to your String :)

**Comment by ArunVicky001** [comment]
Like the way I did above?

**Comment by ArunVicky001** [comment]
you meant to give the string like this 

`String xAxisSetStep = "formatter: function () { return this.pos % 2 && !this.isLast ? '' : this.value; }";`

**Comment by soommy12** [comment]
According to the [docs ](https://api.highcharts.com/android/highcharts/com/highsoft/highcharts/core/HIFunction.html)you can pass pure Javascript function via constructor in String format. You should do it like this:
```
String jsFunction = "function () { return this.pos % 2 && !this.isLast ? '' : this.value; }";
HIFunction fun = new HIFunction(jsFunction);
```

**Comment by ArunVicky001** [comment]
Thank you! it's working.

**Comment by ArunVicky001** [comment]
HI Soommy, 

Here am facing one more issue if the xAxis count is more than 30 again the xAxis label is not displaying, Could you please help me on how to solve this issue ?
