### ISSUE TITLE
HighChart with 50000 data Sample Android Code

### ISSUE THREAD

**Issue by gauravgupta188** [highcharts/highcharts-android#86]
We are using the Android sample code of HIghchart for data more than 50k. I tried to download HICharts Sample code and run with fewer data like 4000, it's working fine. But when I test with 10000 data points, its showing blank space in first time, When I tried to zoom in, all points become visible and behave as expected.
I asked the same question on StackOverflow and didn't get any solution [StackOverflow Question link](https://stackoverflow.com/questions/55103001/android-highchart-not-loading-data-first-time-with-50k-points)

`
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        HIChartView chartView = findViewById(R.id.hc);

        chartView.plugins = new ArrayList<>(Arrays.asList("boost"));

        HIOptions options = new HIOptions();

        HIChart chart = new HIChart();
        chart.setType("line");
        chart.setZoomType("x");
        options.setChart(chart);

        HIBoost boost = new HIBoost();
        boost.setUseGPUTranslations(true);
        options.setBoost(boost);

        HITitle title = new HITitle();
        title.setText("Highcharts drawing 500 points");
        options.setTitle(title);

        HISubtitle subtitle = new HISubtitle();
        subtitle.setText("Using the Boost module");
        options.setSubtitle(subtitle);

        HITooltip tooltip = new HITooltip();
        tooltip.setValueDecimals(2);
        options.setTooltip(tooltip);

        HILine line = new HILine();
        line.setData(data());

        line.setLineWidth(0.5);
        options.setSeries(new ArrayList<HISeries>(Collections.singletonList(line)));

        chartView.setOptions(options);
    }

    private ArrayList<Number[]> data(){
        ArrayList<Number[]> dataList = new ArrayList<>();
        for (int i = 0; i < 8000; i++) {
            double random = Math.random() * 49 + 1;
            Number[] number = new Number[2];
            number[0]=i;
            number[1]=random;
            dataList.add(number);
        }
        Log.d("info","array Size:"+dataList.size());
        return dataList;
    }
}
`

This is the sample code provided by HICharts(without loop).In LogCat this is the HICharts [www.highcharts.com/errors/26] (www.highcharts.com/errors/26)

I tried with IOS version too and it is working fine. It seems issue exists only in Android.

**Comment by soommy12** [comment]
Hello @gauravgupta188 ! Thanks for your report. I will look into it.

**Comment by gauravgupta188** [comment]
@soommy12  Waiting for your reply.

**Comment by soommy12** [comment]
Sorry for late response @gauravgupta188. It seems  `boos-canvas.js` is not working properly on Android devices. It needs further investigation. Unfortunately, we have no ETA for this yet.

**Comment by MikolajMichalczak** [comment]
This issue is no longer relevant in the 11.4.1 version.
