### ISSUE TITLE
scrollablePlotArea does not provide vertical scroll for bar type chart

### ISSUE THREAD

**Issue by SSJ2912** [highcharts/highcharts-android#88]
Scrollable Plot area usually provides scroll over the X Axis for all the charts. But for Bar chart the X-Axis is Vertical and ScrollablePlotArea provides scroll horizontally. Is there any way to provide the scroll vertically( along X-Axis)?

**Comment by soommy12** [comment]
Hello @SSJ2912 . Can you please share some example for what you want to achieve?

**Comment by SSJ2912** [comment]
@soommy12 , 
when I have many element in xCategory, it skips some elements while displaying. And when I use scrollablePlotArea , the scrolling is not provided along the x-Axis

![tempFileForShare_20190430-165450](https://user-images.githubusercontent.com/38619144/56958726-bfca7c80-6b68-11e9-9c71-1cfc69775b53.jpg)

code :

```
val categoriesList = arrayListOf("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
                "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
                "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
                "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
        )
 val pie = HISeries()
        pie.name = "Brands"
        val dataList = arrayListOf<HashMap<String , Any>>()
        for(i in 0 until categoriesList.size)
        {
            val map1 = hashMapOf<String , Any>()
            map1.put("name", "yolo$i")
            map1.put("y", Random.nextInt(20 , 100))
            dataList.add(map1)
        }
        pie.data = dataList

        options.series = arrayListOf(pie)

        options.chart.scrollablePlotArea = HIScrollablePlotArea()
        options.chart.scrollablePlotArea.minWidth = 700
        options.chart.scrollablePlotArea.scrollPositionX = 0

```

**Comment by SSJ2912** [comment]
@soommy12 , Could you please help me sort out this problem?

**Comment by soommy12** [comment]
Sorry for your inconvenience @SSJ2912 , I was on holiday break. Gonna try to reproduce your problem now.

**Comment by soommy12** [comment]
@SSJ2912 It appears to be a bug in the core library. The issue is submitted already [there](https://github.com/highcharts/highcharts/issues/10763).
