### ISSUE TITLE
Referenced canvag.js and pro4.js modules cannot be found

### ISSUE THREAD

**Issue by adenisyuk** [highcharts/highcharts-android#89]
Used Highcharts version: 7.1.1

Here are errors logged when HIChartView is inflated:

...E/AndroidProtocolHandler: Unable to open asset URL: file:///android_asset/js/lib/canvag.js
...E/AndroidProtocolHandler: Unable to open asset URL: file:///android_asset/js/lib/pro4.js

As i see in bundled library assets, the correct modules names are `canvg` and `proj4`

**Comment by soommy12** [comment]
Hi @adenisyuk ! Thanks for your report. That's indeed unfortunate spelling mistake. Definitely needs a fix.

**Comment by adenisyuk** [comment]
Hi @soommy12 , is it resolved somehow or just silently closed? :)

**Comment by soommy12** [comment]
The fix was introduced in the newest release. You can find it marked in the [changelog](https://github.com/highcharts/highcharts-android/releases).
