### ISSUE TITLE
i get  error: cannot find symbol variable type,plotBackgroundColor,plotBorderWidth,plotShadow,chart ,pointFormat,tooltip,pie etc

### ISSUE THREAD

**Issue by kishorkumar55** [highcharts/highcharts-android#9]
i used highcharts lib opetion 'A'.But i get some error like error: cannot find symbol variable type,plotBackgroundColor,plotBorderWidth,plotShadow,chart ,pointFormat,tooltip,pie etc all the veriable can't find.so plz tell me how to resolve that error.
eg:-
Error:(52, 20) error: cannot find symbol variable pie
Error:(45, 16) error: cannot find symbol variable tooltip
Error:(48, 20) error: cannot find symbol variable pie
Error:(90, 18) error: cannot find symbol variable options
Error:(34, 14) error: cannot find symbol variable plotBackgroundColor
Error:(50, 20) error: cannot find symbol variable pie
Error:(49, 20) error: cannot find symbol variable pie
Error:(85, 16) error: cannot find symbol variable data
Error:(54, 16) error: cannot find symbol variable plotOptions
Error:(35, 14) error: cannot find symbol variable plotBorderWidth
Error:(44, 16) error: cannot find symbol variable pointFormat
Error:(36, 14) error: cannot find symbol variable plotShadow
Error:(41, 16) error: cannot find symbol variable title
Error:(53, 20) error: cannot find symbol variable pie
Error:(57, 16) error: cannot find symbol variable name
Error:(51, 20) error: cannot find symbol variable pie
Error:(40, 14) error: cannot find symbol variable text
Error:(37, 16) error: cannot find symbol variable chart
Error:(87, 16) error: cannot find symbol variable series
Error:(33, 14) error: cannot find symbol variable type

**Comment by soommy12** [comment]
There was an update. You need to use version `6.1r` (just add `r` to the version number in your dependency). The way of creating the chart is different now - we use getters and setters to establish the chart properties. Check out the new readme and documentation.

**Comment by kishorkumar55** [comment]
I used  compile 'com.highsoft.highcharts:highcharts:6.1r' that dependency but i can't resolve that error.
I also add
repositories {
    maven { url "https://jitpack.io" }
}
but still gives error.

**Comment by soommy12** [comment]
That's wrong then. What you need to do is add this repository:

`repositories {
    maven {
        url "https://highsoft.bintray.com/Highcharts"
    }
}`

and dependency which you posted already. After the update, you need to use a setter to assign the value. So, in easy words, instead of:

```
HISpline series = new HISpline();
series.data = new ArrayList<>(Arrays.asList(0,5,8,9,3,5,4,4,2,10));
options.series = new ArrayList<>(Collections.singletonList(series));

```
You should do:

```
HISpline series = new HISpline();
series.setData(new ArrayList<>(Arrays.asList(0,5,8,9,3,5,4,4,2,10)));
options.setSeries(new ArrayList<>(Collections.singletonList(series)));
```
