### ISSUE TITLE
Highcharts on Android Studio 3.4

### ISSUE THREAD

**Issue by alkhor82** [highcharts/highcharts-android#90]
Sawadee ;-)

Does HIGHCHARTS work on android? (not a webview)
I have Android 3.4
But this example does not work for me:
https://github.com/highcharts/highcharts-android/tree/master/Example/HighFit

Can you share a ready demo for testing

Thanks

**Comment by soommy12** [comment]
Hi @alkhor82 ! Thanks for your question. The lowest supported Android version is 4.4. It was already discussed [here](https://github.com/highcharts/highcharts-android/issues/30). As the Highcharts Android must use WebView under the hood and it needs some WebView methods which were introduced in API 19 there is no possibility to support lower versions.

**Comment by alkhor82** [comment]
Ty Bartek przejdźmy na nasz język, w końcu Polacy nie gęsi i też swój język mają ;-)
Ty jesteś jedną z osób pracujących nad biblioteką highcharts?

Co do tej wtyczki chciałem ją przetestować w działaniu na Androidzie na telefonie. Pobrałem najnowszą bibliotekę i wg instrukcji chciałem na początku odpalić przykład jaki jest opisywany tutaj:
https://github.com/highcharts/highcharts-android

Ale ciągle jakieś są problemy. Nawet otwierałem projekt z ww. linku, demo przykład aby tylko uruchomić i zobaczyć w działaniu aplikację, ale jak piszę Android Studio wywala mi błędy. Przy odpalaniu tej apki w Android Studio (ten przykład gotowy w ww. linku) dostaję taki komunikat:
Jack compilation exception
Kombinowałem już na wiele sposobów, ale nie wiem czy u mnie jest coś nie tak czy to może coś z tą biblioteką jest nie tak pod Android Studio 3.4

Może są gdzieś jakieś inne przykłady proste tak aby tylko wczytać do Android Studio i móc to uruchomić aby zapoznać się z tą biblioteką.
Z biblioteką na www nie ma problemu, ale na Androida nie mogę jej okiełznać.

I jeszcze jedno pytanie jest taki wykres:
https://www.highcharts.com/android/demo/spline-irregular-time
na strony www serie danych są prezentowane w kodzie tak:
series: [{
        name: "Winter 2014-2015",
        data: [
            [Date.UTC(1970, 10, 25), 0],
            [Date.UTC(1970, 11,  6), 0.25],     
            [Date.UTC(1971, 6,  4), 0]
        ]
    },

Na urządzenia mobilne w Javie serie są podawane w taki już sposób, ale jak określono tutaj dzień i rok:
{ 26524800000L, 0.28 }, 
HISpline series1 = new HISpline();
		series1.setName("Winter 2012-2013");
		Number[][] series1_data = new Number[][] { { 25315200000L, 0 }, { 26524800000L, 0.28 }, { 26956800000L, 0.25 }, { 28512000000L, 0.2 }, { 28944000000L, 0.28 }, { 31017600000L, 0.28 }, { 31276800000L, 0.47 }, { 32400000000L, 0.79 }, { 33696000000L, 0.72 }, { 34387200000L, 1.02 }, { 35078400000L, 1.12 }, { 36288000000L, 1.2 }, { 37497600000L, 1.18 }, { 40176000000L, 1.19 }, { 41904000000L, 1.85 }, { 42249600000L, 2.22 }, { 43459200000L, 1.15 }, { 44755200000L, 0 } };
		series1.setData(new ArrayList<>(Arrays.asList(series1_data)));

Nie da się tego zapisać w jakiś prosty sposób tak jak w JavaScript?
To tak dodatkowo. Na razie walczę z odpaleniem demo w Android Studio, ale nie mogę tego przejść, a druga sprawa nie rozumiem tych serii z Java jak one są zapisywane.

**Comment by alkhor82** [comment]
p.s. pisząc I have Android 3.4 chodziło mi o Android Studio.
Nie sformatowałem wypowiedzi, ale Windowsowy IE już nie radzi sobie na wielu stronach, także moja wypowidź jest jak jest.

**Comment by soommy12** [comment]
As the issue tracker is available globally for everyone, we have to use English here.

When it comes to run the project on Android 3.4. I just downloaded and installed Android Studio 3.4 on a fresh machine and it works smoothly. Are you sure you didn't mess up with configuration files (gradle.properties, build.gradle) ? It would be great to see the entire stack trace.

Speaking of series. Those are just dates in milliseconds. You can pass a Date object as well.

**Comment by alkhor82** [comment]
Hmm… w wolnym czasie wezmę się raz jeszcze za to, ale chciałbym Ci się zapytać (nie ma jak tu wysyłać prywatnych wiadomości więc piszę z języku zrozumiałym dla nas tylko) nie chciałbyś napisać tutoriala jak uruchomić tą bibliotekę i odpalić, ale ten typ wykresu:
https://www.highcharts.com/android/demo/spline-irregular-time
Chodzi o tutorial od 0 omawiający jak stworzyć apkę na AS 3.4 oraz jak wstawić do niej bibliotekę highcharts prezentując wykres, który podałem w linku z tym, że zamieniając dane na zrozumiałe daty.

Zlecenie płatne, także jak byłbyś zainteresowany to napisz do mnie na adres mail w linku ze zdjęciem:
https://s2.ifotos.pl/mini/alkmailJP_qshwpxw.jpg

**Comment by soommy12** [comment]
I've made a tutorial already, you can find it [here](https://www.highcharts.com/blog/post/highcharts-android-wrapper-tutorial/).
