### ISSUE TITLE
How to achieve Plotoptions mouse click, mouse out, mouseover events

### ISSUE THREAD

**Issue by ArunVicky001** [highcharts/highcharts-android#92]
In my chart I want to fire the event when I click plot area, I tried like below but its not trigger 

Could you please tell how to do it in correct way 

` HIPlotOptions plotoptions = new HIPlotOptions();
        plotoptions.setSeries(new HISeries());
        plotoptions.getSeries().setAllowPointSelect(true);
        plotoptions.getSeries().setPoint(new HIPoint());
        plotoptions.getSeries().getPoint().setEvents(new HIEvents());
        plotoptions.getSeries().getPoint().getEvents().setClick(new HIFunction(
                f -> {
                    Toast t = Toast.makeText(
                            this,
                            "Clicked Events [ " + f.getProperty("x") + ", " + f.getProperty("y") + " ]",
                            Toast.LENGTH_SHORT);
                    t.show();
                },
                new String[]{"x"}
        ));
        options.setPlotOptions(plotoptions);`

**Comment by soommy12** [comment]
Hi @ArunVicky001 ! I tried your code and it works properly. The only think you lack is `y` in your array:
`new String[]{"x", "y"}`
