### ISSUE TITLE
No graph is displayed when large height is set to HIChartView

### ISSUE THREAD

**Issue by pradeep2424** [highcharts/highcharts-android#93]
When I am setting height 1500dp or more than 1500dp to HIChartView in XML then no graph is displayed.

Code:-
 <com.highsoft.highcharts.core.HIChartView
                android:id="@+id/hc"
                android:layout_width="match_parent"
                android:layout_height="1500dp"/>

**Comment by soommy12** [comment]
Hello @pradeep2424 ! `dp` is an abstract unit that is based on the physical density of the screen. If you set the view height to 1500dp it is probably much more than your device can support. That's said, the `HIChartView` tries to draw itself in dimension which your device does not support. Under the hood, the `HIChartView` is a container for the actual generated chart, its dimensions are dependent from `HIChartView` width and height. That is why the wrapper generates a chart which is not visible for you. For best effect, I suggest using `match_parent` instead.

**Comment by pradeep2424** [comment]
I have multiple horizontal bar graphs in RecyclerView. Hence I can not use match_parent inside adapter. I tried using wrap_content but I came to know from your support team that wrap_content won't work with HIChartView.

Also my Horizontal graph can have 200 to 250 bars and I  want my graph to adjust height automatically depending on number of bars. So how can I achieve that inside RecyclerView because I can't use wrap_content  according to your support team.

**Comment by soommy12** [comment]
You can set `match_parent` for `HIChartView` and play around with its container (`RecyclerView` or anything else) then the chart should fill it properly. The other solution is using `scrollablePlotArea` but this is quite a different approach. If you want to have all series visible in your chart you should always use `match_parent` for `HIChartView` which should be placed in a container.

**Comment by pradeep2424** [comment]
I can't use match_parent on HIChartView, because there are lot of other views (like button, images, textviews) are on that page.
So if I set match_parent to HIChartView then all the other views gets overlapped by graph.

**Comment by soommy12** [comment]
Hmm, that sounds very strange. Gonna look how the `HIChartView` dimensions are set under the hood and test it in detail.

**Comment by pradeep2424** [comment]
Now I am trying to change HIChartView height multiple times on same page using below code
``` 
1) chartView.getLayoutParams().height = 300;
2) chartView.getLayoutParams().height = 500;
3) chartView.getLayoutParams().height = 700;
```
only first time height changes. After that HIChartView is not changing its height.
