### ISSUE TITLE
Labels are overlapping HIChartView Bar

### ISSUE THREAD

**Issue by pradeep2424** [highcharts/highcharts-android#95]
I am setting margin left to Horizontal bar so that Axis is displayed at fixed position from left.
code:-
```chart.setMarginLeft(60);```
But when my horizontal bar labels are large then starting characters are eliminated by graph.

Then I tried adding "left" alignment to the Labels but then my labels are overlapping Bar graph.
code:-
```HILabels hiLabels1 = new HILabels();  
hiLabels1.setAlign("left");

HIXAxis xAxis = new HIXAxis();
xAxis.setLabels(hiLabels1);
```
**What I want is whenever there is large text for label then label should display some starting characters then followed by "..." indicating that there is more text. And I want to keep fixed left margin of graph to 60.**
Can you please suggest me a proper way to achieve this.

I am attaching screenshots below.
![Alignment](https://user-images.githubusercontent.com/31762483/58304803-7b529980-7e13-11e9-8308-a08efa1a0993.png)
![Without_Alignment](https://user-images.githubusercontent.com/31762483/58304805-7b529980-7e13-11e9-9a82-66a0b65125a1.png)

**Comment by soommy12** [comment]
Hi @pradeep2424 ! Thanks for your question. The best solution for your problem will be `useHTML` flag with proper format. Check it out:
```
hiLabels1.setUseHTML(true);
hiLabels1.setFormat("<span style="display:block; width: 40px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{value}</span>");
```

**Comment by pradeep2424** [comment]
Thank you. This is working great now. But now another problem is I can display label text only in single line. How can I get it in 2 lines.

**Comment by soommy12** [comment]
Well, now it's more about your string manipulation and format than Highcharts options. You can try to make a substring, new line, add dots manually, everything in the `setFormat()` method.
