### ISSUE TITLE
HIDataLabelsOptionsObject dataLabels.setStyle with HIStyle is not working in the version 7.1.1

### ISSUE THREAD

**Issue by ArunVicky001** [highcharts/highcharts-android#97]
Hi, 

In the latest updated version 7.1.1, I could see there is change in styling and HIDataLabels class has removed instead HIDataLabelsOptionsObject class has been introduced , 

If I set the HIStyle to the HIDataLabelsOptionsObject like below its throwing me an error in the runtime 

```
 HIStyle dataLableStyle = new HIStyle();
 dataLableStyle.setFontSize("10px");
  HIDataLabelsOptionsObject dataLabels = new HIDataLabelsOptionsObject();
        dataLabels.setEnabled(true);
        dataLabels.setCrop(false);
        dataLabels.setAllowOverlap(false);
        dataLabels.setUseHTML(true);
        String jsfunction = "function() { var percentile = Number(((this.y - this.point.prior) / this.point.prior * 100).toFixed(0)); var yData = this.y; if (yData > 100) { yData = Highcharts.numberFormat(yData, 0, ',', ','); } var labelValue; var percent = percentile; labelValue = '<span style = ' + 'color:#000' + '>'+yData+'</span>'; if (yData == 0) { labelValue += ''; } else { labelValue += '<span style =' + 'color:#e28507' + ';font-weight:bold' + '>' + ' : ' + percent + '</span>'; } return labelValue; }";

        HIFunction labelFormatter = new HIFunction(jsfunction);
        dataLabels.setFormatter(labelFormatter);

        dataLabels.setStyle(dataLableStyle);
```

getting the below exception 
 `java.lang.IllegalArgumentException: class com.highsoft.highcharts.common.hichartsclasses.HIStyle declares multiple JSON fields named d`

Could you please me solve this issue 

Thanks

**Comment by soommy12** [comment]
Hello @ArunVicky001 ! Thanks for reporting this issue. I'm currently investigating it.

**Comment by soommy12** [comment]
I have to admit, this is a bug. There was a problem with the serialization of `HIDataLabelsOptionsObject` to options. The fix is already done. We will introduce it in the next release.

**Comment by ArunVicky001** [comment]
Thanks for your response!

**Comment by soommy12** [comment]
Hello @ArunVicky001 . In the current release, the **data labels style** takes an `HICSSObject` as an argument now.
