### ISSUE TITLE
Program type already present: com.highsoft.highcharts.common.HIChartsJSONSerializable Message{kind=ERROR, text=Program type already present: com.highsoft.highcharts.common.HIChartsJSONSerializable, sources=[Unknown source file], tool name=Optional.of(D8)}

### ISSUE THREAD

**Issue by paul035** [highcharts/highcharts-android#99]
This is my app/build.gradle file :

apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.android.highchartexample"
        minSdkVersion 22
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

repositories {
    maven {
        url "https://highsoft.bintray.com/Highcharts"
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.+'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'com.highsoft.highcharts:highcharts:7.0.3'
    implementation (name: 'highcharts-release', ext:'aar')
    implementation 'com.google.code.gson:gson:2.8.1'
    implementation 'com.google.guava:guava:27.0.1-android'

}

**Comment by soommy12** [comment]
Hello @paul035 ! You have added `Highcharts` library twice. You should choose between local aar or bintray version. For being always up to date I recommend [choosing option A)](https://github.com/highcharts/highcharts-android#preparing-your-project) described in readme.

**Comment by paul035** [comment]
![Inked1_LI](https://user-images.githubusercontent.com/46248156/58871630-09663400-86e0-11e9-8b2a-9852f75c476d.jpg)

When I'm clicking the above Hamburger button (Highlighted button) my app crashes. Can you please help me with this.

**Comment by soommy12** [comment]
Yes, sure. This is button is running chart export. There are two options. You can disable export by
```
HIExporting exporting = new HIExporting();
exporting.setEnabled(false);
options.setExporting(exporting);
```
Or, if you want to export your chart, set up provider, which is described [here](https://github.com/highcharts/highcharts-android#export-module-requirements).
